openwallet-foundation/credo-ts

.gitignore
README.md
package.json
tsconfig.json
yarn.lock

We are obviously not ready to official npm package distribution, but I would like to try and therefore test the library API continuously outside from different project, so I prepared this packaging to create `.tgz` file to add it as a dependency in other projects. I also added some formatting and linting scripts to prevent mistakes when committing or packaging.

Add npm packaging setup

---

src/lib/__tests__/agents.test.ts
src/lib/agent/Agent.ts
src/lib/helpers.ts
src/lib/index.ts
src/lib/protocols/basicmessage/BasicMessageService.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/connections/domain/Connection.ts
src/lib/protocols/connections/domain/ConnectionState.ts
src/lib/protocols/connections/domain/DidDoc.ts
src/lib/protocols/connections/domain/InvitationDetails.ts
src/lib/protocols/connections/messages.ts
src/lib/protocols/helpers.ts
src/lib/protocols/routing/ProviderRoutingService.ts
src/lib/testUtils.ts
src/lib/types.ts
src/samples/__tests__/e2e.test.ts
types/indy-sdk/jest.d.ts

When I tried to use this library from UI client I realize it could be great to utilize the concept of JS and Node events emitting to listen on particular events and update UI accordingly. I start with the connection state update and we’ll see where it bring us. To be honest, I think of it partially as an experiment.  It’s still in question whether event emitter should be a connection, connection service, agent or something else.

Change connection interface to event emitter

---

src/lib/decorators.test.ts
src/lib/decorators.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/connections/domain/Connection.ts
src/lib/testUtils.ts
src/lib/wallet/IndyWallet.ts
src/lib/wallet/Wallet.ts
src/samples/__tests__/e2e.test.ts
types/indy-sdk/index.d.ts

The most amount of code is related to the extraction and generalization signature verification of connection response message, now it should work for all and not only connection related messages. 
Overall, it's more changes than I originally expected, but you can see smaller bits of changes looking into separate commits if you want:
* Encapsulate theirKey attribute, remove unsed code and update types
* Encapsulate did exchange connection object
* Extract connection response signature verification into decorators

Refactoring of connection service

---

src/lib/decorators.test.ts
src/lib/decorators.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/connections/domain/Connection.ts
src/lib/protocols/connections/messages.ts
src/lib/protocols/helpers.ts
src/lib/timestamp.ts
src/samples/__tests__/e2e.test.ts

Switches to the [Aries Connection Protocol](https://github.com/hyperledger/aries-rfcs/tree/04ce2e2b0f956f2b3dcdad8298c6c039b31b57bc/features/0160-connection-protocol).
P.S. I'm aware of message type prefixes [being changed](https://github.com/hyperledger/aries-rfcs/blob/1d676fa8630a4b659ed5d175ea3b0043c6e83016/features/0348-transition-msg-type-to-https/README.md) but that can be accommodated in a future PR. Deadline for that is end of February.

ConnectionService: Use Connection Protocol

---

package.json
src/lib/decorators.test.ts
src/lib/decorators.ts

Aries RFC 0234 requires signature decorators to encode fields
using base64url instead of base64
Refer https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/README.md

decorators: use base64url

---

src/lib/agent/Agent.ts
src/lib/handlers/acks/AckMessageHandler.ts
src/lib/handlers/basicmessage/BasicMessageHandler.ts
src/lib/handlers/connections/ConnectionRequestHandler.ts
src/lib/handlers/connections/ConnectionResponseHandler.ts
src/lib/handlers/connections/InvitationHandler.ts
src/lib/handlers/routing/ForwardHandler.ts
src/lib/handlers/routing/RouteUpdateHandler.ts
src/lib/handlers/trustping/TrustPingMessageHandler.ts
src/lib/handlers/trustping/TrustPingResponseMessageHandler.ts
src/lib/protocols/trustping/TrustPingService.ts
yarn.lock

Solves #22 
I would like to keep it in `handlers` folder and not in `protocols`, at least for now, because I want to preserve fewer dependencies between protocols. I would like to make protocols independent of each other, not sure whether it's even achievable, I feel it's a good direction to go.
Signed-off-by: jakubkoci <jakub.koci@gmail.com>

Group hanlders by protocol

---

README.md
package.json

@gnarula I was confused because the agency didn't log anything and didn't know what was the reason :) So I'm just adding debug logs as default and mentioning the option to turn-off logs in docs.
Signed-off-by: jakubkoci <jakub.koci@gmail.com>

Add env to run agency with debug logs

---

package.json
src/lib/__tests__/agents.test.ts
src/lib/agent/Agent.ts
src/lib/index.ts
src/samples/__tests__/e2e.test.ts
src/samples/agency.ts
yarn.lock

As a Developer, I want to get `connection` object when I generate or accept invitation to work with this instance right away and don't have to call `getConnections()` and search in all connections in agent instance. 
There are also more deletions than additions so it seems like a good approach.
We can also add some identifier (`id`) attribute, perhaps generated uuid, for every connection object as a next step.

Return connection object instead of just invitation URL

---

package.json
src/lib/__tests__/agents.test.ts
src/lib/agent/Agent.ts
src/lib/handlers/basicmessage/BasicMessageHandler.ts
src/lib/handlers/routing/RouteUpdateHandler.ts
src/lib/handlers/trustping/TrustPingMessageHandler.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/connections/domain/Connection.ts
src/lib/storage/ConnectionRecord.ts

I'm adding persistence to connections. I don't see it as a final solution for 2 reasons, but let's put it there for the reference at least. These reasons are:
1. It still preserves the in-memory connections array. The reason is that we use connection object as emitter and when retrieving a connection from the database we're creating a new object and then a new instance of an event emitter, therefore there could be two instances of same connection with different listeners. So, I load all connections into an array (memory) and use only in-memory instances, but updating the database for every change. 
2. I feel there is to much duplication between `Connection`, `ConnectionRecord`,  `ConnectionProps` and `ConnectionStorageProps` objects. We won't probably have only one class, interface, but …

Add connections persistence

---

src/lib/agent/Agent.ts
src/lib/agent/Dispatcher.ts
src/lib/handlers/Handler.ts
src/lib/handlers/acks/AckMessageHandler.ts
src/lib/handlers/basicmessage/BasicMessageHandler.ts
src/lib/handlers/connections/ConnectionRequestHandler.ts
src/lib/handlers/connections/ConnectionResponseHandler.ts
src/lib/handlers/connections/InvitationHandler.ts
src/lib/handlers/messagepickup/MessagePickupHandler.ts
src/lib/handlers/routing/ForwardHandler.ts
src/lib/handlers/routing/RouteUpdateHandler.ts
src/lib/handlers/trustping/TrustPingMessageHandler.ts
src/lib/handlers/trustping/TrustPingResponseMessageHandler.ts
src/lib/protocols/connections/messages.ts

This PR adds a `supportedMessageTypes` to the `Handler` interface that every handler must implement. Inspired by the .NET implementation.
Now the handler defines which message types it supports instead of declaring this in the agent. I think it fits better in the handler as the handler is coupled to which message types it support.
This also makes the agent class a bit smaller, and will help in the future with pluggable protocol handlers.

add supported message types to handlers

---

src/lib/__tests__/agents.test.ts
src/lib/agent/Agent.ts
src/lib/agent/Dispatcher.ts
src/lib/modules/BasicMessagesModule.ts
src/lib/modules/ConnectionsModule.ts
src/lib/modules/RoutingModule.ts
src/lib/protocols/basicmessage/BasicMessageService.ts
src/samples/__tests__/e2e.test.ts
src/samples/agency.ts

I'm extracting some methods from the Agent class to particular modules. These modules are currently more like Facade but could eventually evolve to standalone modules, consuming services, encapsulate handlers, providing services. I don't see it as necessary to go this direction right now. 
Modules also work as a public framework API, available via Agent object properties:
- `connections`
- `routing`
- `basicMessages`

Extract methods from Agent to particular Module

---

.dockerignore
Dockerfile
README.md
docker-compose.yml
package.json
run.sh

docker setup now allows to run tests in the docker files. It also makes use of a base indy-nodejs image to reduce build times
to test (from README):
```sh
docker build -t aries-framework-javascript .
docker run -it --rm aries-framework-javascript  yarn test -t "agents"
docker-compose up # Run alice-agency and bob-agency
docker run -it --rm --network host aries-framework-javascript yarn test
```

improve docker setup

---

src/lib/agent/Agent.ts
src/lib/agent/Dispatcher.ts
src/lib/agent/MessageReceiver.ts
src/lib/agent/MessageSender.ts
src/lib/agent/models/InboundMessageContext.ts
src/lib/agent/models/MessageContext.ts
src/lib/handlers/Handler.ts
src/lib/handlers/basicmessage/BasicMessageHandler.ts
src/lib/handlers/connections/ConnectionRequestHandler.ts
src/lib/handlers/coordinatemediation/KeylistUpdateHandler.ts
src/lib/handlers/messagepickup/MessagePickupHandler.ts
src/lib/handlers/routing/ForwardHandler.ts
src/lib/handlers/trustping/TrustPingMessageHandler.ts
src/lib/modules/RoutingModule.ts
src/lib/protocols/basicmessage/BasicMessageService.test.ts
src/lib/protocols/basicmessage/BasicMessageService.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/messagepickup/MessagePickupService.ts
src/lib/protocols/routing/ProviderRoutingService.ts
src/lib/protocols/trustping/TrustPingService.ts
src/lib/types.ts

adds a message context class that is populated after a message is received. If found, it attaches the connection record associated with the message to the context.
I started to work on replacing the verkey with connection_id (which we apparently already have?, but is not used everywhere) but felt this could help avoid repetitive patterns of each handler retrieving the connection associated with the message.

replace inbound message with message context

---

package.json
src/lib/__tests__/agents.test.ts
src/lib/agent/AgentMessage.ts
src/lib/agent/BaseMessage.ts
src/lib/agent/ProvisioningService.ts
src/lib/modules/ConnectionsModule.ts
src/lib/modules/RoutingModule.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/storage/ProvisioningRecord.ts
src/samples/__tests__/e2e.test.ts

Seems the connection already had an id. Verkey wasn't used that much, so pretty small change after all.
Fixes #70

Replace verkey with connection id

---

.github/workflows/continuous-integration.yml
.gitignore

Replacement for #85. This only adds the Github actions pipeline, but doesn't remove the azure pipeline yet. Although current master doesn't use the ledger yet, it will work when #82 is merged.
Currently the ledger doesn't have a TAA due to a bug in von network, but I already opened a PR for that. We just have to wait for it to get merged to test with TAA: https://github.com/bcgov/von-network/pull/126.
However this showed something: we need to apply custom logic if there is no TAA on the ledger. In this case we don't need to append to the TAA, and it will fail if we do. I'll add the required changes to the credential schema branch.

add github actions pipeline

---

src/lib/utils/did.test.ts
src/lib/utils/did.ts

The regexes for DID and verkey were not 100% correct. They specified a length of 22 and 44 characters, but they can also be 21 and 43 characters (I don't know why).
I've added a 43 character verkey and a 21 character did identifier to the tests. This are definitely valid as they are generated from `000000000000000000000000Trustee8` seed
Discovered after reading: https://hackmd.io/2IKUPROnRXW57Lmal_SGaQ

fix did and verkey regexes and add tests

---

src/lib/__tests__/credentials.test.ts
src/lib/__tests__/ledger.test.ts
src/lib/agent/Agent.ts
src/lib/agent/AgentConfig.ts
src/lib/types.ts

This is a small change that automatically connect to the ledger pool (instead of manually needing to do it) if `genesisPath` configuration is set. It is backwards compatible (by manually calling `ledger.connect`). 
In the future I'll like to optimise this to only connect when the pool is actually needed, but this way the configuration and API is already available. The optimisation can be an internal change. Maybe we can take a similar approach as Aries Framework .NET that uses an awaitable pool that initialises when you retrieve it.
Fixes #88

auto init ledger pool if genesisPath is configured

---

src/lib/__tests__/credentials.test.ts
src/lib/__tests__/ledger.test.ts
src/lib/agent/LedgerService.ts
src/lib/handlers/credentials/CredentialResponseHandler.ts
src/lib/modules/CredentialsModule.ts

Only return the objects for `getCredentialSchema` and `getCredentialDefinition` instead of both object and id
Fixes #105

only return object for get schema and cred def

---

src/lib/protocols/connections/ConnectionService.ts
src/lib/storage/BaseRecord.ts
src/lib/storage/BasicMessageRecord.ts
src/lib/storage/ConnectionRecord.ts
src/lib/storage/CredentialRecord.ts
src/lib/storage/IndyStorageService.test.ts
src/lib/storage/ProvisioningRecord.ts

I needed to move `createAt` attribute initialization up in the inheritance chain to every particular record. I'm not sure if this is a good approach in the long-term but it at least fixes the issue for now. I also aligned `id` attribute initialization across all records, so even if this is a wrong approach we have it wrong in the same way everywhere :)

fix: Correctly persist createdAt attribute

---

src/lib/handlers/trustping/TrustPingMessageHandler.ts
src/lib/index.ts
src/lib/protocols/connections/ConnectionService.test.ts
src/lib/protocols/connections/ConnectionService.ts

This removes the `did:sov` prefix from dids to be interoperable with ACA-Py. It also contains some other fixes to make AFJ usable in AATH.
Fixes #124

use dids without prefix for connections

---

src/lib/handlers/credentials/CredentialRequestHandler.ts
src/lib/modules/CredentialsModule.ts
src/lib/protocols/credentials/CredentialService.ts
src/lib/protocols/credentials/__tests__/CredentialService.test.ts

Small changes in credential service method signatures, renaming params, add typing. This PR together with #122 fixes #117.

refactor: Credential service method signatures

---

src/lib/handlers/credentials/CredentialOfferHandler.ts
src/lib/handlers/credentials/CredentialRequestHandler.ts
src/lib/handlers/credentials/CredentialResponseHandler.ts
src/lib/modules/CredentialsModule.ts
src/lib/protocols/credentials/CredentialService.ts
src/lib/protocols/credentials/__tests__/CredentialService.test.ts

I added validation to every credential service method, not sure if it is necessary. I use different parametrized tests than `jest.each`. I'm aware that's not so simple to read in this way, but I wanted to have just one test for every invalid state. This should fix #123.
I also added two unrelated tests for credential record attributes.

feat: Validate credential record state transitions

---

src/lib/protocols/credentials/CredentialService.ts
src/lib/protocols/credentials/__tests__/StubWallet.ts
src/lib/wallet/IndyWallet.ts
src/lib/wallet/Wallet.ts

Taken from the [ACA-Py implementation](https://github.com/hyperledger/aries-cloudagent-python/blob/ec9871f84d1faae696284c1d399ff8e4eb1f86e7/aries_cloudagent/wallet/indy.py#L278-L289). They create a master secret on wallet open that uses the same id as the wallet.
The current method created a master secret for each credential, with the same id. Which wouldn't allow to request more than one credential because the second time `proverCreateMasterSecret` would be called `AnoncredsMasterSecretDuplicateNameError` error would be thrown.
Fixes #131

create master secret per wallet

---

src/lib/agent/MessageReceiver.ts
src/lib/agent/ProvisioningService.ts
src/lib/utils/__tests__/indyError.test.ts
src/lib/utils/indyError.ts
src/lib/wallet/IndyWallet.ts

Adds indyError util for consistent error handling. As it can take a while before a new version of indy-sdk is released with the changes (hyperledger/indy-sdk#2283), it takes inconsistencies between indy-sdk and rn-indy-sdk into account. This can be removed once indy-sdk updates
Related to AbsaOSS/rn-indy-sdk#24

add indyError util for consistent error handling

---

src/lib/modules/ConnectionsModule.ts
src/lib/protocols/connections/ConnectionService.test.ts
src/lib/protocols/connections/ConnectionService.ts

**Concern:** Unable to set `alias` when creating or accepting a connection invitation
**Cause:** `ConnectionRecord` contains `alias` however, no support was present to specify it.
**Correction:** 
Added support for `alias` along with `autoAcceptConnection` to the following files: 
- `modules/ConnectionsModule.ts`
- `protocols/connections/ConnectionService.ts`
Fixes #140

Added support to set an alias for a Connection

---

src/lib/modules/RoutingModule.ts
src/lib/protocols/connections/ConnectionService.test.ts

**Concern:** Unable to set `alias` for Mediator
**Cause:** `processInvitation` does have support to set `alias` however, no `alias` was being passed from `RoutingModule.provision()`
**Correction:**
- Added default `alias` within `RoutingModule.provision()`
- Added `alias` to `MediatorConfiguration`
(Updated tests as well)

Added default mediator alias + support to specify mediator alias

---

package.json
src/samples/mediator.ts
yarn.lock

ACA-Py sends outbound messages with the `application/ssi-agent-wire` Content-Type header, which the mediator didn't recognise.

add ssi-agent-wire type to mediator

---

src/lib/modules/CredentialsModule.ts
src/lib/protocols/credentials/CredentialService.ts

This is a temprorary fix until we properly managing transformation of record properties from an to class instances. While using the framework in the app we noticed sometimes the properties are class instances, and sometimes not. This fixes it 'the dirty way' for now.
Note: I'm creating a lot of small pr's and extract some of the present proof work I'm doing to make reviewing easier

fix: check instance types of record properties

---

src/lib/protocols/credentials/CredentialUtils.ts
src/lib/protocols/credentials/__tests__/CredentialUtils.test.ts

I'm working on the present proof protocol, and part of it is verifying the raw against the encoded values. As the PR is already quite big I thought this could be easily added as a separate PR.
The encoding method didn't properly encode all value types. I used the example test cases from the RFC as tests and updated the encode method

add method to check encoding, improve encode

---

src/lib/agent/Dispatcher.ts
src/lib/decorators/thread/ThreadDecoratorExtension.ts
src/lib/protocols/connections/ConnectionService.ts
src/lib/protocols/credentials/CredentialService.ts

Updated the thread id signature to be an attribute instead of an method, cause it is acutally a property

update thread id signature

---

src/lib/modules/BasicMessagesModule.ts
src/lib/modules/ConnectionsModule.ts
src/lib/modules/CredentialsModule.ts

Same as with other property changes. More natural usage when it is a property IMO

make events property instead of method

---

src/lib/decorators/signature/SignatureDecoratorUtils.test.ts
src/lib/decorators/signature/SignatureDecoratorUtils.ts
src/lib/wallet/IndyWallet.ts

I recently complained in some PR that we have `walletHandle` attribute publicly accessible. I got an idea to use `createDid` wallet method in the test. What do you think?

refactor: Hide wallet handle inside a Wallet class

---

src/lib/__tests__/proofs.test.ts
src/lib/agent/Agent.ts
src/lib/modules/ConnectionsModule.ts
src/lib/modules/CredentialsModule.ts
src/lib/modules/ProofsModule.ts
src/lib/protocols/issue-credential/__tests__/StubWallet.ts
src/lib/protocols/issue-credential/models/CredentialInfo.ts
src/lib/protocols/present-proof/ProofService.ts
src/lib/protocols/present-proof/models/ProofRequest.ts
src/lib/protocols/present-proof/models/RequestedCredentials.ts
src/lib/utils/transformers.ts
src/lib/wallet/IndyWallet.ts
src/lib/wallet/Wallet.ts

- remove indy from proofs module
- add role names to module methods
- rename `buildSchemas`, `buildCredentialDefinitions` to `getSchemas`, `getCredentialDefinitions` (not abstracted yet. That's a bigger change and will get a separate PR)
- Use records (json objects) instead of Maps to make API usage easier

changes based on pr feedback

---

src/lib/modules/credentials/__tests__/StubWallet.ts
src/lib/modules/proofs/services/ProofService.ts
src/lib/wallet/IndyWallet.ts
src/lib/wallet/Wallet.ts
yarn.lock

Implements point 7 from #192. Although it's still not ideal to have everything in the wallet I think it's a good step forward. I can imagine we'll have another class like `CredentialsCrypto` with dependency to `Wallet` which could eventually replace dependency from `ProofService` to `Wallet.

refactor: Move indy dependency from proof service to wallet

---

src/lib/__tests__/credentials.test.ts
src/lib/agent/MessageReceiver.ts
src/lib/decorators/signature/SignatureDecoratorUtils.test.ts
src/lib/decorators/signature/SignatureDecoratorUtils.ts
src/lib/modules/basic-messages/messages/BasicMessageMessageType.ts
src/lib/modules/common/messages/CommonMessageType.ts
src/lib/modules/connections/messages/ConnectionMessageType.ts
src/lib/modules/credentials/__tests__/CredentialService.test.ts
src/lib/modules/credentials/messages/IssueCredentialMessageType.ts
src/lib/modules/proofs/messages/PresentProofMessageType.ts
src/lib/modules/routing/messages/RoutingMessageType.ts
src/lib/utils/__tests__/JsonTransformer.test.ts
src/lib/utils/__tests__/messageType.test.ts
src/lib/utils/messageType.ts

Still supports receiving the old "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec" prefix
https://github.com/hyperledger/aries-rfcs/blob/master/features/0348-transition-msg-type-to-https/README.md
Fixes #121

Default to sending https didcomm message prefix

---

src/agent/MessageReceiver.ts
src/modules/connections/__tests__/ConnectionInvitationMessage.test.ts
src/modules/connections/messages/ConnectionInvitationMessage.ts
src/utils/__tests__/messageType.test.ts
src/utils/messageType.ts

Invitations do not go trough the message receiver which means the prefix was not replaced and validation failed because it expected the https://didcomm.org prefix.
This add an `@Transform` to the type of the invitation message so it is replaced with the didcomm prefix. As it is the only out-of-band message, this seemed like the best approach

fix: legacy did:sov prefix on invitation

---

tsconfig.json

Fixes React Native record storage non-iterable async function generator issues due to TS configurations: #225 
ES2017 was the highest target specifiable to not have not-iterable errors in React Native.
Signed-off-by: James Ebert <jamesebert.k@gmail.com>

fix: revert to ES2017 to fix function generator issues in react native

---

.github/workflows/continuous-integration.yml
package.json
yarn.lock

This adds automatic releasing with release-it. It doesn't yet use conventional commits, I'd like to do this at a later stage.
- On every push to main a new `unstable` version will be released. This is for ease of use with developing now that the API is still unstable
- A separate workflow dispatch is added to manually release a new version. This requires an input of `patch`, `minor`, `major` to specify the version.
There were some problems with the format of the first release, so I reverted that. We can let release-it make the first release

chore: add release-it setup

---

package.json

As the title suggests, the npm checks don't work with NPM_TOKEN, only when you do npm login. We only have a token, and the checks are not required
I did a dry run locally but not with NPM_TOKEN, I now tested it with NPM_TOKEN locally.
Third time's the charm, @jakubkoci could you do the honours?

ci: skip npm check, doesn't work with NPM_TOKEN

---

.github/workflows/continuous-integration.yml
yarn.lock

I'm sorry for all the trouble @jakubkoci....
It's hard to test these things locally. I tested in a CI environment in my fork now: https://github.com/TimoGlastra/aries-framework-javascript/runs/2342440334
The dry-run passes. Now let's hope the actual run passes. There's some weird issue with different node versions being used (because we use yarn, release-it uses NPM)

ci: prepend node path

---

.github/workflows/continuous-integration.yml

Ugh!!! NPM is really picking on me. 
I now went as far as releasing the actual package from my fork under a different name. It works now. Dry runs just don't work for NPM....
BTW -- don't worry about the secrets, github masks them.
Behold: `aries-framework-test`: https://www.npmjs.com/package/aries-framework-test
@jakubkoci one again please ;)

ci: set up .npmrc manually

---

.github/workflows/continuous-integration.yml

This is not related to the release PRs so I thought it'd be better to make it a separate PR. 
turns out it actually takes longer to get the cache than to build the docker images themselves.

ci: remove docker cache

---

package.json

Ok so we did a first successful release 🎉 
However some thing were not set up correctly to work with Hyperledger permissions and branch protection. Basically it comes down to that we cannot create a commit, so we can't update the version in package.json
To get around this I made the following changes:
- Do not push new commits to github (only releases, this is not protected)
- Do not create a commit
- Make the tag on the current commit instead of the version bump commit
- Take the current version from the latest tag that belongs to this branch instead of package.json (i.e. the tag must be on a commit that is in the history of this branch) 
- Keep the version in package.json to 0.0.0
I know this is 100% ideal, but without being able to push to the main branch it's quite complex to create a …

ci: do not push after release

---

samples/__tests__/e2e.test.ts
samples/mediator.ts
src/__tests__/agents.test.ts
src/__tests__/credentials.test.ts
src/__tests__/helpers.ts
src/__tests__/ledger.test.ts
src/__tests__/proofs.test.ts
src/agent/Agent.ts
src/transport/InboundTransporter.ts

It aligns API with the setting of the outbound transporter. It's also better for the cases when a developer wants to pass messages into the agent by themself.
BREAKING CHANGE

refactor: extract inbound transporter from agent constructor

---

package.json

as we only have unstable releases, if we do not set the latest tag you can not just install aries-framework

chore: use latest tag for npm release

---

src/__tests__/credentials.test.ts
src/agent/Agent.ts
src/agent/BaseMessage.ts
src/decorators/attachment/Attachment.ts
src/index.ts
src/modules/basic-messages/repository/BasicMessageRecord.ts
src/modules/connections/__tests__/ConnectionService.test.ts
src/modules/connections/models/ConnectionRole.ts
src/modules/connections/repository/ConnectionRecord.ts
src/modules/credentials/CredentialsModule.ts
src/modules/credentials/__tests__/CredentialService.test.ts
src/modules/credentials/repository/CredentialRecord.ts
src/modules/credentials/services/CredentialService.ts
src/modules/ledger/services/LedgerService.ts
src/modules/proofs/ProofsModule.ts
src/modules/proofs/repository/ProofRecord.ts
src/modules/proofs/services/ProofService.ts
src/modules/routing/messages/BatchMessage.ts
src/modules/routing/repository/ProvisioningRecord.ts
src/storage/BaseRecord.ts
src/storage/IndyStorageService.test.ts
src/storage/IndyStorageService.ts
src/storage/Repository.ts

Transform record classes and its sub objects using class transformer.
Fixes #106
Was sort of a blocker for some of the work I wanted to do for #187, and it was long overdue this was fixed.

feat: automatic transformation of record classes

---

.github/workflows/continuous-integration.yml

Because we run the linting jobs inside a docker container we are not benefiting from all of the github features. See image above. This separates the linting /validation from the other jobs.
Fixes #91

ci: sperate linting and validation tasks

---

.github/workflows/continuous-integration.yml
docker/docker-compose-mediators.yml
package.json
samples/__tests__/e2e-ws.test.ts
samples/__tests__/e2e.test.ts
samples/mediator-ws.ts
scripts/run-mediator-ws.sh
src/agent/Agent.ts
src/agent/AgentConfig.ts
src/agent/Dispatcher.ts
src/agent/MessageReceiver.ts
src/agent/MessageSender.ts
src/agent/TransportService.ts
src/agent/__tests__/TransportService.test.ts
src/modules/connections/repository/ConnectionRecord.ts
src/types.ts
yarn.lock

This is how it works now:
* A mediator takes endpoint for invitation or DidDoc from `config`.
* An edge agent takes endpoint for invitation or DidDoc from `inboundConnection` if it has any.
* The edge agent gets out of band invitation via http request to mediator (http://mediator1.com/invitation). The invitation contains `ws` endpoint because we want to make a connection via WebSocket.
* The edge agent takes an endpoint for outbound communication from invitation or DidDoc. For a connection with another edge agent, it takes an endpoint from `indbound` connection. Therefore it’s the same `ws` endpoint as it is contained in the mediator invitation.
To integrate ws and http servers together and support multiple transports we would need to enable following:
* A mediator sends a different …

feat: Add support for WebSocket transports

---

.github/workflows/continuous-integration.yml

This should fix the issues with the release. Github added a `concurrency` key a few weeks ago that allows us to prevent concurrent jobs from running. See the comment in the action file for more context
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idconcurrency

ci: do not run concurrent release jobs

---

package.json
samples/__tests__/e2e-ws.test.ts
samples/mediator-ws.ts
samples/mediator.ts
src/__tests__/helpers.ts
src/agent/Agent.ts
src/agent/MessageSender.ts
src/transport/HttpOutboundTransporter.ts
src/transport/OutboundTransporter.ts
src/transport/WsOutboundTransporter.ts
src/transport/index.ts
src/utils/ws.ts

add internal ws outbound transporter. Same as with HTTP. Next step is multi outbound transport support.

feat: add internal ws outbound transporter

---

src/__tests__/helpers.ts
src/__tests__/ledger.test.ts
src/agent/Agent.ts
src/agent/AgentConfig.ts
src/modules/indy/services/IndyIssuerService.ts
src/modules/ledger/LedgerModule.ts
src/modules/ledger/services/LedgerService.ts
src/storage/fs/NodeFileSystem.ts
src/storage/fs/ReactNativeFileSystem.ts
src/types.ts
src/utils/path.ts

- only connect to ledger when needed
- allow to pass `genesisTransactions` so you don't have to deal with storing the genesis yourself
Fixes #219 
Fixes #265 
The ledger management can be improved, but I think this is a simple first step. Only open the ledger connection if a ledger call is made
---
Tested in both NodeJS and React Native

feat: only connect to ledger when needed

---

src/__tests__/helpers.ts
src/__tests__/setup.ts

This should fix the failing CI.
The CI jobs are now required so it won't be possible to get bad commits into main
The problem was because I moved `toBeConnected` with to setup so each test file doesn't have to do it anymore. However this caused (i think?) some cyclic dependencies

fix: test failing because of moved import

---

samples/mediator-ws.ts
src/__tests__/helpers.ts
src/agent/Agent.ts
src/agent/EnvelopeService.ts
src/agent/MessageReceiver.ts
src/agent/MessageSender.ts
src/agent/TransportService.ts
src/agent/__tests__/MessageSender.test.ts
src/agent/__tests__/TransportService.test.ts
src/agent/helpers.ts
src/transport/WsOutboundTransporter.ts
src/types.ts

I did some refactorings to help me add support for multiple transports in the following PR:
* Add test to `MessageSender`
* Move up a logic from `EnvelopeService` to `MessageSender`
* Remove transport-related details from the `TransportService` and from the core of the framework.
* Rename `transport` to `session` which hopefully express the meaning better.
As a next step I'm considering:
* Rename transporters to transports
* Move up more logic from `MessageSender.packMessage` and pass `service` object to `packMessage`
* Then we could call `packMessage` and `sendMessage` for every available service. Eventually, we could remove the logic from `createOutboundMessage`.
* Improve validation of `outboundMessage` inside `OutboundTransporter` and error handling
* Add multiple transports
If you …

refactor: Move a transport protocol-related logic from the framework core

---

src/utils/BufferEncoder.ts
src/utils/JsonEncoder.ts

Also decodes from uint8Array now instead of only a Buffer.
Necessary for anything that is not in NodeJs.
Signed-off-by: blu3beri <berend@animo.id>

fix: convert from buffer now also accepts uint8Array

---

src/agent/AgentMessage.ts
src/decorators/attachment/Attachment.test.ts
src/decorators/attachment/Attachment.ts
src/decorators/attachment/AttachmentExtension.ts
src/modules/credentials/__tests__/CredentialService.test.ts
src/modules/credentials/messages/IssueCredentialMessage.ts
src/modules/credentials/messages/OfferCredentialMessage.ts
src/modules/credentials/messages/RequestCredentialMessage.ts
src/modules/credentials/services/CredentialService.ts
src/modules/proofs/messages/PresentationMessage.ts
src/modules/proofs/messages/RequestPresentationMessage.ts
src/modules/proofs/services/ProofService.ts

Added the extension to the attachment decorator and renamed the attachment property on the issue and verify messages to avoid confliction.
Has been added for the support of linking credentials to attachments.

feat: Added attachment extension

---

src/utils/environment.ts
src/utils/fetch.ts
src/utils/ws.ts

- fix: fetch & websocket browser support
This add support for fetch and websocket in the browser environment. Typings had to be added to prevent errors in the respective outboundtransport
(Not sure if these typings are the correct way)

fix: websocket and fetch fix for browser

---

src/agent/Agent.ts
src/agent/__tests__/Agent.test.ts

feat: add isInitialized agent property

---

.github/workflows/continuous-integration.yml

The release script failed randomly and then started working again. Adding verbose logging so it will be easier to debug the actions going forward

ci: enable verbose logging

---

src/__tests__/credentials.test.ts
src/modules/credentials/CredentialsModule.ts
src/modules/credentials/__tests__/CredentialRecord.test.ts
src/modules/credentials/__tests__/CredentialService.test.ts
src/modules/credentials/repository/CredentialRecord.ts
src/modules/credentials/services/CredentialService.ts
src/modules/proofs/ProofsModule.ts
src/modules/proofs/repository/ProofRecord.ts
src/modules/proofs/services/ProofService.ts

Using only the thread id gives errors when issuing or proving to yourself as there are multiple records for a single thread id. This retrieves records by both thread id an connection id. this also removes the requirement to check if the record has the correct connection id.

fix: use both thread id and connection id

---

.github/workflows/continuous-integration.yml
package.json
src/modules/connections/ConnectionsModule.ts

This fixes a require cycle that got into main.
It also adds some extra guards to hopefully prevent race conditions with parallel merges. I discovered what the problem is, just now sure how to fix it yet: https://github.com/release-it/release-it/issues/773

ci: cancel old job, require commits for release 

---

src/modules/connections/ConnectionsModule.ts
tests/mediator.ts

Node v16 exists if it encounters an unhandled promise rejection.
We should send a 500 response when receiving a message gives an error

fix: handle receive message promise rejection

---

README.md

Changed https://www.npmjs.com/package/aries-framework-javascript
to https://www.npmjs.com/package/aries-framework

docs: fix faulty url of readme npm badge

---

docs/libindy/macos.md

Libindy should now be installable for macOS users by using brew. This should make the setup easier for beginners :).

docs: updated macos install script

---

src/agent/Dispatcher.ts
src/agent/EnvelopeService.ts
src/agent/MessageSender.ts
src/agent/TransportService.ts
src/agent/__tests__/MessageSender.test.ts
src/agent/__tests__/TransportService.test.ts
src/agent/helpers.ts
src/modules/connections/ConnectionsModule.ts
src/modules/routing/RoutingModule.ts
src/types.ts

feat: Pack and send message based on DidDoc services

---

DEVREADME.md
docker/docker-compose-mediators.yml

Adds support for Apple silicon M1. Just specifies the platforms for which the containers were build and with Rosetta it should be possible to start the test ledger and mediators now.

build: docker containers are compatible with m1

---

src/__tests__/agents.test.ts
src/__tests__/credentials.test.ts
src/__tests__/helpers.ts
src/__tests__/ledger.test.ts
src/__tests__/proofs.test.ts
src/agent/Agent.ts
src/agent/__tests__/Agent.test.ts
src/decorators/signature/SignatureDecoratorUtils.test.ts
src/modules/basic-messages/__tests__/BasicMessageService.test.ts
src/modules/connections/__tests__/ConnectionService.test.ts
src/modules/credentials/__tests__/StubWallet.ts
src/storage/__tests__/IndyStorageService.test.ts
src/types.ts
src/wallet/IndyWallet.ts
src/wallet/Wallet.test.ts
src/wallet/Wallet.ts
src/wallet/error/WalletDuplicateError.ts
src/wallet/error/WalletError.ts
src/wallet/error/WalletNotFoundError.ts
src/wallet/error/index.ts
tests/__tests__/e2e-ws.test.ts
tests/__tests__/e2e.test.ts
tests/mediator-ws.ts
tests/mediator.ts

- remove agent `closeAndDeleteWallet` as it was only used for tests. They now inject the wallet to close and delete
- make `walletConfig` and `walletCredentials` optional in `InitConfig`
- user can now manually initiale the wallet
- If agent is initialized and wallet is not yet initialized and no `walletConfig` and `walletCredentials` are available an error will be thrown

feat: allow for lazy wallet initialization

---

src/__tests__/helpers.ts
src/agent/Agent.ts
src/agent/Dispatcher.ts
src/agent/MessageReceiver.ts
src/agent/MessageSender.ts
src/agent/TransportService.ts
src/agent/__tests__/MessageSender.test.ts
src/agent/__tests__/TransportService.test.ts
src/agent/__tests__/stubs.ts
src/decorators/transport/TransportDecoratorExtension.ts
src/transport/WsOutboundTransporter.ts
tests/__tests__/e2e.test.ts
tests/mediator-ws.ts
tests/mediator.ts

This PR contains the following changes:
* A session object is saved only if there is a `return_route` param in an inbound message. 
* An outbound message is sent via session object, and the dispatcher doesn't return the message to the caller. It works for both HTTP and WebSocket.
* The session object also contains the inbound message. The reason for this is that we can decide if we want to use the session to send a message later in MessageSender. We don't try to send a message via session if there is no `return_route` set for a given session.

feat: Use session to send outbound message

---

src/modules/connections/__tests__/ConnectionService.test.ts
src/modules/connections/repository/ConnectionRecord.ts
src/modules/connections/services/ConnectionService.ts

Adds `theirLabel` to the connectionRecord for easy access. Correctly fetches the label from the invitation or connection request depending on whether or not the agent is the invitee or inviter. This is a followup to @blu3beri's PR #369.
Signed-off-by: James Ebert <jamesebert.k@gmail.com>

feat: added their label to the connection record

---

src/transport/HttpOutboundTransporter.ts

Adds error message to error log.
@jakubkoci this is what you get when you don't include the error message specifically. I think we need to fix this in rn-indy-sdk. I'll try to look at it in the near future. For now this fix helps

fix: add error message to log

---

.eslintrc.js

It has been turned off because of the JSON-LD naming convention. Now, we use decorators to transform camelCase JS properties to the correct naming convention.

style: Enable check for camelcase

---

packages/core/src/index.ts
packages/node/package.json
packages/node/src/index.ts
packages/node/src/transport/HttpInboundTransport.ts
packages/node/src/transport/WsInboundTransport.ts
samples/mediator-ws.ts
samples/mediator.ts
tests/e2e.test.ts
yarn.lock

Moves http and ws inbound transports to the node package. I know there's still work to be done on the transports, but this makes it 1000x easier to set up an agent. They're in the node package, so not strictly tied to core

feat(node): add http and ws inbound transport

---

packages/core/src/modules/proofs/models/RequestedCredentials.ts

Incorrect `@Type` transform was added to requested predicates, overriding `@RecordTransformer`.

fix(core): requested predicates transform type

---

packages/core/package.json
packages/core/src/agent/Agent.ts
packages/core/src/agent/Dispatcher.ts
packages/core/src/agent/Events.ts
packages/core/src/modules/discover-features/DiscoverFeaturesModule.ts
packages/core/src/modules/discover-features/__tests__/DiscoverFeaturesService.test.ts
packages/core/src/modules/discover-features/handlers/DiscloseMessageHandler.ts
packages/core/src/modules/discover-features/handlers/QueryMessageHandler.ts
packages/core/src/modules/discover-features/handlers/index.ts
packages/core/src/modules/discover-features/index.ts
packages/core/src/modules/discover-features/messages/DiscoverFeaturesDiscloseMessage.ts
packages/core/src/modules/discover-features/messages/DiscoverFeaturesQueryMessage.ts
packages/core/src/modules/discover-features/messages/index.ts
packages/core/src/modules/discover-features/services/DiscoverFeaturesService.ts
packages/core/src/modules/discover-features/services/index.ts

Add discover features protocol.
Currently working on aries-toolbox integration where this is required for.

feat(core): add discover features protocol

---

packages/core/src/agent/TransportService.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/credentials/messages/CredentialPreview.ts

Do not include the `did-communication` service in the did doc for now. This break interop with AF.NET. We should solve this in the future by only using `IndyAgent` for connection protocol and did-communication for did exchange protocol

fix(core): do not use did-communication service

---

packages/redux-store/jest.config.ts
packages/redux-store/package.json
packages/redux-store/src/index.ts
packages/redux-store/src/slices/agent.ts
packages/redux-store/src/slices/connections/connectionsListener.ts
packages/redux-store/src/slices/connections/connectionsSelectors.ts
packages/redux-store/src/slices/connections/connectionsSlice.ts
packages/redux-store/src/slices/connections/connectionsThunks.ts
packages/redux-store/src/slices/connections/index.ts
packages/redux-store/src/slices/credentials/credentialsListener.ts
packages/redux-store/src/slices/credentials/credentialsSelectors.ts
packages/redux-store/src/slices/credentials/credentialsSlice.ts
packages/redux-store/src/slices/credentials/credentialsThunks.ts
packages/redux-store/src/slices/credentials/index.ts
packages/redux-store/src/slices/index.ts
packages/redux-store/src/slices/proofs/index.ts
packages/redux-store/src/slices/proofs/proofsListener.ts
packages/redux-store/src/slices/proofs/proofsSelectors.ts
packages/redux-store/src/slices/proofs/proofsSlice.ts
packages/redux-store/src/slices/proofs/proofsThunks.ts
packages/redux-store/src/store.ts
packages/redux-store/src/utils.ts
packages/redux-store/tests/index.test.ts
packages/redux-store/tsconfig.build.json
packages/redux-store/tsconfig.json
yarn.lock

Moves the `@aries-framework/redux-store` package from the mobile agent to here for easier management.
This is just the state as it was in the mobile agent repo. @jakubkoci You'll probably have opinions on this, and I'm interested to hear it. 
I'd like to merge first so we can use the package without manually packing every time, and then discuss maybe at the AFJ WG call.
Fixes hyperledger/aries-mobile-agent-react-native#64

feat(redux-store): move from mobile agent repo

---

packages/redux-store/src/slices/credentials/credentialsSelectors.ts
packages/redux-store/src/slices/proofs/proofsSelectors.ts

The current `ById` selectors in the proof and credential selector were probably copied from the `connectionSelector`. Two function names did not change.

fix(redux-store): credential and proof selector by id

---

packages/core/tests/helpers.ts

Because we use auto-accept in issue credential helper it can take a while to have the whole credential flow finished. Both parties need to interact with the ledger and sign/verify the credential

test: longer timeout for issue credential helper

---

docker/docker-compose-mediators.yml

the start scripts used in the docker-compose setup do not match with the actual name of the start scripts that are defined in the package.json

build: fix start scripts for mediators

---

README.md

This mainly adds to the README that this is currenly a monorepo. It shows all the packages and their respective versioning. Since we use the same versionig strategy for every package, it might be a bit redundant. Open for suggestions, but IMO this is a relatively nice way to do it.

docs: mention monorepo

---

packages/redux-store/src/slices/proofs/proofsSlice.ts
packages/redux-store/src/slices/proofs/proofsThunks.ts

- renamed wrong function name from: `ProofThunks.deleteCredential` -> `ProofThunks.deleteProof`

refactor(redux-store)/deleteProof

---

docs/getting-started/1-transports.md
packages/core/src/agent/Agent.ts
packages/core/src/agent/MessageSender.ts
packages/core/src/agent/__tests__/MessageSender.test.ts
packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/models/did/service/Service.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/routing/RecipientModule.ts
packages/core/src/modules/routing/__tests__/mediation.test.ts
packages/core/src/modules/routing/messages/KeylistUpdateMessage.ts
packages/core/src/modules/routing/messages/KeylistUpdateResponseMessage.ts
packages/core/src/transport/WsOutboundTransporter.ts
packages/core/tests/agents.test.ts
packages/core/tests/connectionless-credentials.test.ts
packages/core/tests/helpers.ts
samples/mediator-ws.ts
samples/mediator.ts
tests/e2e-http.test.ts
tests/e2e-subject.test.ts
tests/e2e-ws.test.ts
tests/transport/SubjectOutboundTransport.ts

This PR has code that corrects issues related to mediation.
Corrections
- multiple restarts with the same mediation invitation 
- second sorting of connection transport services based on inbound services
- multiple outbound transport support
- add transport is now register transport, which allows using multiple types of transport.

fix: mediator transports

---

packages/core/src/modules/credentials/__tests__/CredentialService.test.ts
packages/core/src/modules/credentials/messages/CredentialPreview.ts
packages/core/src/modules/ledger/LedgerModule.ts
packages/core/tests/connectionless-credentials.test.ts
packages/core/tests/credentials-auto-accept.test.ts
packages/core/tests/credentials.test.ts
packages/core/tests/helpers.ts
tests/e2e-test.ts

Two api improvements
1. register credential definition doesn't require `signatureType` parameter anymore (just add bloat to the API)
2. add `fromRecord` method to credential preview to be able to create a preview from json object. this makes it a lot simpler:
Before 
```ts
const credentialPreview = new CredentialPreview({
attributes: [
new CredentialPreviewAttribute({
name: 'name',
mimeType: 'text/plain',
value: 'John',
}),
new CredentialPreviewAttribute({
name: 'age',
mimeType: 'text/plain',
value: '99',
}),
],
})
```
After
```ts
const credentialPreview = CredentialPreview.fromRecord({
name: 'John',
age: '99',
})
```

feat: add from record method to cred preview

---

packages/core/package.json
packages/core/src/modules/basic-messages/messages/BasicMessage.ts
packages/core/src/utils/transformers.ts
yarn.lock

Added transform function for parsing dates from multiple formats. Added transform function to basic messaging.
N/A
_PR template adapted from the Python attrs project._

fix: date parsing

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/credentials/CredentialsModule.ts
packages/core/src/modules/credentials/services/CredentialService.ts
packages/core/src/modules/proofs/ProofsModule.ts
packages/core/src/modules/proofs/services/ProofService.ts

feat: add delete methods to services and modules

---

packages/core/src/modules/connections/__tests__/ConnectionInvitationMessage.test.ts
packages/core/src/modules/connections/messages/ConnectionInvitationMessage.ts
packages/react-native/package.json
packages/react-native/src/index.ts
yarn.lock

- Adds support for the `d_m` invitation parameter in the url
- Improved url parsing (with polyfill for React Native)
- Able to add an image to the invitation

feat(core): d_m invitation parameter and invitation image

---

scripts/ngrok-wait.sh

Fixed the env var name to properly set Agent's endpoints when using ngrok

build: fixed setup when using ngrok

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/tests/connections.test.ts
packages/core/tests/helpers.ts

feat(core): add support for multi use invitations

---

packages/core/src/decorators/thread/ThreadDecorator.ts
packages/core/src/modules/proofs/models/ProofAttribute.ts
packages/core/src/modules/proofs/models/RequestedAttribute.ts
packages/core/src/modules/proofs/models/RequestedPredicate.ts
packages/core/src/modules/routing/messages/BatchPickupMessage.ts

Assumption was that isPositive would check for >= 0, but not negative,
but in reality it checks for >= 1

fix(core): remove isPositive validation decorators

---

packages/core/src/modules/ledger/index.ts

it is used in public config so should be exported

fix: export indy pool config

---

packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts

feat(core): store mediator id in connection record

---

packages/core/src/wallet/IndyWallet.ts

To help when user forgot to call `agent.initialize()` (https://github.com/hyperledger/aries-framework-javascript/issues/508)

fix(core): improve wallet not initialized error

---

packages/core/src/agent/Agent.ts
packages/core/src/agent/AgentConfig.ts
packages/core/src/agent/__tests__/Agent.test.ts
packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/services/ConnectionService.ts

#506 
This pr contains:
- Support for updating agent label
- Support for custom label on connection/invitation
I would also like to add support for a custom imageUrl on connection/label, but before that i would like some feedback on this draft.

feat(core): update agent label and imageUrl plus per connection label and imageUrl

---

packages/core/src/logger/ConsoleLogger.ts

The console logger stringified the data object. Appereantly the Error class has no enumerable properties which means it will be stringified as an empty object. This fix checks if a (top level) value being transformed is an error and will transform the non-enumerable properties of the error.

fix(core): fix empty error log in console logger

---

packages/core/src/agent/MessageSender.ts
packages/core/src/agent/__tests__/AgentMessage.test.ts
packages/core/src/agent/__tests__/MessageSender.test.ts
packages/core/tests/TestMessage.ts

feat(core): validate outbound messages

---

packages/core/src/modules/proofs/__tests__/ProofRequest.test.ts
packages/core/src/modules/proofs/models/ProofAttributeInfo.ts
packages/core/src/modules/proofs/models/ProofPredicateInfo.ts
packages/core/src/modules/proofs/models/ProofRequest.ts
packages/core/src/modules/proofs/services/ProofService.ts
packages/core/src/utils/transformers.ts

BREAKING CHANGE: Proof request requestedAttributes and requestedPredicates are now a map instead of record. This is needed to have proper validation using class-validator.
Maintainers: Before merging and squashing make sure to copy the `BREAKING CHANGE` entry to the commit message field, this is needed for automatic tracking of breaking changes

fix(core)!: improve proof request validation

---

packages/core/src/modules/proofs/ProofsModule.ts
packages/core/tests/connectionless-proofs.test.ts
packages/core/tests/helpers.ts
packages/core/tests/proofs-auto-accept.test.ts
packages/core/tests/proofs.test.ts

BREAKING CHANGE: The `ProofsModule.getRequestedCredentialsForProofRequest` expected some low level message objects as input. This is not in line with the public API of the rest of the framework and has been simplified to only require a proof record id and optionally a boolean whether the retrieved credentials should by filtered based on the proof proposal (if avaiable).
Maintainers: Before merging and squashing make sure to copy the `BREAKING CHANGE` entry to the commit message field, this is needed for automatic tracking of breaking changes

refactor(core)!: simplify get creds for proof api

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/handlers/ConnectionResponseHandler.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/routing/RecipientModule.ts

BREAKING CHANGE: a trust ping response will not be requested anymore after completing a connection. This is not required, and also non-standard behaviour. It was also causing some tests to be flaky as response messages were stil being sent after one of the agents had already shut down.
Maintainers: Before merging and squashing make sure to copy the `BREAKING CHANGE` entry to the commit message field, this is needed for automatic tracking of breaking changes
Fixes #515

fix(core)!: do not request ping res for connection

---

packages/core/src/agent/MessageSender.ts

The error message being logged just indicated that a message is underliverable to a certain connection. It swallowed the underlying errors. This adds an `errors` property to the error log so that it is clear what the underlying errors are when a message is underliverable.

fix(core): log errors if message is undeliverable

---

docs/getting-started/5-credentials.md

There were a couple of broken links in the Credentials Getting Started doc. This PR fixes the links to the Agent and Ledger Getting Started docs by referencing them from the same folder that the Credentials doc is in.

docs: Fixing broken agent and ledger relative links in the credentials doc

---

packages/core/src/modules/credentials/__tests__/CredentialRecord.test.ts
packages/core/src/modules/credentials/__tests__/CredentialService.test.ts
packages/core/src/modules/credentials/services/CredentialService.ts
packages/core/src/utils/__tests__/transformers.test.ts
packages/core/src/utils/transformers.ts
packages/core/tests/connectionless-credentials.test.ts
packages/core/tests/credentials-auto-accept.test.ts

BREAKING CHANGE: internal metadata is now prefixed with `_internal` to avoid clashing and accidental overwriting of internal data.
- All the internal metadata MUST be prefixed with `_internal` to indicate to the framework consumer that this data is internal metadata and is required by the framework.

fix(core)!: prefixed internal metadata with _internal/

---

.github/workflows/continuous-integration.yml

- Tests on node 16.x instead of 16.2
- Tests on 17.x for latest compatibility
Marked as draft to check the tests first
Closes #309 

ci: more node versions to test

---

packages/core/src/agent/Dispatcher.ts
packages/core/src/agent/__tests__/Dispatcher.test.ts
packages/core/src/modules/discover-features/__tests__/DiscoverFeaturesService.test.ts
packages/core/src/modules/discover-features/handlers/DiscloseMessageHandler.ts
packages/core/src/modules/discover-features/handlers/QueryMessageHandler.ts
packages/core/src/modules/discover-features/messages/DiscloseMessage.ts
packages/core/src/modules/discover-features/messages/QueryMessage.ts
packages/core/src/modules/discover-features/messages/index.ts
packages/core/src/modules/discover-features/services/DiscoverFeaturesService.ts

It's mainly about refactoring. I will use the "Add filter of protocols by message families" (86f336c) in #531. 
However, I'm not sure about the "Remove slash from protocol ID to be aligned with spec" (ee5a3a4). It seems like spec https://github.com/hyperledger/aries-rfcs/blob/main/concepts/0003-protocols/README.md#piuri defines protocol URI without the last `/` character, so I removed that. Let me know If you think it's dangerous breaking change or incorrect change :)

refactor: move methods to get supported protocols to Dispatcher

---

packages/core/src/modules/connections/services/ConnectionService.ts

Trinsic doesn't send the senderVerkey on a connectionless exchange.

fix: removed check for senderkey for connectionless exchange

---

.github/workflows/continuous-integration.yml

@JamesKEbert I think this should do it. It will create a tag names `alpha.<number>` on each release. I think lerna search for the default `vX.X.X` prefix so should not cause any issues. 
Let's try!

ci: create tag on alpha release

---

.github/workflows/continuous-integration.yml

The ci created annotated tags which clashes with lerna. This PR makes sure we create non-annotated tags

ci: create non-annotated tags

---

.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml
.github/workflows/lint-pr.yml
packages/core/README.md
packages/node/README.md
packages/react-native/README.md

Adds continuous deployment scripts for stable releases. We can now run a manual `workflow_dispatch` action on the `Continuous Integration` pipeline and it will create a PR for the next release. 
Once that PR is merged it will automatically tag, create a github release and release to NPM. This is in preparation for the 0.1.0 release I want to do.

ci: add continuous deployment scripts

---

DEVREADME.md
network/indy-pool-arm.dockerfile
network/indy_config.py

Ledger setup didn't fully work for ARM baed macs. This PR adds an extra dockerfile that can be used to set up the test ledger on ARM macs.

build: add arm test ledger setup

---

README.md

- Ordered by rfc number
- Added report problem protocol support

docs: added report problem protocol to README

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
packages/core/src/modules/routing/RecipientModule.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/tests/connectionless-proofs.test.ts

fix: support mediation for connectionless exchange

---

packages/core/src/modules/credentials/__tests__/CredentialRecord.test.ts
packages/core/src/modules/credentials/__tests__/CredentialService.test.ts
packages/core/src/modules/credentials/repository/CredentialRecord.ts
packages/core/src/modules/credentials/repository/credentialMetadataTypes.ts
packages/core/src/modules/credentials/repository/index.ts
packages/core/src/modules/credentials/services/CredentialService.ts
packages/core/src/storage/BaseRecord.ts
packages/core/src/storage/Metadata.ts
packages/core/src/storage/Repository.ts
packages/core/src/storage/StorageService.ts
packages/core/src/storage/__tests__/Metadata.test.ts
packages/core/src/types.ts
packages/core/src/utils/transformers.ts

BREAKING CHANGE: removed the `getAll()` function.
- Improved typings on the metadata functions. 
- Hidden ugly `_internal/...` and replaced with an enum
- Record metadata stays the same.
Would be nice if we can get this merged before 0.1.0 as it makes the public api quite a bit better

fix(core)!: Improved typing on metadata api

---

docs/libindy/macos-apple.md

When following the instructions for installing indy for an Apple Silicon (M1 Pro) system, I found that the `brew install` command didn't work. After looking into how to install OpenSSL for M1, I found that the OpenSSL v1.1 on Homebrew also works for Apple Silicon chips (see: https://formulae.brew.sh/formula/openssl@1.1).
After following the rest of the instructions I ran the `is-indy-installed` test script, which resulted in `Libindy was installed correctly`. As a double check I have also installed `@aries-framework/node`, again with success.
> NOTE: When I ran `brew install openssl@1.1` it told me v1.1 was already on my system. I am unsure if this is because stuff I have installed prior to this attempt, or if this is because it's natively shipped with macOs. Therefore I have included the …

docs(apple-silicon): update OpenSSL instructions

---

packages/core/src/storage/__tests__/DidCommMessageRecord.test.ts
packages/core/src/storage/__tests__/DidCommMessageRepository.test.ts
packages/core/src/storage/didcomm/DidCommMessageRecord.ts
packages/core/src/storage/didcomm/DidCommMessageRepository.ts
packages/core/src/storage/didcomm/DidCommMessageRole.ts
packages/core/src/storage/didcomm/index.ts
packages/core/src/storage/index.ts
packages/core/src/types.ts
packages/core/src/utils/__tests__/string.test.ts
packages/core/src/utils/string.ts
packages/core/src/utils/type.ts

Adds a `DidCommMessageRecord` that can be used to store didcomm messages.
This can be useful in the OOB protocol, and with the addition of v2 to the credentials and proofs module. This way we don't have to store the messages inside the record class anymore. 
Instead of accessing and storing a message in the record like this:
```ts
// write
credentialRecord.proposalMessage = proposalMessage
await credentialRepository.save(credentialRecord)
// read
credentialRecord.proposalMessage
```
we can use it like this:
```ts
// write
await didcommMessageRepository.saveAgentMessage({ 
agentMessage: proposalMessage, 
role: DidCommMessageRole.Receiver,
associatedRecordId: credentialRecord.id
})
// read
await didcommMessageRepository.getAgentMessage({
associatedRecordId: credentialRecord.id, …
```

feat: add didcomm message record

---

.eslintrc.js
packages/core/src/utils/__tests__/HashlinkEncoder.test.ts
packages/core/src/utils/__tests__/MultibaseEncoder.test.ts
packages/core/src/utils/__tests__/MultihashEncoder.test.ts
packages/core/src/utils/did.ts

Disallow usage of global `Buffer`, require it to be imported. `Buffer` is available globally in Node.JS and I can't seem to make TS think we're not in a NodeJS env. I just discovered this eslint rule that takes care of it (and also fixed one usage of global buffer outside of the tests 🎉 )

fix: disallow usage of global buffer

---

packages/core/src/crypto/JwsService.ts
packages/core/src/crypto/__tests__/JwsService.test.ts

fix: verify jws contains at least 1 signature

---

packages/core/src/modules/connections/ConnectionsModule.ts

- Allows users to customise a timeout to the `returnWhenIsConnected method`.

feat(core): added timeOut to the module level

---

packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts
packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer2Ez6L.json
packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer2Ez6LMoreServices.json
packages/core/src/modules/dids/methods/peer/__tests__/peerDidNumAlgo2.test.ts
packages/core/src/modules/dids/methods/peer/peerDidNumAlgo2.ts

Fixes for incorrect encoding of services in peer dids. Checked against the [peer-did-python](https://github.com/sicpa-dlab/peer-did-python) implementation.

fix: incorrect encoding of services for did:peer

---

.github/workflows/continuous-deployment.yml

We currently use the commit number, but this is incorrect as the number will be reset to 0 again when the next minor version is released.
E.g. instead of the tag `alpha.347` it will now be `0.2.0-alpha.12`.

ci: get last alpha package version from npm

---

package.json
yarn.lock

The PRs opened by dependabot updated the dependencies only partly resulting in multiple versions of the same package.
Supersedes #613 #614

chore: regenerate yarn.lock for security updates

---

packages/core/src/storage/__tests__/DidCommMessageRepository.test.ts
packages/core/src/storage/didcomm/DidCommMessageRepository.ts

This PR adds `findAgentMessage()` and `saveOrUpdateAgentMessage()` methods to the `DidCommMessageRepository`.
Signed-off-by: NB-Karim <karim.northernblock@gmail.com>

feat: add find and save/update methods to DidCommMessageRepository

---

packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/routing/RecipientModule.ts

Supersedes #458 and incorporates discussions there.
This PR alters the logic for trust pings so that connection records are not updated and events emitted if the record is already in a 'Complete' state.
Fixes the recursive mediator reconnection backoff behavior
Signed-off-by: James Ebert <jamesebert.k@gmail.com>

feat: update recursive backoff & trust ping record updates

---

packages/core/src/modules/credentials/CredentialUtils.ts
packages/core/src/modules/credentials/__tests__/CredentialUtils.test.ts

This PR resolves an interop issue between ACA-Py & AFJ—in credential issuance we verify that the credential did not change between what was offered and what is actually being issued. 
If the credential attribute value to be encoded (as described [here](https://github.com/hyperledger/aries-rfcs/blob/be4ad0a6fb2823bb1fc109364c96f077d5d8dffa/features/0036-issue-credential/README.md#encoding-claims-for-indy-based-verifiable-credentials)) is a string of numbers that contains a leading zero, such as an account number like: `08888`, then ACA-Py removes the leading zero (`8888`), while AFJ instead encodes it with the zero (`08888`). This PR adjusts AFJ’s behavior to bring it in line with ACA-Py’s implementation.
Signed-off-by: James Ebert <jamesebert.k@gmail.com>

fix: leading zeros in credential value encoding

---

packages/core/src/modules/proofs/services/ProofService.ts
packages/core/tests/proofs.test.ts

fix: check groupnames

---

packages/core/src/types.ts
packages/core/src/wallet/IndyWallet.ts
packages/core/tests/wallet.test.ts

Adds key derivation option as documented in the indy-sdk: https://github.com/hyperledger/indy-sdk/tree/master/wrappers/nodejs#createwallet--config-credentials----void
Also tested to work in React Native

feat: add wallet key derivation method option

---

packages/core/tests/wallet.test.ts

Removed '===' prefix to one test name, changed scope of wallet open call to prevent multiple open attempts

test: minor wallet test changes

---

packages/core/src/agent/Agent.ts
packages/core/tests/agents.test.ts

Fixes problem where agent cannot be initialized (again) after shutdown

fix: agent isinitialized on shutdown

---

packages/core/src/modules/routing/messages/MediationRequestMessage.ts

This was probably copied by mistake from the basic message, as it is never been part of the mediation request message.
This currently gives an error if ACA-Py requests mediation from AFJ.

fix(routing): remove sentTime from request message

---

packages/core/src/modules/basic-messages/__tests__/BasicMessageService.test.ts
packages/core/src/modules/basic-messages/services/BasicMessageService.ts

This makes it impossible to send a basic message to yourself

fix: do not use basic message id as record id

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/oob/OutOfBandModule.ts
packages/core/src/modules/oob/repository/OutOfBandRecord.ts
packages/core/tests/helpers.ts
packages/core/tests/oob.test.ts

Just small PR adding ConnectionService tests I removed in the previous PR. I also added some checks for the OOB role and state.

test: reuse connection create and process request tests

---

.eslintrc.js
packages/core/src/agent/Agent.ts
packages/core/src/modules/credentials/services/CredentialService.ts
packages/core/src/modules/proofs/services/ProofService.ts
packages/core/src/modules/routing/RecipientModule.ts
packages/core/src/transport/HttpOutboundTransport.ts
packages/core/src/transport/WsOutboundTransport.ts
samples/mediator.ts

Helps catch nasty bugs (and even caught some places where we didn't call await!), and as #563 has been around forever it's easier to already pick some important rules.

fix: disallow floating promises

---

packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/DidExchangeProtocol.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/dids/domain/createPeerDidFromServices.ts
packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts
packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer1zQmR-did-comm-service.json
packages/core/src/modules/dids/methods/peer/peerDidNumAlgo2.ts
packages/core/src/modules/oob/OutOfBandModule.ts
packages/core/src/modules/oob/messages/OutOfBandMessage.ts
packages/core/tests/helpers.ts

I added a function `serviceToNumAlgo2Did` but I'm testing it in `DidPeer.test`, because I was curious if it's possible to create regular PeerDid and then take `didDocument` from it. As you can see it's not possible right now so I commented the code in the test. 
I described what might be a cause of the problem in issue here [RFC 0434: Ambiguous description of Peer DID numalgo 2 service encoding](https://github.com/hyperledger/aries-rfcs/issues/728).
There is also a simplification of when and what invitation did we store in the connection record. OOB invitation can contain more dids (or service blocks encoded as peer did numalgo2) and we should store only the one we successfully use to send connection request message to.

feat: find existing connection based on invitation did

---

.github/workflows/continuous-integration.yml

Adds node v18 to the test matrix. Once this is merged we can look at removing support for node 12 (https://github.com/hyperledger/aries-framework-javascript/issues/734).

ci: add node 18 to test matrix

---

.github/workflows/continuous-integration.yml
packages/core/src/modules/credentials/__tests__/V1CredentialService.cred.test.ts
packages/core/src/modules/credentials/__tests__/V1CredentialService.offer.test.ts
packages/core/src/modules/credentials/__tests__/V2CredentialService.cred.test.ts
packages/core/src/modules/credentials/__tests__/V2CredentialService.offer.test.ts
packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts

Also updates the ci to add the build script (in addition to check types) so this doesn't happen again.

fix: do not import test logger in src

---

packages/react-native/package.json
yarn.lock

Signed-off-by: Amit <amit@northernblock.io>
Update indy-sdk-react-native version to 0.2.0 to support
- chore!: update indy SDK version to 1.16 for android
- chore(deps): bump plist from 3.0.4 to 3.0.5
- chore(deps): bump async from 2.6.3 to 2.6.4
- chore: update indy framework source link
- 
Issue - https://github.com/hyperledger/aries-framework-javascript/issues/752

chore!: update indy-sdk-react-native version to 0.2.0

---

packages/core/tests/postgres.test.ts
packages/node/src/PostgresPlugin.ts

fix(node): allow to import node package without postgres

---

packages/core/src/modules/credentials/formats/CredentialFormatService.ts
packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
packages/core/src/modules/credentials/protocol/v2/CredentialMessageBuilder.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials-architecture.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials.propose-offer.test.ts

Signed-off-by: Mike Richardson <mike.richardson@northernblock.io>

fix: propose payload attachment in in snake_case JSON format

---

packages/core/tests/oob.test.ts

test: use event listener instead of while loop

---

packages/core/src/modules/vc/W3cCredentialService.ts

Fixed invalid injection symbols for Wallet and Logger in the W3cCredentialService.
Signed-off-by: Karim <karim@animo.id>

fix: invalid injection symbols in W3cCredService

---

packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g1.json
packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g1g2.json
packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g2.json
packages/core/src/modules/dids/__tests__/__fixtures__/didKeyX25519.json
packages/core/src/modules/dids/domain/keyDidDocument.ts
packages/core/src/modules/dids/methods/key/__tests__/DidKey.test.ts

BBS context was missing in the DidDocumentBuilder, resulting in some value being dropped during frameing. This PR adds the context.
Signed-off-by: Karim <karim@animo.id>

fix: add BBS context to DidDoc

---

.github/workflows/continuous-integration.yml

Run ci on pre branches so we also have this enabled for the 0.3.0-pre (and others in the future) branches

ci: run ci on -pre branches

---

packages/core/src/modules/oob/messages/OutOfBandInvitation.ts

Adds a check whether the service is instanceof String as mentioned in  #812. this is needed due to the class-validator logic sadly.

fix(oob): check service is string instance

---

packages/core/src/modules/oob/__tests__/helpers.test.ts
packages/core/src/modules/oob/helpers.ts
packages/core/tests/oob.test.ts

more issues with interop testing in AATH.

fix(oob): legacy invitation with multiple endpoint

---

packages/core/src/transport/WsOutboundTransport.ts
packages/core/src/utils/__tests__/indyProofRequest.test.ts

We were already processing messages serially for pickup v1 and v2. This pr updates to also use this for websocket inbound transport. This can help prevent some race conditions and is consistent with the other pickup approaches

fix: process ws return route messages serially

---

packages/core/src/modules/basic-messages/services/BasicMessageService.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v1credentials-auto-accept.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials-auto-accept.test.ts
packages/core/src/modules/credentials/services/CredentialService.ts
packages/core/src/modules/oob/OutOfBandModule.ts
packages/core/src/modules/oob/OutOfBandService.ts
packages/core/src/modules/oob/repository/__tests__/OutOfBandRecord.test.ts
packages/core/src/modules/proofs/services/ProofService.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/src/modules/routing/services/MediatorService.ts
packages/core/src/utils/JsonTransformer.ts
samples/extension-module/dummy/services/DummyService.ts

Clone records before emitting them in events to avoid mutation later on. 
Fixes #832

fix: clone record before emitting event

---

packages/core/src/agent/MessageSender.ts
packages/core/src/agent/__tests__/MessageSender.test.ts

Fixed issue where message sender would incorrectly return early from loop (inside `sendMessage`) even if service was unable to be satisfied by outbound transports.

fix: send message to service

---

packages/core/src/decorators/ack/AckDecorator.test.ts
packages/core/src/decorators/ack/AckDecorator.ts
packages/core/src/decorators/ack/AckDecoratorExtension.ts

The update to the please ack decorator broke for pre-aip 2 ack decorators. This adds some sane defaults to make sure AFJ doesn't break with old please ack decorators

fix: support pre-aip2 please ack decorator

---

packages/node/src/transport/HttpInboundTransport.ts

If an error occurred after a message has been sent in response in the http inbound transport it would error out because we can't return a response twice in http. This just checks if the response is already sent

fix(node): only send 500 if no headers sent yet

---

packages/core/src/modules/credentials/formats/CredentialFormat.ts
packages/core/src/modules/credentials/formats/indy/IndyCredentialFormat.ts

My previous PR to generalize the crdentials module undid some of the changes to only allow interfaces.

fix(credentials): use interface in module api

---

packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts

fix(credentials): indy cred attachment format

---

.github/workflows/continuous-integration.yml

Fixes lerna version detection for next release. Lerna will use the latest tag to determine the latest released version. As we create a tag for each commit we need to remove all pre-release tags so we can determine the last stable release. It also excludes the private packages that have been added since 0.1.0 (extension-module and demo) from the release / changelog creation.

ci: fix lerna version detection based on tags

---

packages/core/src/modules/connections/services/ConnectionService.ts

Fixes issue where logs would print `[object Object]`

fix(connections): fix log of object in string

---

.eslintrc.js
.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml
package.json
scripts/get-next-bump.ts
tsconfig.eslint.json
yarn.lock

We are using patch version for feature releases and minor versions for breaking releases, this change makes sure that's enforced. 
This should be merged before all other PRs to make sure we aren't going to release 0.3.0-alpha.1 but 0.2.1-alpha.1

ci: add correct version bump

---

packages/core/src/agent/Agent.ts
packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
packages/core/src/modules/connections/handlers/DidExchangeRequestHandler.ts
packages/core/src/modules/credentials/CredentialsModule.ts
packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
packages/core/src/modules/credentials/protocol/v1/__tests__/V1CredentialServiceCred.test.ts
packages/core/src/modules/credentials/protocol/v1/__tests__/V1CredentialServiceProposeOffer.test.ts
packages/core/src/modules/credentials/protocol/v1/handlers/V1OfferCredentialHandler.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialServiceCred.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialServiceOffer.test.ts
packages/core/src/modules/credentials/protocol/v2/handlers/V2OfferCredentialHandler.ts
packages/core/src/modules/ledger/__tests__/IndyPoolService.test.ts
packages/core/src/modules/oob/OutOfBandModule.ts
packages/core/src/modules/proofs/ProofsModule.ts
packages/core/src/modules/proofs/handlers/RequestPresentationHandler.ts
packages/core/src/modules/routing/RecipientModule.ts
packages/core/src/modules/routing/RoutingEvents.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/src/modules/routing/services/RoutingService.ts
packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
packages/core/src/modules/routing/services/__tests__/RoutingService.test.ts

Adds a routing service that handles the creating of keys for routing and integrates with the mediation recipient service to add routing for the mediator.
The extraction is just to make sure we don't have to depend on a mediator dependency all across the framework. 
What this also adds is an event for when routing keys are created. This allows the tenant module to listen for created routing keys and can then create a mapping of it in the base wallet. I first started with a middleware approach (As described in the design document: https://hackmd.io/vGLVlxLvQR6jsEEjzNcL8g), but this added _ A LOT_ of complexity and didn't abstract away the mediator functionality as that is a part of the core API. So I went for the less generic but simpler API, that is just fine I think.
Again no changes to …

feat(routing): add routing service

---

packages/core/src/modules/oob/OutOfBandModule.ts
packages/core/src/utils/__tests__/messageType.test.ts
packages/core/src/utils/messageType.ts
packages/core/tests/oob.test.ts

Fix issue of the oob module not being able to handle the legacy did sov prefix on attachment in oob invitations.
Issue as reported on discord:
> AFJ is throwing an error when i accept an oob invitation with a present-proof/credential-offer attachment from acapy,   Error msg: There is no message in requests~attach supported by agent.  It's due to LegacyDidSovPrefix in the message type.  It fails at this step : https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/oob/OutOfBandModule.ts#L599

fix(oob): support legacy prefix in attachments

---

packages/core/src/agent/Agent.ts
packages/core/src/agent/BaseAgent.ts
packages/core/src/modules/vc/W3cCredentialService.ts
packages/core/src/storage/migration/UpdateAssistant.ts
packages/core/src/storage/migration/updates.ts
packages/core/src/storage/migration/updates/0.1-0.2/connection.ts
packages/core/src/storage/migration/updates/0.1-0.2/credential.ts
packages/core/src/storage/migration/updates/0.1-0.2/index.ts
packages/core/src/storage/migration/updates/0.1-0.2/mediation.ts

This is the same PR as #919 , but based off the 0.3.0-pre branch instead of main. There's no changes compared to #919 
Dependant on:
- #920
- #921 

feat: add base agent class 

---

.github/workflows/continuous-integration.yml

I removed this last time, but seems it is needed after all to correctly generate the changelog. See the changelog in #940 for what's the issue

ci: fix changelog generation

---

packages/core/src/agent/MessageSender.ts
packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/handlers/ConnectionResponseHandler.ts
packages/core/src/modules/connections/handlers/DidExchangeResponseHandler.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/transport/HttpOutboundTransport.ts

This PR adds some improvements to return routing. Mainly it adds two things:
1. Messages returned as a http response are now emitted using an event, meaning the sendMessage await won't wait for the returned message to be processed. This could lead to a chain of send / receive messages that would take a long time to resolve. Especially if the socket was kept open because no response was returned this could lead to unwanted behaviour. (see https://github.com/hyperledger/aries-cloudagent-python/pull/1853 for more context on socket staying open)
2. Do not include the return route decorator if not response is expected. The return route decorator is automatically added if we don't have an endpoint. This only happens with the mediator in most cases. What would happen is that the trust ping was …

fix: no return routing and wait for ping

---

packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/src/modules/routing/services/MediatorService.ts
packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
packages/core/src/modules/routing/services/__tests__/MediatorService.test.ts

Does not send did:key dids yet, only supports processing did:key dids. Sending did:key dids
will be added in a future (breaking) PR and release.
Relevant issue in ACA-Py: https://github.com/hyperledger/aries-cloudagent-python/issues/1859

feat(routing): support did:key in RFC0211

---

packages/core/src/modules/routing/RecipientModule.ts

These messages are really annoying when you're developing in react native and don't necessarily mean something is wrong.

refactor: log warning messages as debug

---

packages/core/src/transport/WsOutboundTransport.ts
packages/node/src/transport/WsInboundTransport.ts

It logs the following to the console, which is really unhelpful and bloats your logs:
```
2022-07-24 09:57:06.677  DEBUG [DIDComm Chat  WebSocket.<anonymous>] WebSocket message event received. 
{
data: {
type: 'Buffer',
data: [
123,
34,
112,
114,
111,
116,
101,
99,
116,
101,
100,
34,
58,
34,
101,
121,
74,
108,
98,
109,
77,
105,
79,
105,
74,
52,
89,
50,
104,
104,
89,
50,
104,
104,
77,
106,
66,
119,
98,
50,
120,
53,
77,
84,
77,
119,
78,
86,
57,
112,
90,
88,
82,
109,
73,
105,
119,
105,
100,
72,
108,
119,
73,
106,
111,
105,
83,
108,
100,
78,
76,
122,
69,
117,
77,
67,
73,
115,
73,
109,
70,
115,
90,
121,
73,
54,
73,
107,
70,
49,
100,
71,
104,
106,
99,
110,
108,
119,
100,
67,
... 745 more items
]
}
}
```

refactor: do not log websocket data

---

packages/core/src/modules/ledger/IndyPool.ts

I'm not sure if the check for REQNACK response was omitted in the write request method on purpose, but `registerSchema` is throwing a confusing error.
Previously:
```
TypeError: Cannot read property 'txnMetadata' of undefined
```
After the update:
```
Ledger 'pool-localhost' rejected write transaction request: client request invalid: could not authenticate, verkey for 9gFCquotxSS7ctKG1GJatU cannot be found
```

feat(ledger): handle REQNACK response for write request

---

packages/core/src/modules/dids/domain/key-type/__tests__/ed25519.test.ts
packages/core/src/modules/dids/domain/key-type/bls12381g2.ts
packages/core/src/modules/dids/domain/key-type/ed25519.ts
packages/core/src/modules/vc/SignatureSuiteRegistry.ts
packages/core/src/modules/vc/W3cCredentialService.ts
packages/core/src/modules/vc/W3cVcModule.ts
packages/core/src/modules/vc/__tests__/W3cCredentialService.test.ts
packages/core/src/modules/vc/__tests__/W3cVcModule.test.ts

Signed-off-by: Karim <karim@animo.id>

feat: fetch verification method types by proof type

---

packages/core/src/modules/generic-records/GenericRecordsModule.ts
packages/core/src/modules/generic-records/service/GenericRecordService.ts
packages/core/src/storage/IndyStorageService.ts
packages/core/src/storage/Repository.ts
packages/core/src/storage/StorageService.ts
packages/core/src/storage/__tests__/Repository.test.ts
packages/core/tests/generic-records.test.ts
tests/InMemoryStorageService.ts
yarn.lock

Fixes #925 
Signed-off-by: Tipu Singh tipu.singh@ayanworks.com

feat: delete by record id 

---

packages/core/src/modules/question-answer/QuestionAnswerModule.ts
packages/core/src/modules/question-answer/__tests__/QuestionAnswerService.test.ts
packages/core/src/modules/question-answer/__tests__/helpers.ts
packages/core/src/modules/question-answer/__tests__/question-answer.e2e.test.ts
packages/core/src/modules/question-answer/repository/QuestionAnswerRecord.ts
packages/core/src/modules/question-answer/services/QuestionAnswerService.ts

Some fixes and additional checks in process methods from `QuestionAnswerService` that are preventing it to correctly accept/reject the received message.
Add some service tests as well as a simple E2E module test that allowed to find and fix a weird issue with parameter construction: `ValidResponse` takes another `ValidResponse` as input and this could make message validation to fail.
No API changes were introduced apart from adding a `findById` method.
Signed-off-by: Ariel Gentile <gentilester@gmail.com>

fix(question-answer): question answer protocol state/role check

---

packages/core/src/modules/ledger/IndyPool.ts

fixes issue where cannot reconnect to ledger after rotating wallet key

fix(ledger): remove poolConnected on pool close

---

MAINTAINERS.md

Add @janrtvld to maintainers as discussed in [Discord](https://discord.com/channels/905194001349627914/941708033434738768/1016248809589850132).

chore: add @janrtvld to maintainers

---

packages/core/src/modules/credentials/CredentialServiceOptions.ts
packages/core/src/modules/proofs/ProofService.ts
packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/models/ProofServiceOptions.ts

feat(proofs): delete associated didcomm messages 

---

packages/core/src/agent/Agent.ts

Signed-off-by: Pavel Zarecky <zarecky@procivis.ch>
This catch block is added to avoid potential crash, when an unexpected message arrives from a connection.
See #1018

fix: avoid crash when an unexpected message arrives

---

packages/core/src/modules/vc/W3cCredentialService.ts
packages/core/src/modules/vc/libraries/documentLoader.native.ts
packages/core/src/modules/vc/libraries/documentLoader.ts
packages/core/src/modules/vc/libraries/jsonld.ts
packages/core/src/utils/environment.ts

Fixes #993 by conditionally importing the XHR and NodeJS document loaders, based on the runtime environment.

fix: unable to resolve nodejs document loader in react native environment

---

packages/core/src/agent/AgentConfig.ts
packages/core/src/modules/connections/repository/ConnectionMetadataTypes.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/dids/helpers.ts
packages/core/src/modules/routing/__tests__/mediation.test.ts
packages/core/src/modules/routing/messages/KeylistUpdateMessage.ts
packages/core/src/modules/routing/messages/KeylistUpdateResponseMessage.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/src/modules/routing/services/MediatorService.ts
packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
packages/core/src/modules/routing/services/__tests__/MediatorService.test.ts
packages/core/src/types.ts

An initial step to support [Aries RFC 0360](https://github.com/hyperledger/aries-rfcs/tree/main/features/0360-use-did-key) by adding an optional configuration flag `useDidKeyInProtocols` that will define how agent should format keys in protocols where keys are exchanged: 'naked' (base58) or did:key encoded. 
This setting will be used unless the other party has already sent us keys (for instance, a Mediator sent us the routing key in a Mediation Grant message). In such case, their format will be used in subsequent messages for that protocol (e.g. KeyList Update). This is achieved by adding a specific metadata key `UseDidKeysForProtocol` to the related connection record, which  intended to track the other party support of did:key in different RFCs. 
Currently, only Coordinate Mediation (RFC …

feat: use did:key flag

---

packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/models/ModuleOptions.ts
packages/core/tests/v2-indy-proofs.test.ts
yarn.lock

The method getRequestedCredentialsForProofRequest was present in the API before the PPV2 code was merged but somehow got lost.
It has been restored in this PR

feat: add getRequestedCredentialsForProofRequest 

---

packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/ProofsApiOptions.ts
packages/core/src/modules/proofs/models/ProofServiceOptions.ts
packages/core/tests/v1-connectionless-proofs.test.ts
packages/core/tests/v2-connectionless-proofs.test.ts

Similar approach as #772, to be able to create a legacy Out-of-Band invitation containing a Request Proof message.
Resolves #997

refactor(proofs)!: createRequest for connectionless proof request

---

packages/core/src/utils/__tests__/shortenedUrl.test.ts
packages/core/src/utils/parseInvitation.ts

Allows content type header to have encoding in the value. To not break implementations that only use `application/json` it just checks wether the header value starts with `application/json`
The oob RFC describes the content type header with encoding in it: 
> The sender MAY include a Content-Type header specifying application/json; charset=utf-8, and in the case where the agent included an Accept header for the application/json MIME type, the sender MUST include the header. If so, the sender MUST return the invitation in JSON format in the response body with a status_code of 200.

fix(oob): allow encoding in content type header

---

demo/src/Faber.ts
packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/__tests__/V1ProofService.test.ts
packages/core/src/modules/proofs/__tests__/V2ProofService.test.ts
packages/core/src/modules/proofs/models/ProofProtocolVersion.ts
packages/core/src/modules/proofs/models/index.ts
packages/core/src/modules/proofs/protocol/v1/V1ProofService.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-presentation.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-proposal.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-request.test.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofService.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-presentation.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-proposal.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-request.test.ts
packages/core/tests/helpers.ts
packages/core/tests/proofs-sub-protocol.test.ts
packages/core/tests/v1-connectionless-proofs.test.ts
packages/core/tests/v1-indy-proofs.test.ts
packages/core/tests/v1-proofs-auto-accept.test.ts
packages/core/tests/v2-connectionless-proofs.test.ts
packages/core/tests/v2-indy-proofs.test.ts
packages/core/tests/v2-proofs-auto-accept.test.ts

Signed-off-by: Mike Richardson <mike.richardson@ontario.ca>

refactor(proofs): remove ProofProtocolVersion enum in 0.3.0-pre

---

DEVREADME.md
packages/bbs-signatures/README.md
packages/bbs-signatures/package.json
packages/react-native/package.json
yarn.lock

fix(react-native): move bbs dep to bbs package

---

packages/react-native/package.json
yarn.lock

Updates indy-sdk-react-native to 0.3.0.
Fixes #1055

chore(react-native)!: update indy-sdk-react-native to 0.3.0

---

.github/workflows/continuous-deployment.yml
lerna.json

CD is broken since #1082 has been merged, and it seems that it's because lerna is using alphabetical order when publishing packages (`lerna publish` command), so attempts to build action-menu before core (marked as peerDependency).
According to [Lerna Publish documentation](https://github.com/lerna/lerna/blob/main/commands/publish/README.md#--graph-type-alldependencies), this is because lerna uses by default a `dependencies` graph-type, which will take into account only packages listed in dependencies to determine the build order. As in this case it is listed in peerDependencies, an `all` graph-type must be used.
Another option of course would be to modify action-menu's package.json to set core as a direct dependency. However, this would be also needed for any other package that comes …

ci: use graph-type all for lerna publish

---

demo/src/AliceInquirer.ts
demo/src/BaseInquirer.ts
demo/src/FaberInquirer.ts

Signed-off-by: blu3beri <berend@animo.id>

fix(demo): direct import to remove warnings

---

packages/node/src/transport/HttpInboundTransport.ts

Allows mediator to have configurable httpinbound endpoint, instead of just '/'

feat: specify httpinboundtransport path

---

packages/core/src/agent/models/OutboundMessageContext.ts
packages/core/src/index.ts
packages/core/src/modules/discover-features/index.ts
packages/core/src/types.ts

Expose AttachmentData and Discover Features events... and some minor housekeeping to remove a few lint warnings.
Signed-off-by: Ariel Gentile <gentilester@gmail.com>

fix: expose AttachmentData and DiscoverFeaturesEvents

---

packages/core/src/agent/AgentConfig.ts
packages/core/src/modules/routing/__tests__/mediation.test.ts
packages/core/src/modules/routing/services/__tests__/MediatorService.test.ts

As discussed some time ago in #497, now we are having a new major release, we use did:key in protocols by default. We'll of course still accept base58-encoded keys if the other party is not yet using did:key.
BREAKING CHANGE:
`useDidKeyInProtocols` configuration parameter is now enabled by default. If your agent only interacts with modern agents (e.g. AFJ 0.2.5 and newer) this will not represent any issue. Otherwise it is safer to explicitly set it to `false`. However, keep in mind that we expect this setting to be deprecated in the future, so we encourage you to update all your agents to use did:key.

feat!: use did:key in protocols by default

---

packages/core/src/modules/oob/domain/index.ts

Signed-off-by: Moriarty <moritz@animo.id>
closes #1150

fix: expose OutOfBandEvents

---

packages/core/src/modules/proofs/formats/indy/IndyProofFormatsServiceOptions.ts
packages/core/src/modules/proofs/protocol/v1/handlers/V1ProposePresentationHandler.ts

refactor(proofs): remove proofrequest property

---

packages/core/src/modules/connections/ConnectionsApi.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/repository/ConnectionRecord.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts
packages/core/tests/connections.test.ts
packages/core/tests/oob-mediation.test.ts

Small update to the feature added in #994 to aggregate the connection type when a connection is related to a mediation grant. 
Previously, it was setting **only** `ConnectionType.Mediator`, so if the connection was previously tagged with another type, it would be lost.
Also fixes typing for `connectionType` in `ConnectionRecord` in order to be able to properly query for connections matching one or multiple types.

fix(routing): add connection type on mediation grant

---

packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/ProofsApiOptions.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-negotiation.test.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofService.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-negotiation.test.ts
packages/core/tests/helpers.ts

Signed-off-by: Łukasz Przytuła <lprzytula@gmail.com>
Allow proof negotiation by responding to presentation proposal with new presentation request, and responding to presentation request with new presentation proposal

feat(proofs): proof negotiation

---

packages/core/src/modules/credentials/formats/indy/IndyCredentialUtils.ts
packages/core/src/modules/credentials/formats/indy/__tests__/IndyCredentialUtils.test.ts

Signed-off-by: Łukasz Przytuła <lprzytula@gmail.com>
String values containing round decimal numbers (for example `1.0`, `6.0`) were encoded as a number (into `1` and `6` respectively) instead of properly hashing the string value, which causes issues with accepting credentials containing such values, issued by aca-py.

fix: credential values encoding

---

packages/core/src/modules/connections/ConnectionsApi.ts
packages/core/src/modules/connections/__tests__/connection-manual.e2e.test.ts

When manually accepting a connection request (either connection or did-exchange) with a reusable invitation the same keys would be used in each did response. For auto accept routing was correctly configured to create new keys for each connection. This aligns the manual flow with the auto accept flow

fix(connections): use new did for each connection from reusable invitation

---

jest.config.ts
packages/bbs-signatures/tests/v2.ldproof.credentials.propose-offerBbs.test.ts
packages/core/src/modules/credentials/formats/__tests__/JsonLdCredentialFormatService.test.ts
packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialDetail.ts
packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialDetailOptions.ts
packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormat.ts
packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts
packages/core/src/modules/credentials/formats/jsonld/index.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.connectionless-credentials.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials-auto-accept.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials.propose-offerED25519.test.ts
packages/core/src/utils/deepEquality.ts
packages/core/src/utils/objectEquality.ts

Some small improvements to the jsonld credential format services of things I discovered when using the service. It mostly includes:
- check the whole credential instead of the credentialSubject against the request
- check the created property against the proof (if it was defined)
- do not require a class as input for the credential detail options in the credentials api
- fix incorrect interfaces
- remove redundant checks

refactor: jsonld credential format improvements

---

packages/core/src/modules/dids/DidsModule.ts
packages/core/src/modules/dids/DidsModuleConfig.ts
packages/core/src/modules/dids/__tests__/DidsModule.test.ts
packages/core/src/modules/dids/__tests__/DidsModuleConfig.test.ts
packages/core/src/modules/dids/__tests__/peer-did.test.ts
packages/core/src/modules/dids/domain/DidRegistrar.ts
packages/core/src/modules/dids/domain/DidResolver.ts
packages/core/src/modules/dids/methods/key/KeyDidRegistrar.ts
packages/core/src/modules/dids/methods/key/KeyDidResolver.ts
packages/core/src/modules/dids/methods/key/__tests__/KeyDidRegistrar.test.ts
packages/core/src/modules/dids/methods/peer/PeerDidRegistrar.ts
packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
packages/core/src/modules/dids/methods/peer/__tests__/PeerDidRegistrar.test.ts
packages/core/src/modules/dids/methods/sov/IndySdkSovDidRegistrar.ts
packages/core/src/modules/dids/methods/sov/IndySdkSovDidResolver.ts
packages/core/src/modules/dids/methods/sov/__tests__/IndySdkSovDidRegistrar.test.ts
packages/core/src/modules/dids/methods/sov/__tests__/IndySdkSovDidResolver.test.ts
packages/core/src/modules/dids/methods/web/WebDidResolver.ts
packages/core/src/modules/dids/services/DidRegistrarService.ts
packages/core/src/modules/dids/services/DidResolverService.ts
packages/core/src/modules/dids/services/__tests__/DidRegistrarService.test.ts
packages/core/src/modules/dids/services/__tests__/DidResolverService.test.ts

Makes the registration of did resolvers and registrars consistent with how we do it in the credentials module by requiring class instances to be passed.
Not really a breaking change as 0.2.0 doesn't allow custom modules yet

refactor(dids): use class instances in module config

---

packages/bbs-signatures/tests/bbs-signatures.e2e.test.ts
packages/bbs-signatures/tests/bbs-signing-provider.e2e.test.ts
packages/bbs-signatures/tests/v2.ldproof.credentials.propose-offerBbs.test.ts
packages/core/src/agent/AgentConfig.ts
packages/core/src/agent/BaseAgent.ts
packages/core/src/crypto/__tests__/JwsService.test.ts
packages/core/src/decorators/signature/SignatureDecoratorUtils.test.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.connectionless-credentials.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials-auto-accept.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials.propose-offerED25519.test.ts
packages/core/src/modules/dids/__tests__/dids-resolver.e2e.test.ts
packages/core/src/modules/dids/__tests__/peer-did.test.ts
packages/core/src/modules/routing/services/MediatorService.ts
packages/core/src/modules/routing/services/RoutingService.ts
packages/core/src/modules/routing/services/__tests__/RoutingService.test.ts
packages/core/src/modules/vc/__tests__/W3cCredentialService.test.ts
packages/core/src/wallet/IndyWallet.test.ts
packages/core/src/wallet/IndyWallet.ts
packages/core/src/wallet/Wallet.ts
packages/core/tests/ledger.test.ts
packages/core/tests/mocks/MockWallet.ts

Removes the `wallet.createDid()` method from the agent. The did registrar module should be used instead to create indy dids. 
The agent.publicDid is kept in for now as it is needed by the ledger module, and we need it to add the endorser did to the agent. Intend to add a feature soon to add an existing did to the agent (for endorsement)
Also adds `@deprecated` tags to all wallet / agent public did functionality that is left to indicate these are deprecated and will be removed once we have replaced the ledger module (which will be when the new anoncreds module is ready). 
I think this is a big step in making AFJ not Indy focused.
There's some gaps in the dids module we need to resolve before it can be fully replaced, mainly:
- Migrate public dids created with the wallet to did records (can …

refactor(wallet)!: remove wallet.createDid method

---

packages/action-menu/README.md
packages/question-answer/README.md

chore: rename plugin to module

---

README.md

I noticed only the `core`, `node` and `react-native` packages were listed in the `README.md`. I'm not sure if this was done on purpose or just forgotten. I've added the `bbs-signatures`, `action-menu`, `question-answer`, and `tenants` modules and updated the `tenants` roadmap state from 🚧  to  ✅. Please comment/reject if this is incorrect.
Also, I've just appended the missing modules to the table for now. I'm not sure about the ordering of these modules/table rows. One approach is to order them alphabetically, but my personal preference is to order them by relevance.
**Example:**
1. `core` -- as you'll always need it
2. `node` & `react-native` (in random order) -- as you'll always need one of the two
3. Other modules -- as they really depend on your use case.
Signed-off-by: Karim …

docs: update readme packages

---

.husky/pre-push
package.json
yarn.lock

Removes the husky pre-push hook, as the command takes way too long to run, and we have CI to make sure we aren't including broken code.

chore: remove husky pre-push hook

---

packages/anoncreds/src/AnonCredsModule.ts
packages/anoncreds/src/AnonCredsModuleConfig.ts
packages/anoncreds/src/__tests__/AnonCredsModule.test.ts
packages/anoncreds/src/__tests__/AnonCredsModuleConfig.test.ts
packages/anoncreds/src/error/AnonCredsError.ts
packages/anoncreds/src/error/index.ts
packages/anoncreds/src/index.ts
packages/anoncreds/src/services/registry/AnonCredsRegistry.ts
packages/anoncreds/src/services/registry/AnonCredsRegistryService.ts
packages/anoncreds/src/services/registry/__tests__/AnonCredsRegistryService.test.ts
packages/indy-sdk/src/IndySdkModuleConfig.ts
packages/indy-sdk/src/anoncreds/services/IndySdkAnonCredsRegistry.ts
packages/indy-sdk/src/anoncreds/services/IndySdkHolderService.ts
packages/indy-sdk/src/anoncreds/utils/__tests__/identifiers.test.ts
packages/indy-sdk/src/anoncreds/utils/identifiers.ts

Fixes https://github.com/hyperledger/aries-framework-javascript/issues/1123, and adds the initial structure for the `AnonCredsModule`

feat(anoncreds): add anoncreds registry service

---

packages/openid4vc-client/package.json

I didn't set the package to private by accident in my previous PR. Here is the fix to avoid this from happening again.

fix(openid4vc-client): set package to private

---

demo/README.md

The link to the Nodejs prerequisites is invalid (missing a slash) and also outdated.

docs: corrected some mistakes on demo documentation

---

packages/bbs-signatures/tests/v2.ldproof.credentials.propose-offerBbs.test.ts
packages/core/src/agent/BaseAgent.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.connectionless-credentials.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials-auto-accept.test.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials.propose-offerED25519.test.ts
packages/core/src/modules/dids/__tests__/dids-registrar.e2e.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-negotiation.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-presentation.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-proposal.test.ts
packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-request.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-negotiation.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-presentation.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-proposal.test.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-request.test.ts
packages/core/src/storage/migration/__tests__/0.1.test.ts
packages/core/src/storage/migration/__tests__/0.2.test.ts
packages/core/src/storage/migration/__tests__/0.3.test.ts
packages/core/src/storage/migration/__tests__/backup.test.ts
packages/core/tests/v1-indy-proofs.test.ts
packages/core/tests/v2-indy-proofs.test.ts
packages/node/src/transport/WsInboundTransport.ts
tests/transport/SubjectOutboundTransport.ts

Marks the `agent.injectionContainer` as deprecated. We now have the `dependencyManager` that wraps the injection container from tsyringe.
This doesn't remove the property yet, but updates all usage of it in the codebase and marks it as deprecated so we can remove it in 0.4.0.

chore: deprecate injectionContainer on agent

---

packages/indy-vdr/package.json
packages/indy-vdr/src/dids/IndyVdrSovDidResolver.ts
packages/indy-vdr/src/index.ts
packages/indy-vdr/src/pool/IndyVdrPool.ts
packages/indy-vdr/src/pool/IndyVdrPoolService.ts
packages/indy-vdr/tests/helpers.ts
packages/indy-vdr/tests/indy-vdr-pool.e2e.test.ts
yarn.lock

Waiting for the release of 0.1.0-dev.4 (https://github.com/hyperledger/indy-vdr/pull/150) for response type fixing.

feat(indy-vdr): use @hyperledger packages

---

.github/workflows/continuous-integration.yml
packages/anoncreds/jest.config.ts
packages/anoncreds/tests/setup.ts

This PR adds `--forceExit --bail` to the test script when running in CI. It won't necesarily fix the issues we have with flaky tests, but it should fix the tests keeping running even though a timeout has occurred. The `--bail` means it will also stop tests after one test has failed instead of continuing running. 
Ideally we don't use `--forceExit` as it's discouraged by Jest and you should gracefully exit. However, I've been doing tests with minimal setups and I think the issue of not exiting is because of the Indy SDK doing tasks while the test times out, and that prevents from a graceful exit. I'm not sure this is the case, but this is my current feeling.
I've tried migrating to vitest over jest as it has way better logging and feels quicker / …

ci: forceExit and bail tests 

---

packages/anoncreds/src/formats/AnonCredsProofFormat.ts
packages/anoncreds/src/formats/LegacyIndyProofFormatService.ts
packages/anoncreds/src/models/AnonCredsProofRequest.ts
packages/anoncreds/src/models/AnonCredsRequestedAttribute.ts
packages/anoncreds/src/models/AnonCredsRequestedPredicate.ts
packages/anoncreds/src/models/AnonCredsRestriction.ts
packages/anoncreds/src/models/__tests__/AnonCredsRestriction.test.ts

Some small changes and an extra test to test anoncreds restriction transformation

test: add anoncreds restriction test

---

packages/askar/package.json
packages/askar/src/wallet/AskarWallet.ts
packages/askar/src/wallet/__tests__/AskarWallet.test.ts

The one that was returned by `AskarWallet.generateNonce()` is not usable for AnonCreds proofs and credential issuance flow, so it is now adjusted to return something equivalent to what's in IndyWallet or anoncreds-rs.
As part of a further refactor, this functionality will be most likely moved to `anoncreds` package, as it is more related to AnonCreds specification than the Wallet itself.

fix(askar): generate nonce suitable for anoncreds

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.env
.devcontainer/devcontainer.json
DEVREADME.md

Initial work on adding devcontainer support to make development easier for Mac, Windows and Linux. The [Dockerfile](.devcontainer/Dockerfile) located in the `.devcontainer` directory is used to build the working container.
Fixes #1281

feat: add devcontainer support

---

packages/indy-sdk/tests/indy-sdk-anoncreds-registry.e2e.test.ts

Let's see if these gracious delay helps us to pass Indy SDK E2E tests in CI.

test(indy-sdk): wait before resolving ledger objects

---

packages/core/src/transport/WsOutboundTransport.ts

Found issue where sending message fails with `Socket is not open.` when only using websocket transports (no http transports).
WS is used to create initial connection, and then starts before mediation request, causing socket state to update to 'CLOSING'. Since this is done before the `close` event is emitted, the relevant socket map value  of `WsOutboundTransport` hasn't been deleted yet, so when we try to send the next message too quickly this error case can happen.

fix: create new socket if socket state is 'closing'

---

.eslintrc.js
demo/src/BaseAgent.ts
demo/src/Faber.ts
package.json
packages/indy-sdk/src/ledger/serializeRequestForSignature.ts
yarn.lock

A relative import from core was preventing indy-sdk from being built correctly.
Here we add an eslint plugin to check these relative imports and other stuff that can be useful now we have plenty of packages in this repo.

fix(indy-sdk): import from core

---

packages/anoncreds-rs/src/services/AnonCredsRsHolderService.ts

When storing AnonCreds credentials, we weren't saving the revocation registry index, making it impossible to properly search for the credential in `RevocationNotificationService`.

fix(anoncreds-rs): save revocation registry index

---

packages/action-menu/src/ActionMenuApi.ts
packages/core/src/agent/Dispatcher.ts
packages/core/src/agent/__tests__/Dispatcher.test.ts
packages/core/src/modules/basic-messages/BasicMessagesApi.ts
packages/core/src/modules/connections/ConnectionsApi.ts
packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts
packages/core/src/modules/credentials/protocol/revocation-notification/services/__tests__/RevocationNotificationService.test.ts
packages/core/src/modules/discover-features/protocol/v1/V1DiscoverFeaturesService.ts
packages/core/src/modules/discover-features/protocol/v1/__tests__/V1DiscoverFeaturesService.test.ts
packages/core/src/modules/discover-features/protocol/v2/V2DiscoverFeaturesService.ts
packages/core/src/modules/discover-features/protocol/v2/__tests__/V2DiscoverFeaturesService.test.ts
packages/core/src/modules/discover-features/services/DiscoverFeaturesService.ts
packages/core/src/modules/routing/MediatorApi.ts
packages/core/src/modules/routing/RecipientApi.ts
packages/core/src/modules/routing/protocol/pickup/v1/MessagePickupService.ts
packages/core/src/modules/routing/protocol/pickup/v2/V2MessagePickupService.ts
packages/core/src/modules/routing/services/__tests__/V2MessagePickupService.test.ts
packages/question-answer/src/QuestionAnswerApi.ts
samples/extension-module/dummy/DummyApi.ts

It was marked as deprecated since 0.3.0
BREAKING CHANGE:
`Dispatcher.registerMessageHandler` has been removed in favour of `MessageHandlerRegistry.registerMessageHandler`

refactor!: remove Dispatcher.registerMessageHandler

---

packages/core/src/transport/WsOutboundTransport.ts

`isNewSocket` was holding whether the socket already exists to an endpoint. I think the logic for closing the socket in `sendMessage` should be : 
```ts
const socket = await this.resolveSocket({ socketId: endpoint, endpoint, connectionId })
socket.send(Buffer.from(JSON.stringify(payload)))
// If the socket was created for this message and we don't have return routing enabled
// We can close the socket as it shouldn't return messages anymore
if (socket && !outboundPackage.responseRequested) {
socket.close()
}
```
As per current logic, the socket is closed only when a message has `responseRequested=false` and a new socket is created just for this message. Let's suppose a message (`responseRequested=false` and socket already exists), in this case sender won't call `socket.close()`. But the …

fix: isNewSocket logic

---

.eslintrc.js
.github/workflows/continuous-integration.yml
packages/anoncreds/tests/setup.ts
packages/askar/src/storage/__tests__/AskarStorageService.test.ts
packages/askar/src/wallet/__tests__/AskarWallet.test.ts
packages/askar/src/wallet/__tests__/packing.test.ts
packages/bbs-signatures/tests/util.ts
packages/tenants/tests/setup.ts
scripts/add-ref-napi-resolution.js
tests/e2e-askar-indy-sdk-wallet-subject.test.ts
tests/runInVersion.ts

This PR adds a few improvements to the test setup that should hopefully prevent timeouts, but also make sure we test the askar setup:
- only run askar related tests in node18
- add ref-napi resolution in node18
- increase timeout for some packages that often timeout

test: various improvements

---

packages/tenants/src/context/TenantSessionCoordinator.ts
packages/tenants/src/context/__tests__/TenantSessionCoordinator.test.ts

Fixes hyperledger/aries-framework-javascript#1353

fix(tenant): Correctly configure storage for multi tenant agents

---

packages/anoncreds/src/utils/credential.ts

Subtle omission that was causing `encodeCredentialValue` to fail under React Native.

fix(anoncreds): Buffer not imported from core

---

packages/action-menu/tests/setup.ts
packages/anoncreds-rs/tests/setup.ts
packages/anoncreds/tests/setup.ts
packages/askar/tests/setup.ts
packages/bbs-signatures/tests/setup.ts
packages/indy-sdk/tests/setup.ts
packages/indy-vdr/tests/setup.ts
packages/openid4vc-client/tests/setup.ts
packages/question-answer/tests/setup.ts
packages/tenants/tests/setup.ts
samples/extension-module/tests/setup.ts

Github action runners are slow as fuck, so I've just increased them all to 2 minutes now.

test: increase timeout to 120 seconds

---

packages/askar/src/wallet/AskarWallet.ts
packages/askar/src/wallet/__tests__/AskarWallet.test.ts
packages/askar/tests/askar-sqlite.e2e.test.ts
packages/askar/tests/helpers.ts
packages/core/src/storage/FileSystem.ts
packages/node/src/NodeFileSystem.ts
packages/react-native/src/ReactNativeFileSystem.ts

Add support for wallet export and import by copying sqlite file and executing a key rotation to the one specified in the `WalletExportImportConfig` object. Similarly, when importing the wallet it will copy the origin file to the expected directory according to wallet id and do a rekey to the key specified.
In addition, there are a few tweaks and fixes for things I found during testing such as: 
- Key object handles clearing in pack/unpack and key creation/signing/verification methods
- Check wallet database file is created before (not sure why, but Askar is not throwing Duplicate error in `Store.provision` when wallet exists). This only works for SQLite but it's better than nothing
- Use key derivation based in argon2 Int if nothing specified, as it's the default in Indy SDK AFAIK

feat(askar): import/export wallet support for SQLite

---

packages/indy-sdk/src/anoncreds/utils/__tests__/identifiers.test.ts
packages/indy-sdk/src/anoncreds/utils/identifiers.ts
packages/indy-vdr/src/anoncreds/utils/_tests_/identifiers.test.ts
packages/indy-vdr/src/anoncreds/utils/identifiers.ts

named capture groups are only supported in more recent versions of hermes
It was of course stupid from me to assume regexes would be fully supported by hermes 🙃

fix: remove named capture groups

---

packages/core/src/agent/TransportService.ts
packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
packages/core/src/modules/connections/handlers/DidExchangeRequestHandler.ts
packages/core/src/modules/routing/__tests__/pickup.test.ts

When a message for a connection request (either for DID Exchange or Connection protocol) is received, a session is created without any connection id associated to it (as it is not created yet).
If the party requesting a connection does not have a public endpoint (e.g. a edge agent connecting to a mediator) and the responder does not have `autoAcceptConnections` enabled, it will not associate this session to the newly created connection, forcing any call to `agent.connections.acceptRequest` to queue the messages, even if the transport used allows a persistent connection (typical case for WebSockets).
So here what we do is simply to associate the connection to the session as soon as it is created. At the moment I don't see any drawback of this strategy but will be happy to hear any …

fix: connection id in sessions for new connections

---

packages/anoncreds-rs/tests/anoncreds-flow.test.ts
packages/anoncreds/src/formats/AnonCredsCredentialFormatService.ts
packages/anoncreds/src/formats/AnonCredsProofFormatService.ts
packages/anoncreds/src/formats/index.ts
packages/anoncreds/src/models/exchange.ts

Add Credential and Proof format services according to [Aries RFC 0771](https://github.com/hyperledger/aries-rfcs/tree/main/features/0771-anoncreds-attachments).
Essentially the same as Legacy Indy counterparts but using the new identifiers, using entropy instead of prover_did for Credential Request and not restricting identifiers to legacy Indy format, so any AnonCreds method can be used with them.

feat(anoncreds): add AnonCreds format services

---

packages/anoncreds-rs/src/services/AnonCredsRsHolderService.ts
packages/anoncreds-rs/src/services/__tests__/AnonCredsRsHolderService.test.ts
packages/anoncreds/src/AnonCredsApi.ts
packages/anoncreds/src/services/AnonCredsHolderService.ts
packages/anoncreds/src/services/AnonCredsHolderServiceOptions.ts
packages/indy-sdk/src/anoncreds/services/IndySdkHolderService.ts

feat(anoncreds): add getCredential(s) methods

---

packages/indy-vdr/tests/helpers.ts
packages/indy-vdr/tests/indy-vdr-did-registrar.e2e.test.ts

In Indy VDR tests, after DID creation we are attempting to resolve the recently created DID immediately, which does not always work properly in CI. Here we add the 1000 ms delay that we also do in other Indy registrar tests.

test(indy-vdr): add delay after DID creation

---

packages/core/src/modules/connections/DidExchangeProtocol.ts
packages/core/tests/oob.test.ts

It was already fixed for Connection protocol in https://github.com/hyperledger/aries-framework-javascript/pull/896 but missing for DID Exchange.

fix(connections): store imageUrl when using DIDExchange

---

demo/package.json
packages/indy-vdr/package.json
yarn.lock

I'm not sure if @hyperledger/indy-vdr-shared and @hyperledger/indy-vdr-nodejs versions are fixed to a particular version on purpose, but tests seem to work fine on the latest 0.1.0-dev.14.
This is mainly to fix https://github.com/hyperledger/aries-agent-test-harness/issues/669. If the version should be fixed to dev.13, another possibility is to fix it in the AATH backchannel.

fix(indy-vdr): do not force indy-vdr version

---

packages/askar/src/wallet/AskarWallet.ts
packages/indy-sdk-to-askar-migration/src/IndySdkToAskarMigrationUpdater.ts

Some small issues related to the migration script, mostly to do with write ahead logging.
Now the database is always copied with the optional wal file.

fix: small issues with migration and WAL files

---

packages/core/src/modules/routing/services/MediatorService.ts

Added `RoutingCreatedEvent` emit after creation of mediator routing record in `MediatorService`.
This change is required to enable mediator functionality for tenant agents as `registerRecipientKeyForTenant` will not be called for mediator routing key otherwise (done in `RoutingCreatedEvent` listener).

fix: Emit RoutingCreated event for mediator routing record

---

packages/openid4vc-client/src/OpenId4VcClientService.ts

Previously the `requestCredential` method would throw an error if the `scope` parameter was not present in the `access_token` response. This `scope` value was used to indicate the desired credential type when requesting the credential. However, this was incorrect, as this value is optional according to the [specification](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.2.2).
This PR removes the requirement for the `scope` to be present on the `access_token` response. If the `scope` is present, it will be used to check if the server metadata indicates the requested credential format is supported for the requested credential type (indicated by the `scope`). If not, this validation is skipped.
When the `access_token` response does not contain a `scope`, the `credentialType` value that …

fix: remove scope check from response

---

packages/react-native/src/ReactNativeFileSystem.ts

Some schema names can have characters that are not supported by URL loaders without being encoded. This PR fixes this issue by url encoding before passing the URL off to the loading mechanics. I tested this change agains the issue that reports the problem and it does fix the problem.
Fixes #1478

fix: encode tails url

---

packages/askar/src/wallet/AskarWallet.ts
packages/askar/src/wallet/__tests__/packing.test.ts
packages/askar/src/wallet/__tests__/testVectors.ts
packages/core/src/agent/EnvelopeService.ts
packages/core/src/crypto/Key.ts
packages/core/src/didcomm/JweEnvelope.ts
packages/core/src/didcomm/versions/v2/index.ts
packages/core/src/didcomm/versions/v2/types.ts
packages/core/src/modules/dids/domain/DidDocument.ts
packages/core/src/wallet/Wallet.ts
packages/indy-sdk/src/wallet/IndySdkWallet.ts
yarn.lock

- Added tests for DidComm V2 message packing
- Fixed issue to pass test vectors from the spec:  https://identity.foundation/didcomm-messaging/spec/#appendix
**Issue with the current implementation**: we need to use DID Resolver to unpack messages properly:
- resolve sender key from `skid`
- resolve recipient key from `kid`

test: tests for DidComm V2 message packing

---

packages/react-native/src/ReactNativeFileSystem.ts

Check to make sure an URL is not already encoded before encoding it. If this happens it will create an erronious URL.
Fixes #1484

fix: check if URL already encoded

---

packages/core/src/modules/cache/singleContextLruCache/SingleContextStorageLruCache.ts
packages/core/src/modules/routing/services/MediatorService.ts

Fixes https://github.com/hyperledger/aries-framework-javascript/issues/968
This just handles the multiple creation and then erroring of signleton records. 
We still have an issue with multiple writes to the same document, which we should be able to fix with locks

fix: race condition singleton records

---

packages/node/src/transport/HttpInboundTransport.ts
samples/mediator.ts

Adds `IndySdkModule` to `Agent` modules in order to allow it to have a default Wallet and Storage implementation (it could be Askar once we solve the performance issue for node <18 and/or drop support for it).
In `HttpInboundTransport`, It also moves content-type validation to the specific endpoint rather than the whole HTTP server. This is needed to allow using an invitation endpoint.

fix(samples): mediator wallet and http transport

---

packages/askar/src/wallet/AskarWallet.ts
packages/askar/tests/askar-inmemory.e2e.test.ts
packages/askar/tests/helpers.ts

Quick fix to allow the creation of an in-memory wallet (for test purposes). Previously, the parameter was supported but, due to a particular error thrown by `@hyperledger/askar-shared` it was not working.

fix(askar): in memory wallet creation

---

packages/askar/src/AskarModule.ts
packages/askar/src/AskarModuleConfig.ts
packages/askar/src/index.ts
packages/askar/src/storage/AskarStorageService.ts
packages/askar/src/utils/assertAskarWallet.ts
packages/askar/src/wallet/AskarBaseWallet.ts
packages/askar/src/wallet/AskarProfileWallet.ts
packages/askar/src/wallet/AskarWallet.ts
packages/askar/src/wallet/__tests__/AskarProfileWallet.test.ts
packages/askar/src/wallet/index.ts
packages/core/src/types.ts
packages/tenants/tests/tenants-askar-profiles.e2e.test.ts

Adds support for using askar profiles in multi-tenancy, so you don't have to create a new database for each tenant.
As commented on #1486, I've made some 'hacks' to make it work with the currrent API. I think extracting the wallet management from the wallet implementation can clean some things up, as well as having a more sophisticated wallet provider that is a bit more aware of having possible multilple wallets active at the same time within an agent.
The askar module now has a new `multiWalletDatabaseScheme` with two options: `ProfilePerWallet` or `DatabasePerWallet`. the database per wallet is the default to not make breaking changes, and profiel per wallet will reuse the same store for all wallets.
This is the only thing you have to do to benefit from this new feature. I've used the …

feat: support askar profiles for multi-tenancy

---

demo/src/Faber.ts
demo/src/FaberInquirer.ts
packages/core/src/agent/MessageReceiver.ts
packages/core/src/modules/oob/protocols/v1/OutOfBandService.ts
packages/core/src/modules/oob/repository/OutOfBandRecord.ts

When a connection is auto-created after receiving first DIDComm v2 message, the OOB record that generated the invitation is not associated to it. So it becomes difficult to find it it afterwards. 
This happened to Faber in the demo, and may happen to you as well!

fix: add OOB id to auto-created connection

---

packages/cheqd/src/CheqdModule.ts
packages/cheqd/src/CheqdModuleConfig.ts
packages/cheqd/src/ledger/CheqdLedgerService.ts

Makes the cosmos payer seed optional, as you can also used it as a holder without payer seed.

fix(cheqd): make cosmos payer seed optional

---

packages/core/src/transport/WsOutboundTransport.ts

Updated `WsOutboundTransport` to use `connectionId` as part of WS connection identifier. In current implementation, only `endpoint` value is used.
This change fixes issue in use cases where tenant agent acts as a mediator:
- For instance, we have mediator and issuer agents hosted inside same multi-tenant AFJ instance and we also have a holder agent on mobile device. Holder on a mobile device has an active WS connection with a mediator.
- Currently, WS connection will be reused if it's already open for the same endpoint. This means that message sent from holder to issuer via WS transport will go through mediator WS connection
- On multi-tenant instance side, this message will be received with existing transport session of mediator WS connection
- This will cause transport session (along …

fix(transport): Use connection in WebSocket ID

---

Dockerfile

This PR fixes a blocker in the docker file where the source openssl libs are no longer available.

fix: bump missing dependencies version

---

packages/core/src/agent/TransportService.ts

We found an edge-case where a websocket transport session would be closed/unavailable on the client agent side, but mediator still thinks it is available (due to client being offline).
When client returns back online and initiates a flow via mediator, the mediator will attempt to send the package to the now outdated websocket, instead of the newest / current session.
This PR fixes the problem, but is there any reason why a single connection may need multiple open WebSocket transport sessions?

fix: do not send package via outdated session

---

packages/core/package.json

Our good friend @dependabot with its #1565 made me remember we had this dependency on core that shouldn't be there. Didn't go further in order to not deal with breaking changes. I think we can move to node-fetch v3 (and see how to deal `AgentDependencies` types) in a next major release.
Fixes #1492

fix(core): remove node-fetch dependency

---

packages/core/src/utils/__tests__/shortenedUrl.test.ts
packages/core/src/utils/parseInvitation.ts

feat: allow connection invitation encoded in oob url param

---

packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/services/ConnectionService.ts

When creating the DID document, In `connections` protocol we are generating a DIDComm service per endpoint, but using the same `id` for all of them.

fix: duplicate service ids in connections protocol

---

packages/core/src/modules/connections/ConnectionsModuleConfig.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/didcomm/services/DidCommDocumentService.ts
packages/core/src/modules/didcomm/services/__tests__/DidCommDocumentService.test.ts
packages/core/src/modules/oob/OutOfBandApi.ts
packages/core/src/modules/oob/__tests__/implicit.e2e.test.ts

It seems that  our implicit invitation implementation for DID Exchange does not conform exactly with what's written in [RFC 0023](https://github.com/hyperledger/aries-rfcs/blob/main/features/0023-did-exchange/README.md):
>An invitation is presented in one of two forms:
> An explicit [out-of-band invitation](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#messages) with its own @id.
> An implicit invitation contained in a DID document's [service](https://w3c-ccg.github.io/did-spec/#service-endpoints) attribute that conforms to the [DIDComm conventions](https://github.com/hyperledger/aries-rfcs/blob/main/features/0067-didcomm-diddoc-conventions/README.md#service-conventions).
> When a request responds to an explicit invitation, its ~thread.pthid MUST be …

fix: implicit invitation to specific service

---

packages/core/src/modules/oob/__tests__/OutOfBandInvitation.test.ts
packages/core/src/modules/oob/messages/OutOfBandInvitation.ts

I'm not an expert (neither a fan 😝) of `class-validator` but I recently found an issue when creating an `OutOfBandInvitation` instance whose `service` field contains a plain string. It works and allows to do a `toUrl()` and so on, but when it passes through the MessageValidator it threw an error saying:
```
OutOfBandInvitation: Failed to validate class.
An instance of OutOfBandInvitation has failed the validation:
- property services[0] has failed the following constraints: each value in nested property services must be either object or array·
```
I found that services field has both `@IsStringOrInstance` and `@ValidateNested` decorators. The first one seems to be doing the correct check on every element of the array, while the latter (which is the one  throwing the error) seems to me …

fix: service validation in OOB invitation objects

---

packages/anoncreds/src/repository/AnonCredsCredentialRecord.ts

For some unfortunate reason, we are not saving `createdAt` at AnonCredsCredentialRecord creation. This is useful to do things like sorting credentials by their issuance date (something available with W3C Credential Reacords)

fix: save AnonCredsCredentialRecord createdAt

---

packages/anoncreds/src/utils/getRevocationRegistries.ts

Previously when fetching multiple revocation registries, afj would wait for the response from the first request before sending off the second request. I added functionality to send off all requests at once and then wait for all responses. This makes the code more async and faster

feat: sped up lookup for revocation registries

---

Dockerfile
package.json
samples/mediator.ts

Intermediate solution until we finally remove `indy-sdk` dependency: current Dockerfile won't work because it install node 16 and we now require at least 18, so here we are updating it. Also upgraded sample mediator to use Aries Askar, which now works properly due to the patched `ref-napi` library.
Resolves #1621

feat: update dockerfile to node 18 and sample mediator to askar

---

package.json
packages/core/package.json
packages/core/src/agent/AgentDependencies.ts
packages/core/src/transport/HttpOutboundTransport.ts
packages/core/src/utils/__tests__/shortenedUrl.test.ts
packages/core/src/utils/parseInvitation.ts
packages/node/package.json
packages/node/src/index.ts
yarn.lock

As now our minimal supported node version is 18, which has a built-in fetch API, this is an attempt to get rid of external `node-fetch` dependency on `@aries-framework/core`.
Credits to @dependabot, who give us the idea!

build(deps): use node's built-in fetch

---

demo/package.json
packages/indy-vdr/package.json
yarn.lock

It is already done in other open PRs, but just wanted to do this small one as it is getting a bit annoying to work on macOS these days 😞. This new release of `indy-vdr` wrapper takes the correct binary for this platform.

feat: bump indy-vdr version

---

MAINTAINERS.md

This PR contains the following changes to `MAINTAINERS.md`:
- Updated @berendsliedrecht's GitHub handle
- @berendsliedrecht, I've left your Discord handle untouched as it looks like you didn't update it.
- Removed @JamesKEbert (with approval from James)

docs: update active maintainers

---

packages/core/src/agent/__tests__/Agent.test.ts
packages/core/src/modules/connections/ConnectionsApi.ts
packages/core/src/modules/connections/ConnectionsModule.ts
packages/core/src/modules/connections/ConnectionsModuleConfig.ts
packages/core/src/modules/connections/DidExchangeProtocol.ts
packages/core/src/modules/connections/__tests__/InMemoryDidRegistry.ts
packages/core/src/modules/connections/__tests__/didexchange-numalgo.e2e.test.ts
packages/core/src/modules/connections/messages/DidExchangeCompleteMessage.ts
packages/core/src/modules/connections/messages/DidExchangeProblemReportMessage.ts
packages/core/src/modules/connections/messages/DidExchangeRequestMessage.ts
packages/core/src/modules/connections/messages/DidExchangeResponseMessage.ts
packages/core/src/modules/connections/models/HandshakeProtocol.ts
packages/core/src/modules/didcomm/services/DidCommDocumentService.ts
packages/core/src/modules/dids/DidsApi.ts
packages/core/src/modules/dids/__tests__/DidsApi.test.ts
packages/core/src/modules/dids/domain/DidDocument.ts
packages/core/src/modules/dids/methods/peer/PeerDidRegistrar.ts
packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts
packages/core/src/modules/dids/methods/peer/__tests__/PeerDidRegistrar.test.ts
packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer4zQmUJdJ.json
packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer4zQmd8Cp.json
packages/core/src/modules/dids/methods/peer/__tests__/peerDidNumAlgo4.test.ts
packages/core/src/modules/dids/methods/peer/createPeerDidDocumentFromServices.ts
packages/core/src/modules/dids/methods/peer/didPeer.ts
packages/core/src/modules/dids/methods/peer/peerDidNumAlgo4.ts
packages/core/src/modules/dids/repository/DidRecord.ts
packages/core/src/modules/dids/repository/DidRepository.ts
packages/core/src/modules/oob/OutOfBandApi.ts
packages/core/tests/oob.test.ts

Add support to `did:peer:2` and `did:peer:4` in DID Exchange protocol, in order to start aligning with [RFC 0793](https://github.com/hyperledger/aries-rfcs/blob/fcb2cafce6abea0995804c32a6da473c8894e470/features/0793-unqualfied-dids-transition/README.md).
This includes the recent changes in signatures for DID Exchange 1.1, as specified in [RFC 0023](https://github.com/hyperledger/aries-rfcs/blob/main/features/0023-did-exchange/README.md#request-message-attributes).
Currently, AFJ uses qualified DIDs for DID Exchange protocol, in `did:peer:1` format. The community is going towards `did:peer:2` and the new `did:peer:4` (more meaningful in DIDComm v2 world). So in this PR we are trying to do the transition from `did:peer:1` to `did:peer:4` in order to be compatible with ACA-Py when it adds …

feat: did:peer:2 and did:peer:4 support in DID Exchange

---

MAINTAINERS.md

Removes @janrtvld (now @janrxyz) from the maintainers. Have coordinated this with him

chore: removed jan as maintainer

---

packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/discover-features/DiscoverFeaturesApi.ts
packages/core/src/modules/oob/OutOfBandApi.ts
packages/core/src/modules/routing/MediationRecipientApi.ts
packages/core/src/modules/routing/services/MediationRecipientService.ts

This adds a `meta` key to all the meta errors within the framework that contains the class + method name, as it's currently very hard to see where an rxjs timeout error originated.
This will be printed in the error message, and should make debugging easier.
```
TimeoutError: Timeout has occurred
info: {
"meta": "<the meta value>",
"lastValue": null,
"seen": 0
}
```

chore: add meta to rxjs timeout errors

---

packages/core/src/crypto/Key.ts

This makes sure that at least in the ConsoleLogger the `Key` class is printend as the `fingerprint` property, so we avoid this:
```
{
"publicKey": {
"type": "Buffer",
"data": [
67,
227,
94,
17,
202,
44,
168,
217,
210,
62,
120,
65,
119,
12,
186,
150,
210,
1,
153,
142,
54,
158,
119,
223,
138,
189,
1,
4,
72,
145,
192,
23
]
},
"keyType": "ed25519"
}
```

fix: properly print key class

---

packages/core/src/modules/proofs/protocol/v2/__tests__/v2-presentation-exchange-presentation.e2e.test.ts

fix(present-proof): isolated tests

---

.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml

Same issue as the one fixed in #1669 when we changed from aries-framework-javascript to agent-framework-javascript.
Also updates the deprecated setup-node action (supersedes #1624).

ci: fix git checkout path and update setup-node

---

packages/anoncreds-rs/tests/LocalDidResolver.ts
packages/cheqd/src/dids/CheqdDidResolver.ts
packages/core/src/modules/connections/__tests__/InMemoryDidRegistry.ts
packages/core/src/modules/dids/domain/DidResolver.ts
packages/core/src/modules/dids/methods/jwk/JwkDidResolver.ts
packages/core/src/modules/dids/methods/key/KeyDidResolver.ts
packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
packages/core/src/modules/dids/methods/web/WebDidResolver.ts
packages/core/src/modules/dids/services/DidResolverService.ts
packages/core/src/modules/dids/services/__tests__/DidResolverService.test.ts
packages/core/src/modules/dids/types.ts
packages/indy-sdk/src/dids/IndySdkIndyDidResolver.ts
packages/indy-sdk/src/dids/IndySdkSovDidResolver.ts
packages/indy-vdr/src/dids/IndyVdrIndyDidResolver.ts
packages/indy-vdr/src/dids/IndyVdrSovDidResolver.ts
packages/tenants/tests/tenants.e2e.test.ts

Adds support for caching of did resolver results. I saw that in a lot flows we're resoling the same did multiple times, and thus sometimes hitting the ledger 5 times for the same did. This adds a default cache of 5 minutes for did documents.
You can disable this by passing options to resolve, and I've disabled it for dids where it doesn't make sense: `did:peer`, `did:key` and `did:jwk`.
BREAKING CHANGE: it is now required to set the `allowsCaching` on a `DidResolver` implementation. When set to `true` the `DidResolverService` will allow the results from the `DidResolver` implementation to be cached. When `false`, a result from the `DidResolver` will NEVER be cached. It is advised to not allow caching for dynamically generated or stored did documents (such as `did:peer`, `did:key` and …

feat(dids)!: did caching

---

README.md
packages/anoncreds/README.md
packages/askar/README.md
packages/bbs-signatures/README.md
packages/cheqd/README.md
packages/core/README.md
packages/indy-sdk-to-askar-migration/README.md
packages/indy-vdr/README.md
packages/tenants/README.md

Some cleanup updates to the README.
I've moved some sections over to the docs, we should probably also move the left-over parts to the docs (like installation for Action menu package) so it's not scattered anymore.
Will open a PR in docs soon also with migration etc.. and all the changes in 0.5.0

docs: readme cleanup

---

packages/anoncreds/src/AnonCredsApi.ts

Encountered an issue where the rev reg def was stored twice and that will create an error when the status list is created

fix(anoncreds): only store the revocation registry definition when the state is finished

---

packages/anoncreds/src/AnonCredsApi.ts
packages/indy-vdr/src/anoncreds/utils/__tests__/transform.test.ts
packages/indy-vdr/src/anoncreds/utils/transform.ts

Encountered a bug where the newly revoked idx was in the issued and revoked list. New test covers this case.

fix(indy-vdr): for creating latest delta

---

packages/core/src/modules/credentials/protocol/CredentialProtocolOptions.ts
packages/core/src/modules/credentials/protocol/v2/CredentialFormatCoordinator.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialProtocol.ts
packages/core/src/modules/credentials/protocol/v2/messages/V2IssueCredentialMessage.ts
packages/core/src/modules/credentials/protocol/v2/messages/V2OfferCredentialMessage.ts
packages/core/src/modules/credentials/protocol/v2/messages/V2ProposeCredentialMessage.ts
packages/core/src/modules/credentials/protocol/v2/messages/V2RequestCredentialMessage.ts
packages/core/src/modules/proofs/protocol/ProofProtocolOptions.ts
packages/core/src/modules/proofs/protocol/v2/ProofFormatCoordinator.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofProtocol.ts
packages/core/src/modules/proofs/protocol/v2/messages/V2PresentationMessage.ts
packages/core/src/modules/proofs/protocol/v2/messages/V2ProposePresentationMessage.ts
packages/core/src/modules/proofs/protocol/v2/messages/V2RequestPresentationMessage.ts

Adds the `goal` and `goal_code` properties to all the messages and interfaces for v2 protocols.
`goal_code` was already enabled for proof messages, but not goal. No validation, no logic to it, just something an user of Credo can use to add context to an exchange. 
Goal codes are adopted by v2 of the protocols.

feat: add goal codes to v2 protocols

---

packages/core/src/modules/message-pickup/MessagePickupApi.ts
packages/core/src/modules/message-pickup/MessagePickupApiOptions.ts
packages/core/src/modules/message-pickup/MessagePickupEvents.ts
packages/core/src/modules/message-pickup/__tests__/pickup.test.ts
packages/core/src/modules/message-pickup/protocol/v1/V1MessagePickupProtocol.ts
packages/core/src/modules/message-pickup/protocol/v1/handlers/V1BatchHandler.ts
packages/core/src/modules/message-pickup/protocol/v2/V2MessagePickupProtocol.ts
packages/core/src/modules/message-pickup/protocol/v2/handlers/V2StatusHandler.ts
packages/core/src/modules/routing/MediationRecipientApi.ts

Add a blocking mode for `MessagePickupApi.pickupMessages()`, where the agent will wait until all messages have been effectively retrieved and therefore the message pickup process is completed.
This tries to solve two main situations:
1) Retrieve queued messages BEFORE setting live mode in agents configured with `MediatorPickupStrategy.PickUpV2LiveMode`. This allows supporting the case where the mediator does not support `live-delivery-change` message (which is the case of AFJ <= 0.4.2 and AFAIK ACA-Py's Pick-up v2 plug-in). In such case, mediator will send a problem report that will be logged in the recipient but should not prevent the pick-up flow from being started
2) Facilitate the creation of a process dedicated to message pickup only. For instance, this can be used in mobile agents …

feat(mesage-pickup): option for awaiting completion

---

packages/indy-vdr/src/pool/IndyVdrPoolService.ts

Updated `getAllPoolTransactions` method to include the pool config as part of the result so we know which pool is which.
BC Wallet already uses this in a yarn patch to the Credo-ts package. I figured I'd get it in the main repo so others could use it and we didn't have to keep maintaining the patch.

feat: updated getAllPoolTransactions method

---

demo-openid/package.json
demo/package.json
packages/anoncreds/package.json
yarn.lock

Updated to v0.2.1 to allow building on React Native (wrong libanoncreds header). See https://github.com/hyperledger/anoncreds-rs/pull/327

chore: update anoncreds-rs

---

packages/anoncreds/src/protocols/credentials/v1/V1CredentialProtocol.ts
packages/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts
packages/core/src/modules/credentials/protocol/v2/CredentialFormatCoordinator.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialProtocol.ts
packages/core/src/modules/proofs/protocol/v2/ProofFormatCoordinator.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofProtocol.ts
packages/core/src/modules/proofs/protocol/v2/handlers/V2PresentationHandler.ts
packages/core/src/storage/didcomm/DidCommMessageRepository.ts

- Added an additional requirement to the query to find an agent message. This was added so you can technically offer a credential, and request a proof, to yourself. No changes in the current behavior.

fix(core): query credential and proof records by correct DIDComm role

---

packages/drpc/src/DrpcApi.ts

Previously the drpc method `recvRequest` would receive messages that had just been send by the agent. This is a quick fix to ensure the method on receives incoming requests from other agents

fix: stopped recvRequest from receiving outbound messages

---

packages/anoncreds/src/protocols/credentials/v1/V1CredentialProtocol.ts
packages/anoncreds/src/protocols/credentials/v1/__tests__/V1CredentialProtocolCred.test.ts
packages/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts
packages/core/src/modules/credentials/protocol/BaseCredentialProtocol.ts
packages/core/src/modules/credentials/protocol/CredentialProtocol.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialProtocol.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialProtocolCred.test.ts
packages/core/src/modules/proofs/protocol/BaseProofProtocol.ts
packages/core/src/modules/proofs/protocol/ProofProtocol.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofProtocol.ts

- Missed in the last PR regarding issuance to self. We also have to make sure when finding the credential, or proof, exchange record, that the role is correct otherwise we will find multiple instances with the same connection id and thread id.
- Fixed some of the deprecated jest functions (just the ones I came across).

fix: query the record by credential and proof role

---

packages/core/src/transport/WsOutboundTransport.ts

The previous approach was only possible in Node.
The websocket implementation of RN follows this specification. https://developer.mozilla.org/en-US/docs/Web/API/WebSocket. 
The Promise was therefore never resolved as the callback does not exist.

fix: websocket outbound transport

---

packages/anoncreds/src/formats/DataIntegrityCredentialFormatService.ts
packages/anoncreds/src/utils/credential.ts
packages/anoncreds/src/utils/index.ts
packages/anoncreds/src/utils/indyIdentifiers.ts
packages/core/src/modules/dif-presentation-exchange/DifPresentationExchangeService.ts
packages/core/src/modules/dif-presentation-exchange/utils/presentationsToCreate.ts
packages/core/src/modules/proofs/formats/dif-presentation-exchange/DifPresentationExchangeProofFormat.ts
packages/core/src/transport/WsOutboundTransport.ts

fix: usage of wrong buffer implementation
fix: w3c anoncreds don't require a credential subject id to be present

fix: w3c anoncreds

---

packages/core/src/modules/credentials/CredentialsApi.ts
packages/core/src/modules/credentials/CredentialsApiOptions.ts
packages/core/src/modules/proofs/ProofsApi.ts
packages/core/src/modules/proofs/ProofsApiOptions.ts

Adds same functionality available in proofs api, allowing to send a problem report when declining a credential offer. Also adds support for sending a problem report if no connection is available on the exchange (when doing e.g. message attached to oob invitation)

feat: credentials api decline offer report

---

docker-compose.arm.yml
docker-compose.yml
packages/cheqd/src/dids/didCheqdUtil.ts
packages/cheqd/src/ledger/CheqdLedgerService.ts
packages/cheqd/tests/cheqd-data-integrity.e2e.test.ts
packages/cheqd/tests/cheqd-did-registrar.e2e.test.ts
packages/cheqd/tests/cheqd-did-resolver.e2e.test.ts
packages/cheqd/tests/cheqd-sdk-anoncreds-registry.e2e.test.ts
packages/cheqd/tests/setupCheqdModule.ts

Adds some error handling to make sure the agent initialization does not fail if a cheqd network is down. As this prevents wallets and servers from starting.
Also updates test to not rely on cheqd testnet, but rather a local network so we're not dependant on external services

fix(cheqd): do not crash agent if cheqd down

---

packages/core/src/modules/discover-features/DiscoverFeaturesApi.ts
packages/core/src/modules/message-pickup/MessagePickupApi.ts

Under React Native, when testing Message Pickup V2 live mode for long periods I found out some warnings stating that there were too many subscribers for agent event emitter. 
After inspecting a bit the code of `MessagePickupApi` I saw we forgot to add a `first()` operator so it only waits for the first `MessagePickupCompleted` event and then unsubscribes automatically. Same thing happened to `DiscoverFeaturesApi` so here I added the same thing.

fix: unsubscribe from emitter after pickup completion

---

.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml
Dockerfile
packages/cheqd/package.json
yarn.lock

This updates the cheqd SDK to a new release that is compatible with node version 2 (used by cheqd testnet and soon mainnet).
~~Still need to figure out the React Native changes so draft for now~~
For react native I will update the docs, but we can already merge this PR.
Also pinned the Node.JS version as it's suddenly broken on newer minor versions due to ffi-napi ( https://github.com/nodejs/node/issues/52240)

fix: update cheqd to 2.4.2

---

packages/core/src/agent/Agent.ts
packages/core/src/agent/Dispatcher.ts
packages/core/src/agent/Events.ts
packages/core/src/agent/MessageReceiver.ts
packages/core/src/agent/models/InboundMessageContext.ts
packages/core/src/modules/message-pickup/protocol/v2/V2MessagePickupProtocol.ts
packages/core/src/modules/message-pickup/storage/QueuedMessage.ts

Add reception time in both `AgentReceivedEvent` and `AgentProcessedEvent`. This is mainly useful for agents behind a mediator, since they don't know for sure what is the actual creation time of a given DIDComm message (unless the protocol forces to specify it, like Basic Messages).
While this is not 100% accurate (as the sender can be offline at the time of creating it and therefore the reception time by receiver's mediator will not equal to this), it will work fine for most cases and does not break any protocol.
The only addition at protocol level is to optionally specify `lastModTime` when attaching queued messages in Message Pickup protocol. This recommendation was discussed today at DIDComm UG and likely added to V2 and V3 Message Pickup protocols.

feat: queued messages reception time

---

packages/openid4vc/src/openid4vc-issuer/router/accessTokenEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/credentialEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/verifyAccessToken.ts

Ensures that the access token can only be used for the issuance session it was created for, and not for other issuance sessions. This is recommend according to OID4VCI spec.

fix: access token can only be used for offer

---

.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml
Dockerfile
demo-openid/package.json
demo/package.json
package.json
packages/anoncreds/package.json
packages/askar/package.json
packages/indy-sdk-to-askar-migration/package.json
packages/indy-vdr/package.json
packages/node/package.json
samples/extension-module/package.json
yarn.lock

Trying to re-gain compatibliity with latest node versions (18.20, 20.12, 21.6) by using a patched version of `@2060.io/ffi-napi`. The issue was caused by an experimental feature in N-API (see [this commit](https://github.com/nodejs/node/commit/7a216d5fd6331c98c117ef471d0c971c8d97f757)), which was enabled when compiling ffi-napi because it had `NAPI_EXPERIMENTAL` flag set (originally this was needed until the release of [node 12.17](https://github.com/node-ffi-napi/node-ffi-napi/blob/1e7bbb170462f5f0880350cc4a518a2755b9337f/src/ffi.cc#L2), but the flag wasn't removed since the repo was not being maintained after that).
Given that `@hyperledger/aries-askar-nodejs`, `@hyperledger/indy-vdr-nodejs` and `@hyperledger/anoncreds` had pinned previous version of ffi-napi, I think we'll need to do a …

fix: node-ffi-napi-compatibility

---

packages/tenants/src/TenantsApi.ts
packages/tenants/src/TenantsApiOptions.ts
packages/tenants/tests/tenants.test.ts

Has been boterhing me a lot, as it makes the function a lot more complex to use and thus I used `getTenantAgent`, but this way it's easer to use `withTenantAgent,` which always makes sure the session is closed

feat(tenants): return value from withTenatnAgent

---

packages/core/src/modules/dif-presentation-exchange/DifPresentationExchangeService.ts
packages/core/src/modules/dif-presentation-exchange/models/DifPexCredentialsForRequest.ts
packages/core/src/modules/dif-presentation-exchange/utils/credentialSelection.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts

This adds a new field `dislocedPayload` to the return value of credentials for PEX so you know which fields will be disclosed in an SD-JWT VC. 
It is a breaking change as the value is now not a credential record, but an object with a record. However as we mark experimental features (of which SD-JWT, PEX and OpenID4VC are marked as experimental) as not following semver, I think it's OK to do this. This way we can keep improving the API between 0.5 - 0.6 without having to make a ton of new breaking release. Of course we want to minimze them, but in this case it's worth the tradoff IMO.

feat: add disclosures so you know which fields are disclosed

---

packages/anoncreds/src/anoncreds-rs/AnonCredsRsHolderService.ts
packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts
packages/anoncreds/src/utils/indyIdentifiers.ts
packages/anoncreds/src/utils/w3cAnonCredsUtils.ts

I ran into issues issues while receiving legacy Indy credentials with revocation support, e.g. receiving the following error when using [BC Digital Trust Showcase](https://digital.gov.bc.ca/digital-trust/showcase/dashboard):
> CredoError: QEquAHkM35w4XVT3Ku5yat:4:QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card:CL_ACCUM:dd6cecd9-a71b-4af4-a8f6-26a3fee2e073 is not a valid did:indy did\n    at parseIndyDid at getUnQualifiedDidIndyDid at getW3cRecordAnonCredsTags
I found that record metadata was populated with `revocationRegistryId` from the W3C credential object, which in this case would be an unqualified identifier. As `getUnQualifiedDidIndyDid` expected a qualified identifier, this fails. In addition, the utility method `getQualifiedDidIndyDid` was not taking into account …

fix(anoncreds): unqualified revocation registry processing

---

packages/anoncreds/src/updates/0.4-0.5/__tests__/w3cCredentialRecordMigration.test.ts
packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts

As discussed in today's meeting, in order to properly bind existing Credential Exchange Records to the credentials stored as a result of them.

fix(anoncreds): credential exchange record migration

---

packages/anoncreds/src/updates/0.4-0.5/__tests__/w3cCredentialRecordMigration.test.ts
packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts

Unfortunately we were looking for the wrong id when migrating Credential Exchange records that were bound to legacy AnonCreds credentials, as they are referenced by their `credentialId` instead of framework's record `id`.

fix(anoncreds): migration script credential id

---

packages/core/src/modules/didcomm/services/DidCommDocumentService.ts
packages/core/src/modules/didcomm/util/matchingEd25519Key.ts
packages/core/src/modules/dids/domain/DidDocument.ts
packages/indy-vdr/src/dids/__tests__/IndyVdrIndyDidRegistrar.test.ts

Fixes a bug where if you would use a did document that contains keys not in authentication or keyAgreement, and also want to use it for DIDComm, it would break when the did document would be parsed for DIDComm. The restrictions are now loosened, as it was mostly used to find the matching Ed25519 key for a X25519 key.

fix: allow did document for didcomm without authentication or keyAgreement

---

packages/core/src/modules/connections/__tests__/InMemoryDidRegistry.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/connections/services/DidRotateService.ts
packages/core/src/modules/dids/DidsApi.ts
packages/core/src/modules/dids/__tests__/peer-did.test.ts
packages/core/src/modules/dids/repository/DidRecord.ts
packages/core/src/storage/migration/__tests__/__snapshots__/0.1.test.ts.snap
packages/core/src/storage/migration/updates/0.1-0.2/__tests__/connection.test.ts
packages/core/src/storage/migration/updates/0.1-0.2/connection.ts
packages/indy-vdr/src/dids/IndyVdrIndyDidRegistrar.ts
packages/indy-vdr/src/dids/__tests__/IndyVdrIndyDidRegistrar.test.ts

When integrating the new `invitationDid` with a `did:cheqd` DID, I noticed that DIDComm wouldn't work because the recipientKeyFingerprints weren't added.
To make it easier, it is now calculated in the did record if the did document is provided, and I've also updated the `did:indy` registrar to store the did document. It's very expensive to resolve these documents, and this will allow us in a future update to shortcut did docs created by us to first look for the local record.
But for now, it makes it easy to use any kind of did with DIDComm.

fix: store recipient keys by default

---

.github/workflows/continuous-integration.yml
packages/anoncreds/src/anoncreds-rs/__tests__/AnonCredsRsHolderService.test.ts
packages/anoncreds/src/anoncreds-rs/__tests__/AnonCredsRsServices.test.ts
packages/anoncreds/src/formats/__tests__/legacy-indy-format-services.test.ts
packages/anoncreds/src/updates/0.4-0.5/__tests__/w3cCredentialRecordMigration.test.ts
packages/anoncreds/tests/anoncreds-flow.test.ts
packages/anoncreds/tests/data-integrity-flow-anoncreds.test.ts
packages/anoncreds/tests/data-integrity-flow-w3c.test.ts
packages/anoncreds/tests/data-integrity-flow.test.ts
packages/anoncreds/tests/indy-flow.test.ts
packages/cheqd/src/dids/CheqdDidResolver.ts
packages/cheqd/tests/cheqd-did-registrar.e2e.test.ts
packages/cheqd/tests/cheqd-did-resolver.e2e.test.ts
packages/core/src/modules/dids/__tests__/peer-did.test.ts
packages/core/src/modules/dids/domain/DidResolver.ts
packages/core/src/modules/dids/methods/jwk/JwkDidResolver.ts
packages/core/src/modules/dids/methods/key/KeyDidResolver.ts
packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
packages/core/src/modules/dids/methods/web/WebDidResolver.ts
packages/core/src/modules/dids/services/DidRegistrarService.ts
packages/core/src/modules/dids/services/DidResolverService.ts
packages/core/src/modules/dids/services/__tests__/DidRegistrarService.test.ts
packages/core/src/modules/dids/services/__tests__/DidResolverService.test.ts
packages/core/src/modules/dids/types.ts
packages/core/src/modules/dif-presentation-exchange/utils/credentialSelection.ts
packages/core/src/modules/vc/jwt-vc/__tests__/W3cJwtCredentialService.test.ts
packages/core/tests/oob.test.ts
packages/indy-vdr/src/dids/IndyVdrIndyDidResolver.ts
packages/indy-vdr/tests/indy-vdr-indy-did-resolver.e2e.test.ts

It's a bit weird that for DIDs we created we have to resolve them from the ledger quite often. We already introduced using a cache, which mainly resolved the issue where we would resolve a did multiple times in a session. 
This will help with keeping things fast and local when working with did documents locally (e.g. signing credentials, etc..). We also noticed that some blockchains need some time to process did documents, and that it prevents you from already using the key in a did document. So using the local did record can speed things up quite a lot.
We will have to make improvements still to e.g. the cheqd anoncreds resolver as that bypasses this layer (which is good as it needs metadata from the resolver). But there may be some additional optimizations we can do to keep signing …

feat: allow serving dids from did record

---

packages/anoncreds/src/repository/AnonCredsCredentialDefinitionPrivateRecord.ts
packages/anoncreds/src/repository/AnonCredsCredentialDefinitionRecord.ts
packages/anoncreds/src/repository/AnonCredsKeyCorrectnessProofRecord.ts
packages/anoncreds/src/repository/AnonCredsRevocationRegistryDefinitionRecord.ts
packages/anoncreds/src/repository/AnonCredsSchemaRecord.ts

In testing some migrations internally we noticed that anoncreds records did not have createdAt properties (even though the types do have it).
This fixes it for new records, but we probably need to do a migration for 0.6 -- setting it to updateAt (very low chance it will be set as most anoncreds records are static), and otherwise to the current time.

fix: set created at for anoncreds records

---

packages/core/src/modules/oob/OutOfBandApi.ts

If only messages were attached and an existing connection, but reuseConnection was false, it would still use the existing connection.

fix(oob): only reuse connection if enabled

---

packages/core/src/modules/sd-jwt-vc/SdJwtVcOptions.ts
packages/core/src/modules/sd-jwt-vc/SdJwtVcService.ts
packages/core/src/modules/sd-jwt-vc/__tests__/SdJwtVcService.test.ts
packages/core/src/modules/sd-jwt-vc/__tests__/sdjwtvc.fixtures.ts

Allow to issue SD-JWT VCs without being bound to a holder (no `cnf` claim). It's optional in the SPEC. still required for OpenID4VC at the moment (I'm not sure if we need to support unbound credentials there?)

feat: sd-jwt issuance without holder binding

---

packages/openid4vc/package.json
yarn.lock

Updates to new OID4VCI, which uses the new ssi-types from sphereon, which uses the new sd-jwt version 😄 
So mostly for consistency of version libraries used

chore: update oid4vci deps

---

packages/indy-vdr/src/anoncreds/IndyVdrAnonCredsRegistry.ts
packages/indy-vdr/tests/indy-vdr-anoncreds-registry.e2e.test.ts

- Fixed the issue that wrong schema id is stored for credentials
- Written a test case to register and resolve a credential definition (internal,credDefDid != schemaDid)

fix: wrong schema id is stored for credentials

---

network/indy-pool.dockerfile

Recently, CI started failing in E2E tests due to some missing dependencies. Here we are updating indy-pool image to the latest one by BC Gov, that is more up to date and seems to work great for our purposes.

ci: update indy-pool image

---

packages/anoncreds/src/protocols/credentials/v1/V1CredentialProtocol.ts
packages/anoncreds/src/protocols/credentials/v1/__tests__/V1CredentialProtocolCred.test.ts
packages/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts
packages/anoncreds/src/protocols/proofs/v1/__tests__/V1ProofProtocol.test.ts
packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
packages/core/src/modules/connections/services/ConnectionService.ts
packages/core/src/modules/credentials/protocol/BaseCredentialProtocol.ts
packages/core/src/modules/credentials/protocol/v2/V2CredentialProtocol.ts
packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialProtocolCred.test.ts
packages/core/src/modules/proofs/protocol/BaseProofProtocol.ts
packages/core/src/modules/proofs/protocol/v2/V2ProofProtocol.ts
packages/core/src/modules/proofs/protocol/v2/__tests__/V2ProofProtocol.test.ts

fix: process problem report message

---

packages/anoncreds/src/models/exchange.ts
packages/anoncreds/src/updates/0.4-0.5/__tests__/w3cCredentialRecordMigration.test.ts
packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts

Sadly, the fix done in 0.5.3 for Indy credentials migration was not enough for some Indy revocable credentials, since it is failing to apply qualified/unqualified revocation registry identifier tags into Credential Exchange record and, therefore, not effectively updating its bindings to the W3C credential.
This happens, for instance, when migrating from 0.4.2 to 0.5.3 the credentials received in [BCGov Showcase](https://digital.gov.bc.ca/digital-trust/showcase/) and attempting to delete the credentials associated to a credential exchange. 
Fixes #1882
cc @wadeking98 @bryce-mcmath

fix: unqualified indy revRegDefId in migration

---

packages/core/src/agent/Dispatcher.ts
packages/core/src/agent/MessageHandlerMiddleware.ts
packages/core/src/agent/MessageReceiver.ts
packages/core/src/agent/__tests__/Dispatcher.test.ts
packages/core/src/agent/models/InboundMessageContext.ts
packages/core/src/modules/connections/ConnectionsApi.ts
packages/core/src/plugins/DependencyManager.ts
packages/core/tests/middleware.test.ts

This PR adds two things:
- middleware for the message handler
- fallback message handler for when no message handler is registered for the incoming message type
You could quite easily solve 2 (fallback message handler) with 1 (middleware), but it's meant to be a convenience method so you can easily handle incoming messages without a handler (i suspect for a lot of use case it should suffice). But the middleware gives that extra power to e.g. modify the incoming message. 
It would be nice to also start adopting the middleware in more places, e.g. the message sender (to modify messages before they are sent).
Our use case for adding this at the moment is that we want to handle messages that have no message class supported. I haven't added any top-level APIs yet (only on the dependency …

feat: add message handler middleware and fallback

---

packages/core/src/agent/MessageHandlerRegistry.ts
packages/core/src/agent/__tests__/Dispatcher.test.ts
packages/core/src/plugins/DependencyManager.ts
packages/tenants/tests/tenants.test.ts

The fallback message handler and the middleware were lost in the tenant agent. I moved the middleware and the fallback handler to the `MessageHandlerRegistry` so it will be available in the child container.

fix: Moved the middleware to the MessageHandlerRegistry

---

.github/workflows/release.yml

Last one -- need to make sure we're always publishing an unstalbe release, even if there's no changes (so we create a snapshot 'change').

ci: fix unstable release

---

.changeset/silly-cooks-compete.md
package.json
packages/action-menu/package.json
packages/action-menu/tsconfig.build.json
packages/anoncreds/package.json
packages/anoncreds/tsconfig.build.json
packages/askar/package.json
packages/askar/tsconfig.build.json
packages/bbs-signatures/package.json
packages/bbs-signatures/tsconfig.build.json
packages/cheqd/package.json
packages/core/package.json
packages/core/tsconfig.build.json
packages/drpc/package.json
packages/drpc/tsconfig.build.json
packages/indy-sdk-to-askar-migration/package.json
packages/indy-sdk-to-askar-migration/tsconfig.build.json
packages/indy-vdr/package.json
packages/indy-vdr/tsconfig.build.json
packages/node/package.json
packages/node/tsconfig.build.json
packages/openid4vc/package.json
packages/openid4vc/tsconfig.build.json
packages/question-answer/package.json
packages/question-answer/tsconfig.build.json
packages/react-native/package.json
packages/react-native/tsconfig.build.json
packages/tenants/package.json
packages/tenants/tsconfig.build.json
pnpm-lock.yaml

Fixes the build issue introduced in 0.5.5. We'll have to do a 0.5.6 release sadly.
It does add a few nice improvements though:
- now also includes src in package.json
- source maps point to source files, so whenever you now click on a type / method in e.g. vscode from credo you will be shown the source TS code rather than the build js code. Making debugging a lot easier I'd say :)

build: fix build issue in 0.5.5

---

.changeset/big-baboons-poke.md
packages/core/src/index.ts

this should fix the issue that was raised in the Discord.
I think it would be interesting to look at supporting ESM soon, as more and more bundlers / tools are supporting it and it can help us with a bit more 'stable' builds as we have to do less transforming, and thus TS will mostly strip types, rather than transform the imports to requires.

fix: export ParsedMessageType

---

.changeset/rude-kangaroos-tease.md
packages/openid4vc/src/shared/router/express.native.ts

Custom express.native.ts file will prevent React Native from bundling the `express` dependency. If at runtime express is imported it will throw an error, this will only be the case if you try to use the issuer or verifier modules in React Native (which are not supported in RN)
Fixes #1943

fix: express import in react native

---

.changeset/pretty-spies-argue.md
packages/core/src/modules/dids/methods/jwk/JwkDidRegistrar.ts
packages/core/src/modules/dids/methods/jwk/__tests__/JwkDidRegistrar.test.ts
packages/core/src/modules/dids/methods/key/KeyDidRegistrar.ts
packages/core/src/modules/dids/methods/key/__tests__/KeyDidRegistrar.test.ts
packages/core/src/modules/dids/methods/peer/PeerDidRegistrar.ts
packages/core/src/modules/dids/methods/peer/__tests__/PeerDidRegistrar.test.ts

fix(dids): allow to pass in a key instance when creating a did document

---

.changeset/pink-icons-hope.md
packages/core/src/modules/oob/OutOfBandApi.ts

This is related to https://github.com/bcgov/vc-authn-oidc/issues/583, where apparently ACA-Py is returning a present but empty handshake_protocols array in connection-less use case. I cannot think of a valid use case for an empty array so I think it is correct to consider it as undefined if it comes like that.

fix: check handshake protocols array is not empty

---

packages/openid4vc/package.json
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerServiceOptions.ts
packages/openid4vc/src/openid4vc-issuer/router/metadataEndpoint.ts
packages/openid4vc/src/shared/issuerMetadataUtils.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts
packages/openid4vc/tests/utilsVci.ts
pnpm-lock.yaml

Small update to the new v13 logic, so that we can also pass `credentialConfigurationsSupported` to the `createIssuer` method in addition to `updateIssuerMetadata`

fix: add v13 param to createIssuer

---

packages/askar/package.json
packages/askar/src/secureEnvironment/index.ts
packages/askar/src/secureEnvironment/secureEnvironment.native.ts
packages/askar/src/secureEnvironment/secureEnvironment.ts
packages/askar/src/wallet/AskarBaseWallet.ts
packages/askar/src/wallet/__tests__/AskarWallet.test.ts
packages/core/src/crypto/Key.ts
packages/core/src/wallet/Wallet.ts
pnpm-lock.yaml

feat(askar): improved hardware key support

---

packages/askar/src/wallet/AskarBaseWallet.ts
packages/core/src/crypto/Key.ts

- Had to remove the `keyId` property on the `Key` class as it was not ready yet. It caused some issues as some places we just infer the key id as the `publicKeyBase58` and because of that, some keys with a custom would not work.
- It is not required for the hardware key as the key id for the record is the `publicKeyBase58`, but for the underlying hardware key in the secure element it will just be a UUID.
When we do a bigger crypto move I would like to bring the custom key id back.

fix: remove key id

---

.changeset/heavy-gorillas-draw.md
packages/openid4vc/src/openid4vc-holder/OpenId4VcHolderApi.ts
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderServiceOptions.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts
packages/openid4vc/src/openid4vc-issuer/__tests__/openid4vc-issuer.test.ts
packages/openid4vc/src/shared/__tests__/issuerMetadataUtils.test.ts
packages/openid4vc/src/shared/issuerMetadataUtils.ts
packages/openid4vc/src/shared/models/index.ts

There were some issues in the transformation logic between v11 and v13 metadata. I fixedthe issue and also updated the code to use v13 by default as the v13 format is richer and thus we make sure we won't lose any metadata when transforming from v11 -> 13

fix(openid4vc): v11 metadata type and transformation

---

.changeset/sharp-crews-sniff.md
packages/core/src/modules/x509/X509ModuleConfig.ts
packages/openid4vc/package.json
packages/openid4vc/src/openid4vc-holder/OpenId4VcHolderApi.ts
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderServiceOptions.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerApi.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerServiceOptions.ts
packages/openid4vc/src/openid4vc-issuer/repository/OpenId4VcIssuerRecord.ts
packages/openid4vc/src/openid4vc-issuer/router/accessTokenEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/credentialEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/metadataEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/verifyResourceRequest.ts
packages/openid4vc/src/openid4vc-verifier/__tests__/openid4vc-verifier.test.ts
packages/openid4vc/src/shared/utils.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts
pnpm-lock.yaml

blocked by for now https://github.com/Sphereon-Opensource/OID4VC/pull/131

feat: dpop support

---

packages/openid4vc/src/openid4vc-holder/OpenId4vcSiopHolderService.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts
packages/openid4vc/tests/utils.ts

depends on https://github.com/openwallet-foundation/credo-ts/pull/1966
and https://github.com/Sphereon-Opensource/OID4VC/pull/137

test: openid4vp x509

---

packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts
packages/openid4vc/src/shared/models/index.ts

This fixes the issue reported in ([#1963](https://github.com/openwallet-foundation/credo-ts/issues/1963)).
* Added logic to set credentialRequest.types based on credentialRequest.credential_definition.type if credential_definition is defined.
* This ensures that the types attribute is correctly populated from credential_definition when available, preventing potential issues with undefined credential_definition.type.
* The change is applied at line 41 in packages/openid4vc/src/shared/models/index.ts.

fix: resolve undefined credential_definition.type in credentialRequest

---

packages/core/src/modules/dif-presentation-exchange/utils/credentialSelection.ts

Fixes #1993 
The PR adjusts `getSubmissionRequirementRulePick` to assign all `satisfiedSubmissions` to `submissionEntry`, rather than `submission`.
This is a bug fix, but if anyone relies on the `submission` property, this could be seen as a breaking change.

fix: 1993 assign satisfiedSubmissions to submissionEntry in `getSubmissionRequirementRulePick`

---

packages/anoncreds/src/formats/AnonCredsCredentialFormatService.ts

When the index is 0 it also fails which should not happen.

fix: Changed condition to check if the revocationRegistryIndex is undefined instead of falsy

---

packages/core/src/modules/credentials/protocol/v2/V2CredentialProtocol.ts

- Fixes #2022 
- Initially during processing proposal in cases where an OOB credential is being offered.
- If holder, accepts OOB invitation and negotiates the offer, the connection details are appended on the holders side.
- But for issuer we are unable to update the credential record with the connection details.
- Hence, the issuer considers this credential proposal as a new flow and creates a new credential record with connection details. This causes the flow to break further in the processing when two records against a single threadId are found

fix: duplicate offer being created on issuers side while negotiating offer as a holder

---

packages/core/src/modules/x509/__tests__/X509Service.test.ts

chore(x509): added test to create self-signed certificate with Curve Ed25519

---

packages/indy-vdr/src/dids/__tests__/IndyVdrIndyDidResolver.test.ts
packages/indy-vdr/src/dids/didIndyUtil.ts
packages/indy-vdr/src/dids/didSovUtil.ts

This PR fixes a TODO item left in the Indy DID Resolution code. nym.diddocContent is in fact a string and not a json object when retrieved from the ledger.

fix: handling of diddoc content as string

---

packages/cheqd/package.json
pnpm-lock.yaml

- This dependency bump fixes an JSONLD Schema validation error with DID Document resolution by including the [linkedDomain context](https://identity.foundation/.well-known/did-configuration/v1/) when a serviceEndpoint type is set to `LinkedDomains`.

build(deps): bump cheqd sdk from 2.4.4 to 2.5.1

---

.changeset/spotty-hounds-relax.md
packages/askar/src/utils/askarKeyTypes.ts
packages/askar/src/wallet/AskarBaseWallet.ts
packages/askar/src/wallet/__tests__/AskarWallet.test.ts
packages/core/src/wallet/Wallet.ts

it's very specific to what we need for OID4VC now. At some point we should make one generic encryption/decryption api in the wallet api, and then build a JWE layer on top of it.
the method is optional for now but implemented in askar wallet so it's not really a breaking change

feat: add direct ecdh-es jwe encryption/decryption

---

packages/core/src/modules/vc/W3cCredentialsModule.ts
packages/core/src/modules/vc/__tests__/W3CredentialsModule.test.ts
packages/core/src/modules/vc/data-integrity/signature-suites/ed25519/Ed25519Signature2020.ts
packages/core/src/modules/vc/data-integrity/signature-suites/ed25519/context2020.ts
packages/core/src/modules/vc/data-integrity/signature-suites/index.ts

This is a somewhat naive implementation of adding Ed25519Signature2020 support to the W3cCredentialsModule. Feedback is most welcome and any direction you'd be willing to offer on what other things are required to get this to a merge-able state would be appreciated.

feat: add Ed25519Signature2020 support

---

packages/core/package.json
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
pnpm-lock.yaml

Two fixes for mdoc:
- update mdoc client to fix react native issues
- proper handling of cose_key (gave issues with BDR pid issuer)

fix: mdoc fixes

---

packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierService.ts

Fixes #2075 by removing the obsolete if block, and using the errors thrown by the various verifier functions to establish a `reason` when a presentation isn't valid.

fix: Remove unnecessary conditional

---

packages/core/src/modules/credentials/CredentialsApi.ts

- Added missing parameter in `findAllByQuery` method in credential api

fix: add missing parameter in findAllByQuery method in credential api

---

packages/anoncreds/src/formats/AnonCredsCredentialFormatService.ts

issue-credential-v2 anoncreds didcomm attachments are sending with `anoncreds/credential@v1.0` format type rather than `anoncreds/credential-offer@v1.0`
spec:
https://github.com/hyperledger/aries-rfcs/blob/main/features/0771-anoncreds-attachments/README.md#credential-offer-format

fix: Anoncreds Offer Attachment Type

---

packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts

fix: Revocation Index 0 anoncreds-rs support

---

.changeset/hip-planes-hunt.md
.eslintrc.js
packages/core/package.json
packages/core/src/transport/HttpOutboundTransport.ts
packages/core/src/utils/fetch.ts
packages/core/src/utils/parseInvitation.ts
pnpm-lock.yaml

It has been supported for a long time now in all platforms and it's currently causing issues in our wallets. Using the native abort controller

chore: remove abort controller

---

packages/indy-vdr/src/pool/IndyVdrPool.ts

Fixes: Unable to reinitialize agent once shut down #2135

chore: fixes restart without indy pool disconnect

---

.changeset/popular-walls-add.md
tsconfig.build.json

Generally this should not have an impact for the supported environments (Node.JS / React Native). However this will have to be tested in React Native

build: update target for tsc compiler to ES2020

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.arm.yml
.devcontainer/docker-compose.yml

This is just an addition for devs that want to run the full test suite and need the docker compose setup, but have issues building locally (such as myself lol 🥲)

chore: update devcontainer to use proper docker compose

---

packages/core/tsconfig.build.json

In Core we are including test types in the source code, and since now we have dependency on DIDComm module it was messing up the core package build process (it creates 2 directories, one with core and another with didcomm).
Thanks @sairanjit for noticing and showing the solution for this!

fix: exclude test types from core

---

.changeset/eleven-deers-rush.md
packages/core/src/modules/mdoc/MdocContext.ts
packages/core/src/modules/x509/X509Certificate.ts

I've noticed i often need some elements but not the thumbprint and the method requiring crypto and being async was a bit annoying.

refactor: split async `getData` method on x509 certificate

---

.changeset/brave-cars-deny.md
.github/workflows/continuous-integration.yml
packages/core/package.json
packages/core/src/modules/mdoc/MdocDeviceResponse.ts
packages/core/src/modules/mdoc/__tests__/mdocProximityDeviceResponse.test.ts
pnpm-lock.yaml

- Update mdoc dep to 0.4.0
- create device response returns bytes and not base64 encoded

chore(mdoc): update dependency

---

.changeset/famous-meals-rhyme.md
packages/core/src/modules/x509/__tests__/X509Service.test.ts
packages/core/src/modules/x509/utils/extensions.ts

Use SHA-1 hash of the key to generate the AuthorityKeyIdentifier and the SubjectKeyIdentifier

fix(x509): use the SHA-1 hash of the public key for the SubjectKeyIdentifier and the AuthorityKeyIdentifier

---

packages/core/src/modules/mdoc/MdocDeviceResponse.ts
packages/core/src/modules/mdoc/__tests__/mdocServer.test.ts

Dit not check the verification result of individual mdocs in last PRs refactor. Now also added a test to cover this

fix(mdoc): use verification result

---

packages/anoncreds/src/anoncreds-rs/AnonCredsRsHolderService.ts
packages/anoncreds/src/formats/AnonCredsProofFormatService.ts
packages/anoncreds/src/formats/__tests__/anoncreds-format-services.test.ts

This is for a problem we were seeing with the bc wallet when trying to use the anoncreds proof format with unqualified did sov's. I believe this should be supported by credo due to all the utility functions for the conversion.

fix: additional unqualified did:sov support with anoncreds

---

packages/core/src/modules/vc/models/credential/W3cCredential.ts

This PR adds the missing `credentialSchema` attribute in `w3cCredential` class constructor.

fix: add missing credentialSchema attribute in w3cCredential class

---

.changeset/ninety-tables-crash.md
packages/core/src/modules/sd-jwt-vc/SdJwtVcOptions.ts
packages/core/src/modules/sd-jwt-vc/SdJwtVcService.ts
packages/core/src/modules/sd-jwt-vc/__tests__/SdJwtVcService.test.ts
packages/core/src/modules/sd-jwt-vc/__tests__/sdJwtVc.test.ts
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts
packages/openid4vc/tests/openid4vc-draft21.e2e.test.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts

and verify that SD-JWT VCs have either dc+sd-jwt or vc+sd-jwt as typ header. You can still use vc+sd-jwt as typ header by providing the headerType value when signing an SD-JWT VC. For OID4VCI the typ header is based on the oid4vci credential format used.

feat: use dc+sd-jwt as SD-JWT VC typ header by default 

---

packages/cheqd/src/ledger/CheqdLedgerService.ts

Feemarket initialized is required is the newer cheqd sdk versions. This was done in main, unfortunately missed it in the backport

fix(cheqd): Initialize feemarket module

---

.changeset/fluffy-countries-hide.md
packages/core/src/logger/replaceError.ts

on an error, due to the error serialization not working great in all environments
Fixes #2274

docs(changeset): changed the console logger to call `toString()`

---

.changeset/violet-meals-worry.md
packages/indy-vdr/src/anoncreds/utils/transform.ts

We discovered this bug when we ran into an issue where if you created a credential with revocation registry size 4, issued 4 credentials, then revoked the last one, all proof requests with that credential would fail. Off by one errors strike again 😁

fix: correct revocation registry check edge case

---

.changeset/sharp-beans-brush.md
packages/indy-vdr/src/anoncreds/utils/transform.ts

fix: off by one error in indy vdr revocation check

---

packages/core/src/constants.ts

I think after #2203 Wallet injection symbol is not used anymore. So I guess we can drop it?

fix: remove Wallet injection symbol

---

.changeset/empty-days-tickle.md
packages/core/src/modules/vc/data-integrity/libraries/nativeDocumentLoader.ts
packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierService.ts

currently if `await relyingParty.createAuthorizationRequest` or `await relyingParty.verifyAuthorizationResponse` take longer than 10 seconds (the rxjs timeout), then the timeout throws an unhandled promise rejection that can bubble up in nasty ways.
This fix catches the error and wraps the promise as a result where the error is rethrown in the correct context

fix: unhandled rejection in the oid4vp verifier service

---

.changeset/kind-pots-yell.md
packages/cheqd/src/anoncreds/utils/identifiers.ts
packages/cheqd/src/dids/CheqdDidRegistrar.ts
packages/cheqd/tests/cheqd-did-registrar.e2e.test.ts
packages/cheqd/tests/cheqd-did-resolver.e2e.test.ts
packages/cheqd/tests/cheqd-ld-proof.e2e.test.ts

we are facing an issue in JSONLD issuance with credo, and issue is with the default document loader
```
DidDocument {
context: ['https://www.w3.org/ns/did/v1', 'https://w3id.org/did/v1', 'https://w3id.org/security/suites/jws-2020/v1', 'https://w3id.org/security/suites/ed25519-2018/v1'],
id: 'did:cheqd:testnet:151734ba-d9c8-4bf6-a83c-bc4098b10ac6',
controller: [],
verificationMethod: [ VerificationMethod {
id: 'did:cheqd:testnet:151734ba-d9c8-4bf6-a83c-bc4098b10ac6#z6MktzU5kM5XdEKmGrZwXfQEa3jZAyexhmP7iNDMotin4GcR',
type: 'Ed25519VerificationKey2018',
controller: 'did:cheqd:testnet:151734ba-d9c8-4bf6-a83c-bc4098b10ac6',
publicKeyBase58: 'FYD3A6q6HgqJAMjEr6SPixBZMQP7Ht8m2MJRyckm93q3'
}],
authentication: ['did:cheqd:testnet:151734ba-d9c8-4bf6-a83c-bc4098b10ac6#z6MktzU5kM5XdEKmGrZwXfQEa3jZAyexh …
```

fix(cheqd): Populate contexts for JsonLD issuance

---

.changeset/chilly-bears-jump.md
packages/core/src/index.ts
packages/core/src/utils/deepEquality.ts
packages/openid4vc/package.json
packages/openid4vc/src/openid4vc-holder/OpenId4vpHolderService.ts
packages/openid4vc/src/openid4vc-holder/OpenId4vpHolderServiceOptions.ts
packages/openid4vc/tests/openid4vc.e2e.test.ts
pnpm-lock.yaml

feat: custom verification callback for the authorization request on the holder side for verification

---

.changeset/brown-files-return.md
packages/askar/tests/askar-didcomm-credo-05.test.ts
packages/didcomm/src/EnvelopeService.ts

The KMS PR introduced issues when testing with Credo 0.5 instances. I've fixed the issue and added some tests based on DIDComm messages created by Credo 0.5. I also tested DIDcomm messages created by Credo main branch with Credo 0.5 manually and this works as well.
Fixes #2311

fix: incorrect key alg for didcomm

---

demo-openid/package.json

In order to run the crede-ts demo properly it is required to fix the `npm run provider` script accordingly to the `Provider.js` in `src`.

fix: correct provider source file in npm run script

---

.changeset/clean-zoos-swim.md
packages/indy-vdr/src/anoncreds/utils/__tests__/transform.test.ts
packages/indy-vdr/src/anoncreds/utils/transform.ts

Backport of #2319 to v0.5.x
This PR cherry-picks the fix for `indyVdrCreateLatestRevocationDelta` to allow individual credential revocation/unrevocation.
See original PR #2319 for full context and discussion.

fix: correct indyVdrCreateLatestRevocationDelta to allow individual credential revocation/unrevocation

---

packages/core/src/modules/mdoc/__tests__/mdocServer.test.ts

Trying to get rid of this error that is appearing in CI/CD since a long time now. It is related to some kind of breaking change in `@animo-id/mdoc` that is preventing it from properly handling `input.now` field in `verififyIssuerSignature`. I was about to create a PR in that library but such method doesn't exist anymore (more breaking changes, it seems...) so I thought the best would be to just workaround this test in credo-ts for now.
Basically what we do here is to mock current date to match one suitable for the issuer certificate used in the test (which needs the current date to be between Aug 12 2024 and Aug 26 2024). Not the ideal solution but probably better than just skipping the test.
EDIT: I failed at mocking current date, since it produces other tests to fail. So I decided to …

test: fix mdoc-server test

---

demo-openid/src/Verifier.ts

In the OpenID4VC demo, presentation with DCQL failed with the holder unable to handle the request.
Two corrections to the DCQL query in the demo are made:
* The `id` is changed to not use the forbidden character `+`
* The credential type query is changed to match the credential type issued in the demo

fix: incorrect DCQL query in OpenID4VC demo

---

.changeset/cyan-tomatoes-end.md
packages/didcomm/src/modules/connections/__tests__/did-rotate.test.ts
packages/didcomm/src/modules/connections/services/DidRotateService.ts

Emit a `didRotated` event from `processHangup` method so it can be captured by a client

feat(didcomm): emit event on hangup

---

packages/webvh/package.json
pnpm-lock.yaml

hey @TimoGlastra @genaris I found a couple issues with the react-native build and this version resolves those issues along with #2366 for v0.5.x

chore: update didwebvh-ts to version 2.5.2 in package.json

---

.changeset/beige-deer-cross.md
packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerServiceOptions.ts

Fixes the return type of the credential mappers.
cc @TimoGlastra

fix(openid4vc): return type of credential mappers

---

packages/node/src/transport/HttpInboundTransport.ts

This is the same fix for the memory leak recently found but targeting 0.5.x. (please ignore the branch version)
Auto unsubscribes the listener for the encrypted message filter after first match.

fix: AgentMessageProcessed event listener leak

---

packages/webvh/src/anoncreds/services/WebVhAnonCredsRegistry.ts
packages/webvh/src/anoncreds/utils/transform.ts

for 0.5.x
- Implemented logic to retrieve and validate revocation entries based on timestamp.
- Introduced WebVhRevocationStatusListContent class for structured revocation status data.
- Improved error handling for missing revocation entries and logging for resolution attempts.

feat(webvh): enhance revocation status list handling in WebVhAnonCredsRegistry

---

.changeset/little-windows-check.md
packages/core/src/logger/replaceError.ts

We keep seeing issues in React Native with error serialization, making it hard to debug without adding a lot of console.logs in node_modules. I have verified this in our wallet, and it improves the error serialization, for errors that don't implement `toString`.

chore: update the `replaceError` to better handle react native serialization

---

packages/core/src/modules/message-pickup/MessagePickupApi.ts
packages/core/src/modules/message-pickup/__tests__/MessagePickupApi.test.ts
packages/core/src/modules/message-pickup/__tests__/MessagePickupSessionService.test.ts
packages/core/src/modules/message-pickup/services/MessagePickupSessionService.ts

This is to fix a couple problems we've been having with live mode and both http and ws sessions. I don't know much about the outbound context session id but I changed the preference to choose the session by connection id first, and then use the websocket session if it is in the session table.
Then for the removing of the pickup session when in live mode delivery, I changed this to only happen when websocket sessions close. All other delivery modes close pickup sessions on every session closed event.
TODO: Automated testing

fix: Set pickup delivery to prefer websocket transport

---

.changeset/all-mails-guess.md
packages/core/src/modules/dif-presentation-exchange/DifPresentationExchangeService.ts
packages/core/src/modules/vc/W3cCredentialServiceOptions.ts
packages/core/src/modules/vc/data-integrity/W3cJsonLdCredentialService.ts
packages/core/src/modules/vc/data-integrity/libraries/jsonld-signatures.ts

Backporting #2390 for 0.5.x releases. 
Note that `challenge` field is now marked as optional in `W3cSignPresentationOptionsBase`. Could this interface change represent a breaking change? If so, I can change it to be mandatory even if not used (in such case, caller should just use an empty string).

fix(vc): allow selecting proof purpose for VPs (backport #2390)

---

.changeset/shaky-emus-invite.md
packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
packages/openid4vc/src/openid4vc-issuer/router/accessTokenEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/credentialEndpoint.ts
packages/openid4vc/src/openid4vc-issuer/router/deferredCredentialEndpoint.ts

From my tests, this seems to be necessary in some flows where neither a client id or wallet attestation has been used.

fix(openid4vc): fallback to anon auth with refresh tokens
