openwallet-foundation/credo-ts

run.sh
You may use alice or agency01, bob or agency 02,
when starting test networks.
=> Make options match error

CODEOWNERS, README.md
I wanted to surface the CI state, as well as add a code owners.
=> Additional repo improvements

.ci/azure-pipelines.yml
If you want to see the results, [look here](https://dev.azure.com/Hyperledger/Aries/_build/results?buildId=4246&view=results)
=> Add networking tests

src/lib/agent/MessageSender.ts
Other agents may have it set as null or not a part of the
message
=> MessageSender: Check if routingKey is set

src/lib/handlers/InvitationHandler.ts
=> InvitationHandler: Wait for route to be created with agency

package.json, src/lib/logger.ts
Prevents polluting downstream logs
=> Logger: Use debug module

src/lib/protocols/basicmessage/BasicMessageService.ts
Also removes the ack message in response since spec
doesn't list it
=> BasicMessage: Emit an event on basic message

package.json, src/lib/__tests__/agents.test.ts, src/lib/agent/Agent.ts, src/lib/decorators.test.ts, src/lib/decorators.ts, src/lib/wallet/IndyWallet.ts, src/lib/wallet/Wallet.test.js, src/samples/__tests__/e2e.test.ts, src/samples/agency.ts, types/indy-sdk/index.d.ts
This would allow users to use rn-indy-sdk/ARNIMA in downstream projects
=> Allow using an interface that implements indy-sdk

CONTRIBUTING.md, SECURITY.md, package.json
- Update license in package.json to Apache-2
- Add CONTRIBUTING.md & SECURITY.md
- Fixes #29 & #31
=> Correct licensing info, contribution guidelines

README.md
Signed-off-by: Timo Glastra <timo@glastra.me>
=> add note about indy-sdk to installation steps

.gitignore
Signed-off-by: Matt Raffel <mattr@kiva.org>
=> adding idea directory to gitignore file

src/samples/agency.ts
I forgot to remove this temporary endpoint when I was adding the pickup protocol #45
=> Remove unused messages endpoint from sample agency

src/lib/agent/Agent.ts, src/lib/agent/ProvisioningService.ts, src/lib/storage/BaseRecord.ts, src/lib/storage/ProvisioningRecord.ts
=> Add provisioning record persistence

README.md, TROUBLESHOOTING.md
Extracted the troubleshooting to a separate file and added the steps to resolve the issues both Karim and I faced while installing AFJ / libindy on macOS.
=> add extra troubleshooting help

.github/workflows/continuous-integration.yml, src/lib/utils/did.test.ts
I've found formatting error when pushing to my fork. I fix formatting and also add `lint` job to CI.
=> Fix formatting and add lint step to CI

src/lib/__tests__/agents.test.ts, src/lib/__tests__/credentials.test.ts, src/lib/__tests__/helpers.ts, src/lib/agent/Agent.ts, src/lib/agent/MessageReceiver.ts, src/lib/handlers/credentials/CredentialOfferHandler.ts, src/lib/modules/CredentialsModule.ts, src/lib/protocols/credentials/CredentialService.test.ts, src/lib/protocols/credentials/CredentialService.ts, src/lib/protocols/credentials/CredentialState.ts, src/lib/protocols/credentials/__tests__/CredentialService.test.ts, src/lib/protocols/credentials/__tests__/StubStorageService.ts, src/lib/protocols/credentials/__tests__/StubWallet.ts, src/lib/protocols/credentials/messages/CredentialOfferMessage.ts, src/lib/protocols/credentials/messages/MessageType.ts, src/lib/storage/BaseRecord.ts, src/lib/storage/CredentialRecord.ts, src/lib/storage/Repository.ts, src/lib/storage/StorageService.ts, src/lib/wallet/IndyWallet.ts, src/lib/wallet/Wallet.ts, types/indy-sdk/index.d.ts
This PR contains the first task "Credential offer exchange" from the #64
=> Send and accept credential offer

TROUBLESHOOTING.md
=> update troubleshooting with homebrew update

.github/workflows/continuous-integration.yml, README.md, docker/docker-compose-mediators-ngrok.yml, docker/docker-compose-mediators.yml, scripts/ngrok-wait.sh, scripts/run-mediator.sh, src/lib/agent/AgentConfig.ts, src/lib/agent/__tests__/AgentConfig.test.ts, src/lib/protocols/connections/ConnectionService.test.ts, src/lib/types.ts, src/samples/config.ts
The ngrok option is a convenient when using the framework in a mobile environment
Fixes #138 
Fixes #144
=> refactor docker scripts, add ngrok option

src/lib/agent/LedgerService.ts
=> Update indy error handling when connecting to the ledger

src/lib/protocols/connections/ConnectionInvitationMessage.ts, src/lib/protocols/connections/__tests__/ConnectionInvitationMessage.test.ts
=> make routing keys optional in connection invitation message

src/lib/agent/Agent.ts, src/lib/handlers/proof/RequestPresentationHandler.ts, src/lib/modules/CredentialsModule.ts, src/lib/modules/ProofsModule.ts, src/lib/protocols/credentials/CredentialService.ts, src/lib/protocols/credentials/__tests__/StubWallet.ts, src/lib/protocols/proof/ProofService.ts, src/lib/protocols/proof/ProofState.ts, src/lib/protocols/proof/messages/ProofRequestMessage.ts, src/lib/protocols/proof/messages/RequestPresentationMessage.ts, src/lib/protocols/proof/messages/messages.ts, src/lib/storage/BaseRecord.ts, src/lib/storage/ProofRecord.ts, src/lib/wallet/IndyWallet.ts, src/lib/wallet/Wallet.ts, types/indy-sdk/index.d.ts
Signed-off-by: Parth <Parthkm78@gmail.com>
=> proof request implementation

src/lib/modules/CredentialsModule.ts, src/lib/protocols/connections/ConnectionService.ts
Emit events for createInvitation and receiveInvitation and add events() method to CredentialsModule.
Related to #157
=> Event related fixes

src/lib/protocols/credentials/__tests__/StubWallet.ts, src/lib/wallet/IndyWallet.ts, src/lib/wallet/Wallet.ts
Update the wallet error handling to be a bit less repetitive
=> update wallet error handling

src/lib/modules/BasicMessagesModule.ts, src/lib/modules/ConnectionsModule.ts, src/lib/modules/CredentialsModule.ts
=> small rewording of event documentation

.github/workflows/continuous-integration.yml, CONTRIBUTING.md, README.md
This changes all references from master to main. I think this should be merged after the rename?
@ryjones we don't have permission to do the renaming, could you assist with this?
=> rename master to main

src/lib/__tests__/ledger.test.ts
Fixes #57 (after #184 is merged)
=> remove console logs from ledger tests

.github/workflows/continuous-integration.yml, src/lib/agent/__tests__/AgentConfig.test.ts, src/lib/protocols/connections/__tests__/ConnectionService.test.ts, src/lib/protocols/connections/__tests__/ConnectionState.test.ts, src/lib/protocols/connections/domain/ConnectionState.ts, src/lib/protocols/issue-credential/CredentialState.ts, src/lib/protocols/issue-credential/__tests__/CredentialService.test.ts, src/lib/protocols/issue-credential/__tests__/CredentialState.test.ts, src/lib/protocols/present-proof/ProofState.ts, src/lib/protocols/present-proof/__tests__/ProofState.test.ts
Fixes #176 
#170 already uses the rfc states so doesn't require any additional changes
=> update record states to match rfc

src/lib/modules/proofs/ProofsModule.ts
small fix to make presentation proposal optional
=> fix: make presentation proposal optional

src/lib/agent/Dispatcher.ts, src/lib/agent/Handler.ts, src/lib/modules/basic-messages/handlers/BasicMessageHandler.ts, src/lib/modules/connections/handlers/AckMessageHandler.ts, src/lib/modules/connections/handlers/ConnectionRequestHandler.ts, src/lib/modules/connections/handlers/ConnectionResponseHandler.ts, src/lib/modules/connections/handlers/TrustPingMessageHandler.ts, src/lib/modules/connections/handlers/TrustPingResponseMessageHandler.ts, src/lib/modules/credentials/handlers/CredentialAckHandler.ts, src/lib/modules/credentials/handlers/IssueCredentialHandler.ts, src/lib/modules/credentials/handlers/OfferCredentialHandler.ts, src/lib/modules/credentials/handlers/ProposeCredentialHandler.ts, src/lib/modules/credentials/handlers/RequestCredentialHandler.ts, src/lib/modules/proofs/handlers/PresentationAckHandler.ts, src/lib/modules/proofs/handlers/PresentationHandler.ts, src/lib/modules/proofs/handlers/ProposePresentationHandler.ts, src/lib/modules/proofs/handlers/RequestPresentationHandler.ts, src/lib/modules/routing/handlers/ForwardHandler.ts, src/lib/modules/routing/handlers/KeylistUpdateHandler.ts, src/lib/modules/routing/handlers/MessagePickupHandler.ts
=> refactor: Move handler interface to agent directory

src/lib/modules/common/index.ts, src/lib/modules/common/messages/AckMessage.ts, src/lib/modules/common/messages/CommonMessageType.ts, src/lib/modules/connections/__tests__/ConnectionService.test.ts, src/lib/modules/connections/handlers/AckMessageHandler.ts, src/lib/modules/connections/messages/ConnectionMessageType.ts, src/lib/modules/connections/messages/index.ts, src/lib/modules/connections/services/ConnectionService.ts, src/lib/modules/credentials/__tests__/CredentialService.test.ts, src/lib/modules/credentials/messages/CredentialAckMessage.ts, src/lib/modules/credentials/services/CredentialService.ts, src/lib/modules/proofs/messages/PresentationAckMessage.ts, src/lib/modules/proofs/services/ProofService.ts
Implementation of point 6 and closing #192.
=> refactor: Extract ack message from connections to common module

jest.config.js
I'm sorry, I forgot to add `samples` as test root the tests there has been ignored.
=> fix: Add samples folder as test root

.github/workflows/repolinter.yml
This adds a manual dispatch action to run repolinter. Doesn't seem necessary to run it on each PR.
=> add repolinter action

.github/workflows/continuous-integration.yml
=> ci: fix release action, remove duplication

samples/mediator-ws.ts
=> refactor: Re-use ws outbound transport in mediator

src/modules/routing/RecipientModule.ts, src/modules/routing/services/RecipientService.ts
Signed-off-by: David Clawson <david.clawson@gmail.com>
=> Created default mediator tag & wallet retrieval

.github/workflows/codeql-analysis.yml
Github recommended me to add a CodeQL analysis github action
=> ci: add codeql action

src/index.ts
=> chore: export wallet interface

src/index.ts
=> chore: export injection symbols

src/modules/connections/messages/ConnectionRequestMessage.ts
=> fix: Remove apostrophe from connection request message type

src/agent/Agent.ts, tests/mediator-ws.ts, tests/mediator.ts
@jakubkoci as per your comment in #322 here's how you can achieve it using dependency injection
I think we should use injection for the transports in general instead of manually passing the agent in. But for now I think this is a fine solution.
=> refactor: inject transport service in transports

docs/getting-started/1-transports.md, docs/setup-electron.md, docs/setup-nodejs.md, docs/setup-react-native.md
should be initialize of course
=> docs: fix incorrect init method

README.md, src/__tests__/helpers.ts, src/agent/__tests__/Agent.test.ts, src/modules/connections/ConnectionsModule.ts, src/modules/routing/RecipientModule.ts, src/modules/routing/__tests__/RecipientService.test.ts, src/modules/routing/handlers/KeylistUpdateResponseHandler.ts, src/modules/routing/handlers/MediationDenyHandler.ts, src/modules/routing/handlers/MediationGrantHandler.ts, src/modules/routing/services/MediationRecipientService.ts, src/modules/routing/services/index.ts
Signed-off-by: Adam Burdett <burdettadam@gmail.com>
=> renamed RecipientService to MediationRecipientService

.github/workflows/continuous-integration.yml, packages/react-native/package.json, packages/react-native/src/index.ts
Some issues that I encountered using the new packages in our projects.
=> fix: monorepo release issues

.github/workflows/continuous-integration.yml
Placed it in the wrong job.. Need it in the release
=> ci: fetch all commits for correct versioning

packages/core/src/modules/proofs/ProofsModule.ts, packages/core/src/modules/proofs/services/ProofService.ts
=> fix: proof configurable on proofRecord

packages/core/tests/helpers.ts
this should hopefully fix the randomly failing tests. There were some weird promise calls causing timeouts...
=> test: fix test flakyness

.github/actions/setup-indy-pool/action.yml, DEVREADME.md, network/add-did-from-seed.sh, network/add-did.sh, packages/core/package.json, packages/core/src/modules/ledger/LedgerModule.ts, packages/core/src/modules/ledger/services/LedgerService.ts, packages/core/tests/ledger.test.ts, packages/react-native/package.json, yarn.lock
Add missing implementation for registerPublicDid in ledger module.
Apart from ledger source files, there were some updates in ledger setup scripts in order to properly run the tests, as it is needed to have some permissions to write public DIDs.
Signed-off-by: Ariel Gentile <gentilester@gmail.com>
=> feat(core): ledger module registerPublicDid implementation

packages/redux-store/src/store.ts
=> fix(redux-store): add reducers to initializeStore

packages/redux-store/src/slices/connections/connectionsSlice.ts, packages/redux-store/src/slices/connections/connectionsThunks.ts, packages/redux-store/src/slices/credentials/credentialsSlice.ts, packages/redux-store/src/slices/credentials/credentialsThunks.ts, packages/redux-store/src/slices/proofs/proofsSlice.ts, packages/redux-store/src/slices/proofs/proofsThunks.ts
- Able to delete credentialRecord and proofRecord like the connectionRecord
=> feat(redux-store): delete credentialRecord and proofRecord

README.md
Signed-off-by: Ana Goessens <anagoessens@gmail.com>
=> docs: added info on wgc to readme

packages/core/src/modules/routing/RecipientModule.ts
Was filtering based on our did doc, not theirs....
=> fix: their did doc not ours

packages/core/src/index.ts, packages/core/src/wallet/IndyWallet.ts, packages/core/src/wallet/error/WalletInvalidKeyError.ts, packages/core/src/wallet/error/index.ts
=> feat!: throw invalid key instead of wallet error

packages/core/src/storage/BaseRecord.ts
=> fix: make records serializable

packages/core/src/modules/proofs/models/AttributeFilter.ts
=> fix: add option check to attribute constructor

packages/core/src/agent/AgentMessage.ts, packages/core/src/agent/EnvelopeService.ts, packages/core/src/agent/__tests__/AgentMessage.test.ts, packages/core/src/modules/connections/messages/ConnectionInvitationMessage.ts
=> fix: incorrect recip key with multi routing keys

packages/core/src/storage/BaseRecord.ts
Signed-off-by: Jan <jan@animo.id>
=> feat(core): add toJson method to baserecord

packages/core/package.json, packages/core/src/modules/connections/__tests__/ConnectionInvitationMessage.test.ts, packages/core/src/modules/connections/messages/ConnectionInvitationMessage.ts, packages/react-native/package.json, packages/react-native/src/index.ts, yarn.lock
- Took the advice of @TimoGlastra ans used query-string for parsing URLs.
=> fix(core): using query-string to parse URLs

docs/getting-started/0-agent.md
Considered all past comments and changes plus new AFJ framework mods on api's
=> docs: add agent setup

packages/core/src/modules/connections/messages/ConnectionInvitationMessage.ts
=> fix(core): remove unused url import

README.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> docs: fix meeting time in readme and add link to meetings page

packages/node/bin/is-indy-installed.js, packages/node/package.json
=> feat(node): add is-indy-installed command

README.md
Signed-off-by: Ana Goessens <anagoessens@gmail.com>
=> docs: added info on ext to readme

packages/core/src/transport/HttpOutboundTransport.ts
=> fix(core): do not throw error on timeout in http

docs/libindy/linux.md, docs/libindy/macos.md, docs/setup-electron.md
- Improved the setup guide for electron
- Added some information to the macos part of the libindy setup 
- M1 still needs some work...
=> docs: improved electron setup 

packages/core/src/modules/basic-messages/BasicMessageEvents.ts, packages/core/src/modules/basic-messages/__tests__/BasicMessageService.test.ts, packages/core/src/modules/basic-messages/services/BasicMessageService.ts, packages/core/tests/helpers.ts
Signed-off-by: NeilSMyers <mmyersneil@gmail.com>
Created BasicMessageSentEvent. created in tandem with an update to AFJ/react-hooks and will need to be merged before that PR can be
=> feat(core)!: added basic message sent event

packages/core/src/agent/Dispatcher.ts
=> fix: include error when message cannot be handled

packages/core/src/modules/proofs/models/ProofRequest.ts
Signed-off-by: janrtvld <jan@animo.id>
=> refactor(core): allow map or record on proof request

packages/node/bin/is-indy-installed.js
- fix(node): added node v12 support for libindy check
- fix(node): node v12 did not support randomUUID()
=> fix(node): node v12 support for is-indy-installed

packages/core/src/types.ts
=> fix(core): expose record metadata types

.eslintrc.js, packages/core/src/utils/base58.ts
=> style: non-null assertions and newline import

packages/core/src/agent/__tests__/Dispatcher.test.ts
=> chore: disable unnecessary type check in Dispatcher test

packages/core/src/modules/connections/ConnectionsModule.ts, packages/core/src/modules/connections/services/ConnectionService.ts
Related to #583 
I'm already using these changes in OOB implementation #531 but I wanted to create separate PR.
=> feat(core): allow to set auto accept connetion exchange when accepting invitation

.github/workflows/continuous-deployment.yml
=> ci: prepend v to alpha releases for consistency

packages/core/src/modules/proofs/services/ProofService.ts
=> refactor(proofs): remove unused method from service

packages/core/src/agent/Agent.ts
start and stop transports in parallel as suggested by @jakubkoci  in https://github.com/hyperledger/aries-framework-javascript/pull/704#discussion_r849258130
I've grouped the inbound / outbound so we they're all running in parallel
=> refactor: start and stop transports in parallel

.github/actions/setup-postgres-wallet-plugin/action.yml, .github/actions/setup-postgres/action.yml, .github/workflows/continuous-integration.yml
-  Added ci setup for Postgres
Related Issue: #553 
Related PR for feature: #699
=> ci: add yml for postgres setup

packages/core/src/agent/Dispatcher.ts, packages/core/src/agent/EnvelopeService.ts, packages/core/src/agent/MessageReceiver.ts, packages/core/src/agent/MessageSender.ts, packages/core/src/agent/__tests__/MessageSender.test.ts, packages/core/src/agent/models/InboundMessageContext.ts, packages/core/src/modules/basic-messages/__tests__/BasicMessageService.test.ts, packages/core/src/modules/connections/ConnectionsModule.ts, packages/core/src/modules/connections/DidExchangeProtocol.ts, packages/core/src/modules/connections/__tests__/ConnectionService.test.ts, packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts, packages/core/src/modules/connections/handlers/ConnectionResponseHandler.ts, packages/core/src/modules/connections/handlers/DidExchangeRequestHandler.ts, packages/core/src/modules/connections/handlers/DidExchangeResponseHandler.ts, packages/core/src/modules/connections/handlers/TrustPingMessageHandler.ts, packages/core/src/modules/connections/services/ConnectionService.ts, packages/core/src/modules/dids/DidsModule.ts, packages/core/src/modules/dids/domain/createPeerDidFromServices.ts, packages/core/src/modules/dids/helpers.ts, packages/core/src/modules/dids/repository/DidRepository.ts, packages/core/src/modules/oob/OutOfBandModule.ts, packages/core/src/modules/routing/__tests__/mediation.test.ts, packages/core/src/modules/routing/handlers/KeylistUpdateResponseHandler.ts, packages/core/src/modules/routing/handlers/MediationDenyHandler.ts, packages/core/src/modules/routing/handlers/MediationGrantHandler.ts, packages/core/src/modules/routing/handlers/MediationRequestHandler.ts, packages/core/src/types.ts, packages/core/src/wallet/IndyWallet.ts, packages/core/src/wallet/Wallet.ts
=> feat: use did keys for oob and did exchange protocols

packages/core/src/modules/common/messages/AckMessage.ts, packages/core/src/modules/common/messages/CommonMessageType.ts
=> refactor: replace message type constant with string literal

packages/core/src/modules/connections/DidExchangeProtocol.ts
=> fix: add oob state and role check

packages/core/src/modules/routing/RecipientModule.ts
=> fix(routing): also use pickup strategy from config

packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
=> fix(credentials): store revocation identifiers

DEVREADME.md
adds some hints for debugging running tests
Signed-off-by: Moriarty <moritz@animo.id>
=> docs: update developer readme

packages/core/src/modules/credentials/CredentialsModuleOptions.ts
Just to make the type a bit simpler
=> refactor(credentials): remove formats for version

.github/workflows/continuous-deployment.yml, .github/workflows/continuous-integration.yml
=> ci: fix next version bump variable

.github/workflows/continuous-deployment.yml, .github/workflows/continuous-integration.yml
=> ci: fix next version bump output

demo/package.json, packages/core/package.json, packages/react-native/package.json, samples/extension-module/package.json, yarn.lock
=> chore: update afj dependencies

packages/core/src/storage/Repository.ts
=> fix: clone record before emitting event

CONTRIBUTING.md
see https://github.com/hyperledger/aries-framework-javascript/issues/918
=> docs: initial contributing checklist

MAINTAINERS.md
I somehow directly pushed to main and now messed up the prettier formatting. I restricted the branch protection to make sure it doesn't happen again. This PR fixes the prettier formatting.
=> style: prettier formatting

.github/actions/setup-postgres-wallet-plugin/action.yml, Dockerfile
Signed-off-by: Sai Ranjit Tummalapalli <sairanjit5@gmail.com>
=> ci: set default rust version

packages/action-menu/package.json, packages/question-answer/package.json
Signed-off-by: Ariel Gentile <gentilester@gmail.com>
=> chore: make action-menu and question-answer public

packages/core/src/modules/proofs/protocol/v2/V2ProofService.ts, packages/core/src/modules/proofs/repository/PresentationExchangeRecord.ts, packages/core/src/modules/proofs/repository/index.ts
Signed-off-by: Jim Ezesinachi <ezesinachijim@gmail.com>
=> chore: deleted PresentationExchangeRecord.ts

packages/core/src/modules/common/messages/AckMessage.ts
Signed-off-by: Jim Ezesinachi <jim@animo.id>
=> refactor: remove ACK status type of fail

packages/indy-sdk/package.json
=> build(indy-sdk): set private to false

samples/extension-module/dummy/messages/DummyResponseMessage.ts
Remove suspicious reference to 2060.io in `DummyResponseMessage`
=> fix(samples): dummy module response message type

packages/core/src/agent/BaseAgent.ts
Closes hyperledger/aries-framework-javascript#1242
=> refactor(core)!: remove deprecated injectionContainer prop

packages/indy-sdk/src/ledger/IndySdkPoolService.ts, packages/indy-vdr/src/pool/IndyVdrPoolService.ts
Not much use to a cache if the key to set is different from the key to retrieve :)
=> fix: did cache key not being set correctly

packages/askar/tests/helpers.ts, packages/core/tests/helpers.ts
Randomize wallet Ids in Askar E2E tests. Also randomize Indy Postgres wallets just in case more tests are added in the future.
=> test: randomize askar wallet ids

.github/workflows/continuous-integration.yml
=> build: test large builders 

.github/actions/setup-cheqd/action.yml, .github/workflows/continuous-integration.yml, README.md, demo/package.json, demo/src/BaseAgent.ts, demo/src/Faber.ts, demo/src/FaberInquirer.ts, packages/cheqd/README.md, packages/cheqd/src/anoncreds/services/CheqdAnonCredsRegistry.ts, packages/cheqd/tests/cheqd-did-resolver.e2e.test.ts, packages/cheqd/tests/cheqd-sdk-anoncreds-registry.e2e.test.ts, packages/cheqd/tests/setupCheqdModule.ts
This PR adds the required Readme files and integrates cheqd modules in the demo
Also included a setup-cheqd in ./.github/actions which starts a localnet for the tests to be run
=> feat: Add cheqd demo and localnet for tests

packages/core/src/modules/vc/signature-suites/ed25519/Ed25519Signature2018.ts
We got some errors for a did document that didn't conform, but they weren't very helpful (hiding the actual error).
=> chore: improve ed25519 context url checks

DEVREADME.md
Fixed links for setting up an indy ledger.
=> docs: Update DEVREADME.md setup-indy-ledger links

.github/workflows/continuous-deployment.yml
Explicitly set npm registry in order to attempt to fix #1518
=> ci: set npm registry for releases

packages/cheqd/tests/setupCheqdModule.ts, packages/core/src/modules/credentials/protocol/v2/__tests__/v2.ldproof.credentials.propose-offerED25519.test.ts, packages/core/src/modules/dids/DidsModuleConfig.ts, packages/core/src/modules/dids/__tests__/DidsModuleConfig.test.ts, packages/indy-sdk/tests/setupIndySdkModule.ts
=> fix: force did:key resolver/registrar presence

packages/core/src/agent/Agent.ts
mediation initialization was happening before the message subscription was registered, thus meaning the received messages to provision the mediator wouldn't be processed. This moves it to the start of the initialize method, before mediation initialization
=> fix: create message subscription first

packages/core/src/modules/connections/__tests__/helpers.test.ts, packages/core/src/modules/connections/models/did/DidDoc.ts, packages/core/src/modules/connections/models/did/__tests__/DidDoc.test.ts, packages/core/src/modules/connections/services/helpers.ts, packages/core/src/modules/dids/domain/DidDocument.ts, packages/core/src/modules/dids/domain/__tests__/DidDocument.test.ts, packages/core/src/types.ts
=> fix: priority sorting for didcomm services

packages/cheqd/src/anoncreds/services/CheqdAnonCredsRegistry.ts
For more information about these changes, see: https://cheqd-community.slack.com/archives/C02AQ9UK4HY/p1693916571308369
=> fix(cheqd): Changed the name formatting to a encoded hex value

packages/core/src/modules/dids/domain/DidDocument.ts
=> fix(core): allow string for did document controller

.github/workflows/continuous-deployment.yml
@genaris the magic sauce to fix CI hopefully
=> ci: change secret

demo/package.json, package.json, packages/anoncreds-rs/package.json, packages/askar/package.json, packages/indy-sdk-to-askar-migration/package.json, packages/sd-jwt-vc/package.json, yarn.lock
Updates all shared components to the latest version so we can test them before making a stable release.
Going to try it out with the Paradym Wallet afterwards as well to make sure everything works in React Native
=> chore: update shared components libraries

packages/core/src/modules/proofs/formats/dif-presentation-exchange/DifPresentationExchangeProofFormatService.ts
- Removed a check for `DifPresentationExchangeService` dependency
- Fixes the issue for the `presentationExchange` proof format in the multitenancy
=> fix: remove check for DifPresentationExchangeService dependency

README.md, packages/action-menu/README.md, packages/anoncreds-rs/README.md, packages/anoncreds/README.md, packages/askar/README.md, packages/bbs-signatures/README.md, packages/cheqd/README.md, packages/core/README.md, packages/indy-sdk-to-askar-migration/README.md, packages/indy-sdk/README.md, packages/indy-vdr/README.md, packages/node/README.md, packages/openid4vc-client/README.md, packages/question-answer/README.md, packages/react-native/README.md, packages/sd-jwt-vc/README.md, packages/tenants/README.md
Replaces the Aries logo in all READMEs
=> refactor: replace Aries logo

packages/tenants/src/TenantsApi.ts, packages/tenants/src/__tests__/TenantsApi.test.ts, packages/tenants/src/services/TenantRecordService.ts
=> feat(tenants): expose get all tenants on public API

packages/bbs-signatures/tests/bbs-signing-provider.e2e.test.ts, packages/core/src/modules/message-pickup/protocol/v1/V1MessagePickupProtocol.ts
=> fix: unused imports

packages/anoncreds/src/formats/AnonCredsCredentialFormatService.ts, packages/anoncreds/src/formats/AnonCredsProofFormatService.ts, packages/anoncreds/src/formats/LegacyIndyProofFormatService.ts
=> fix(anoncreds): allow for zero idx to be used for revocation

packages/react-native/package.json
Fixes https://github.com/openwallet-foundation/credo-ts/issues/1635
=> fix(rn): more flexible react native version

demo-openid/package.json, demo/package.json, package.json, packages/anoncreds/package.json, packages/askar/package.json, packages/indy-sdk-to-askar-migration/package.json, packages/indy-vdr/package.json, samples/extension-module/package.json, yarn.lock
Updates the shared components deps to stable 0.2 versions
=> chore: update shared components to stable release

.github/dependabot.yml
- Update comments
- Group all updates into a single PR.
=> chore: Update Dependabot configuration

.devcontainer/devcontainer.json
- Update the dev container configuration.
- Install the Prettier - Code formatter extension.
- Perform a `yarn install` to initialize the development environment.
=> feat: New developer quality of life updates

packages/cheqd/package.json, yarn.lock
=> build: update cheqd

packages/core/src/modules/connections/ConnectionsApi.ts
As discussed at today's meeting
=> fix: remove mediation keys after hangup

packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierService.ts
just a simple log to help when verification fails
=> chore: add log

packages/anoncreds/src/utils/proofRequest.ts, packages/core/src/modules/proofs/protocol/v2/__tests__/v2-anoncreds-unqualified-proofs.e2e.test.ts
Simple fix for below issue, following the existing pattern:
- https://github.com/openwallet-foundation/credo-ts/issues/1906
I think this is my first Credo PR so forgive me for any blunders
=> fix: anoncreds predicate only proof with unqualified dids

.changeset/wet-tools-drum.md, .github/workflows/release.yml, CHANGELOG.md, packages/action-menu/CHANGELOG.md, packages/anoncreds/CHANGELOG.md, packages/askar/CHANGELOG.md, packages/bbs-signatures/CHANGELOG.md, packages/cheqd/CHANGELOG.md, packages/core/CHANGELOG.md, packages/drpc/CHANGELOG.md, packages/indy-sdk-to-askar-migration/CHANGELOG.md, packages/indy-vdr/CHANGELOG.md, packages/node/CHANGELOG.md, packages/openid4vc/CHANGELOG.md, packages/question-answer/CHANGELOG.md, packages/react-native/CHANGELOG.md, packages/tenants/CHANGELOG.md
=> fix: minor should be patch

.github/workflows/continuous-integration.yml
See https://github.com/actions/setup-node/issues/641
=> ci: set pnpm cache key

demo-openid/package.json, demo/package.json, package.json, packages/askar/package.json, packages/askar/src/utils/askarKeyBackend.ts, packages/askar/src/wallet/AskarBaseWallet.ts, packages/askar/src/wallet/__tests__/AskarWallet.test.ts, packages/core/src/crypto/KeyBackend.ts, packages/core/src/crypto/index.ts, packages/core/src/wallet/Wallet.ts, packages/indy-sdk-to-askar-migration/package.json, pnpm-lock.yaml, samples/extension-module/package.json, tests/InMemoryWallet.ts
- Waiting for the GH release of askar.
=> feat(askar): create keys in the secure element

.github/workflows/release.yml
Only works when base of PR is this repo and label `alpha-release` is added to the PR
=> feat: release alpha from PR

.changeset/chatty-pens-hope.md, .changeset/four-dodos-smoke.md, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderServiceOptions.ts
=> fix: several oid4vc fixes

.changeset/six-geese-pull.md, packages/cheqd/src/CheqdApi.ts, packages/cheqd/src/CheqdModule.ts, packages/cheqd/src/dids/CheqdDidRegistrar.ts, pnpm-lock.yaml
This PR introduces the exposure of the `createResource` function from the `CheqdDidRegistrar` class using `CheqdApi` class, enabling the creation of custom DID-Linked Resources (DLRs). With this enhancement, users can now create and manage DLRs such as trust registries, images, files, and other custom resources as needed.
=> feat(cheqd): Add CheqdApi

packages/core/src/modules/mdoc/__tests__/mdoc.service.test.ts, packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierService.ts, packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierServiceOptions.ts, packages/openid4vc/src/shared/models/OpenId4VcJwtIssuer.ts, packages/openid4vc/src/shared/utils.ts, packages/openid4vc/tests/openid4vc.e2e.test.ts
=> feat: optional x5c issuer field

packages/openid4vc/src/openid4vc-holder/OpenId4VcHolderApi.ts, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderServiceOptions.ts, packages/openid4vc/src/shared/models/index.ts
small change to return access token response and check for bath issuance before creating holder binding
=> chore: return access token response

packages/core/src/modules/x509/X509Certificate.ts, packages/core/src/modules/x509/X509ServiceOptions.ts, packages/core/src/modules/x509/__tests__/X509Service.test.ts
=> feat(x509): able to add Certificate Authority Key Identifier to self-signed certificates

packages/core/src/modules/x509/X509Certificate.ts, packages/core/src/modules/x509/__tests__/X509Service.test.ts
=> feat(x509): add key usage to X.509 certificate

packages/core/src/modules/x509/X509Certificate.ts
=> fix(x509): encode key usages as a bit string

packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts
We should get a new key for each credential
=> fix: batch keys

.changeset/six-phones-marry.md, packages/core/src/modules/mdoc/MdocDeviceResponse.ts, packages/core/src/modules/mdoc/MdocOptions.ts, packages/core/src/modules/mdoc/MdocService.ts, packages/core/src/modules/mdoc/__tests__/mdocProximityDeviceResponse.test.ts
=> feat: support device response with multiple mdocs

.changeset/serious-rivers-clap.md, packages/askar/src/wallet/AskarBaseWallet.ts, packages/askar/src/wallet/__tests__/AskarWallet.test.ts, packages/core/src/wallet/Wallet.ts, packages/openid4vc/src/openid4vc-holder/OpenId4vcSiopHolderService.ts
This is used by the french playground. Kept it very simple as this is already implemented more generically in the KMS branch
=> feat: support A128CBC-HS256 encryption algorithm for JWE

packages/core/package.json, pnpm-lock.yaml
=> chore: update ec-compression

packages/core/src/modules/mdoc/index.ts
- export date only from animo-id/mdoc
=> chore(mdoc): export DateOnly from @animo-id/mdoc

.changeset/mighty-jars-pay.md, packages/core/src/modules/x509/X509Certificate.ts, packages/core/src/modules/x509/X509ServiceOptions.ts, packages/core/src/modules/x509/__tests__/X509Service.test.ts, packages/core/src/modules/x509/extensions/IssuerAlternativeNameExtension.ts, packages/core/src/modules/x509/utils/extensions.ts
=> fix(x509): ready for IACA + DCS mdoc

.changeset/big-ears-dream.md, packages/core/src/modules/x509/X509Service.ts, packages/core/src/modules/x509/__tests__/X509Service.test.ts
… the root certificate is not included in the certificate chain but present in the trusted certificates
=> fix: support verification of certificate chain without root

packages/didcomm/src/modules/connections/ConnectionsModuleConfig.ts
=> fix: update default

biome.json, packages/askar/src/secureEnvironment/secureEnvironment.native.ts, packages/bbs-signatures/src/signature-suites/BbsBlsSignature2020.ts, packages/bbs-signatures/src/signature-suites/BbsBlsSignatureProof2020.ts, packages/core/src/modules/mdoc/Mdoc.ts, packages/core/src/modules/vc/data-integrity/deriveProof.ts, packages/core/src/modules/vc/data-integrity/jsonldUtil.ts, packages/core/src/modules/vc/data-integrity/libraries/nativeDocumentLoader.native.ts, packages/core/src/modules/vc/data-integrity/libraries/nativeDocumentLoader.ts, packages/core/src/modules/vc/jwt-vc/__tests__/W3cJwtCredentialService.test.ts, packages/core/src/modules/vc/jwt-vc/credentialTransformer.ts, packages/core/src/modules/vc/jwt-vc/presentationTransformer.ts, packages/didcomm/src/modules/connections/__tests__/ConnectionRequestMessage.test.ts, packages/didcomm/src/modules/proofs/protocol/v2/__tests__/v2-indy-proof-negotiation.e2e.test.ts, packages/didcomm/src/updates/0.1-0.2/connection.ts, packages/didcomm/src/updates/0.1-0.2/credential.ts, tests/InMemoryStorageService.ts
Removes all warnings to not clutter the output with existing code.
=> chore: remove warnings

demo-openid/package.json, demo/package.json, packages/anoncreds/package.json, pnpm-lock.yaml
=> chore: update anoncreds dependencies

packages/core/src/modules/connections/DidExchangeProtocol.ts
Backporting a fix done in #2166  (and the following fix in #2229) to 0.5.x branch.
It touches only resolvable did use cases (did:peer:4 and public dids), leaving intact the typical did:peer:1 cases (if it works, don't touch it!).
For the moment I'm testing it with success in 0.5.13 agents, using did:peer:4 by default in DID Exchange requests.
=> fix: didRotate signature in DID Exchange Response

packages/core/package.json, pnpm-lock.yaml
=> chore: update ec-compression library

packages/anoncreds/src/anoncreds-rs/AnonCredsRsHolderService.ts
Tiny fix for a bug we found while testing this patch
=> fix: assign proper rev_reg_id

packages/core/package.json
- Add missing `test` script in core package
=> chore: add missing test script in package-core

docker-compose.arm.yml, docker-compose.yml, packages/cheqd/package.json, packages/cheqd/src/anoncreds/services/CheqdAnonCredsRegistry.ts, packages/cheqd/src/anoncreds/utils/identifiers.ts, packages/cheqd/tests/cheqd-did-registrar.e2e.test.ts, packages/core/src/modules/dids/domain/DidDocumentBuilder.ts, pnpm-lock.yaml
Adding this PR for backwards compatibility for breaking changes in cheqd
=> chore(cheqd): Bump @cheqd/sdk

.changeset/eleven-numbers-jam.md, .changeset/popular-walls-add.md, .changeset/purple-donkeys-camp.md
was causing issues in the CI pipeline
=> chore: remove bbs from changeset

.changeset/stupid-beans-glow.md, .github/workflows/continuous-integration.yml, .gitignore, packages/core/src/transport/WsOutboundTransport.ts, packages/openid4vc/src/openid4vc-holder/__tests__/openid4vci-holder.test.ts
=> fix: use socket methods defined in react native (backport #2152)

packages/core/src/agent/Agent.ts
=> fix: support receivedAt in DIDComm message receiver

.changeset/spicy-parents-enjoy.md, packages/core/src/crypto/hashes/Hasher.ts, packages/core/src/crypto/hashes/Sha1.ts, packages/core/src/crypto/hashes/Sha256.ts, packages/core/src/crypto/hashes/Sha512.ts, packages/core/src/crypto/hashes/index.ts, packages/core/src/utils/MultiHashEncoder.ts
Also updating deprecated imports in sha-1/sha-256
=> feat(core): support sha-512 in Hasher

.changeset/clean-ways-serve.md, packages/openid4vc/package.json, packages/openid4vc/src/openid4vc-holder/OpenId4VcHolderApi.ts, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderService.ts, packages/openid4vc/src/openid4vc-holder/OpenId4VciHolderServiceOptions.ts, packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerModuleConfig.ts, packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerService.ts, packages/openid4vc/src/openid4vc-issuer/OpenId4VcIssuerServiceOptions.ts, packages/openid4vc/src/openid4vc-issuer/repository/OpenId4VcIssuanceSessionRecord.ts, packages/openid4vc/src/openid4vc-issuer/router/accessTokenEndpoint.ts, packages/openid4vc/src/openid4vc-issuer/router/authorizationChallengeEndpoint.ts, packages/openid4vc/src/openid4vc-issuer/router/issuerMetadataEndpoint.ts, packages/openid4vc/src/shared/callbacks.ts, packages/openid4vc/tests/openid4vci-deferred.e2e.test.ts, pnpm-lock.yaml
Adds support for refresh tokens in the OpenID4VC server/client.
=> feat(openid4vc): add refresh token support

packages/webvh/package.json, pnpm-lock.yaml
=> chore: update didwebvh-ts to version 2.5.2 in package.json

packages/webvh/package.json, pnpm-lock.yaml
=> chore: update didwebvh-ts and json-canonicalize

packages/webvh/src/dids/WebvhDidResolver.ts
Currently it is not properly getting document context due to this lack of JSON transformation.
=> fix(webvh): DID Document resolution (backport of #2389)

packages/webvh/src/dids/WebvhDidResolver.ts
Currently it is not properly getting document context due to this lack of JSON transformation.
=> fix(webvh): DID Document resolution

packages/didcomm/src/modules/message-pickup/MessagePickupSession.ts, packages/didcomm/src/modules/message-pickup/__tests__/MessagePickupSessionService.test.ts, packages/didcomm/src/modules/message-pickup/protocol/v2/V2MessagePickupProtocol.ts, packages/didcomm/src/modules/message-pickup/services/MessagePickupSessionService.ts
Some improvements after feedback on #2399
=> refactor(didcomm): filter by transport session id in message pickup

packages/webvh/src/anoncreds/services/WebVhAnonCredsRegistry.ts, packages/webvh/src/anoncreds/services/__tests__/WebVhTransform.test.ts, packages/webvh/src/anoncreds/services/__tests__/mock-resources.ts, packages/webvh/src/dids/WebVhDidRegistrar.ts
This PR updates the WebVH context and introduces support for creating a new DID type using the updated multikey format.
=> fix(webvh): update context webvh and create did type
